---
permalink: api-automation/concept_manage_access_endpoint.html 
sidebar: sidebar 
keywords: manage, endpoints, access 
summary: 您需要建立存取端點或邏輯介面（LIF）、這些都是資源配置儲存虛擬機器（SVM）、LUN和檔案共用所需的。您可以檢視、建立、修改及刪除Active IQ Unified Manager 您的SVM、LUN或檔案共享區的存取端點。 
---
= 使用 API 管理存取端點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要建立存取端點或邏輯介面（LIF）、這些都是資源配置儲存虛擬機器（SVM）、LUN和檔案共用所需的。您可以檢視、建立、修改及刪除Active IQ Unified Manager 您的SVM、LUN或檔案共享區的存取端點。



== 檢視存取端點

您可以使用下列方法、檢視Unified Manager環境中的存取端點清單。若要查詢特定SVM、LUN或檔案共用區的存取端點清單、您必須輸入SVM、LUN或檔案共用區的唯一識別碼。您也可以輸入唯一的存取端點金鑰、以擷取特定存取端點的詳細資料。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
取得
 a| 
「/儲存設備供應商/存取端點」

儲存設備供應商/存取端點/\｛key｝

|===


== 新增存取端點

您可以建立自訂存取端點、並將必要的內容指派給它。您必須輸入要建立為輸入參數的存取端點詳細資料。您可以使用此API、或是System Manager或ONTAP ECLI、在每個節點上建立存取端點。建立存取端點時、同時支援IPv6和IPv6位址。

[NOTE]
====
您必須為SVM設定每個節點的存取端點數量下限、才能成功配置LUN和檔案共用。您應該為SVM設定每個節點至少兩個存取端點、一個支援CIFS和/或NFS傳輸協定、另一個支援iSCSI或FCP傳輸協定。

====
[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
貼文
 a| 
「/儲存設備供應商/存取端點」

|===


== 刪除存取端點

您可以使用下列方法刪除特定的存取端點。您必須提供存取端點金鑰作為輸入參數、才能刪除特定的存取端點。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
刪除
 a| 
儲存設備供應商/存取端點/\｛key｝

|===


== 修改存取端點

您可以使用下列方法修改存取端點並更新其內容。您需要提供存取端點金鑰、才能修改特定的存取端點。您也需要輸入要更新的屬性及其值。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
修補程式
 a| 
儲存設備供應商/存取端點/\｛key｝

|===