---
permalink: api-automation/concept_data_center_apis.html 
sidebar: sidebar 
keywords: manage, storage, objects, data center 
summary: 資料中心類別下的REST API可讓您管理資料中心內的儲存物件、例如叢集、節點、集合體、儲存VM、 磁碟區、LUN、檔案共用區和命名空間。這些API可用於查詢物件的組態、有些API則可讓您執行新增、刪除或修改這些物件的作業。 
---
= 使用 API 管理資料中心內的儲存對象
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
其餘API則位於「datacentre」類別、可讓您管理資料中心內的儲存物件、例如叢集、節點、集合體、儲存VM、 磁碟區、LUN、檔案共用區和命名空間。這些API可用於查詢物件的組態、有些API則可讓您執行新增、刪除或修改這些物件的作業。

這些API大多是透過篩選、排序和分頁支援、提供跨叢集集合的Get呼叫。在執行這些API時、它們會從資料庫傳回資料。因此、新建立的物件需要在下一個擷取週期中探索、才能顯示在回應中。

若要查詢特定物件的詳細資料、您必須輸入該物件的唯一識別碼、才能檢視其詳細資料。例如、如需儲存物件的度量和分析資訊、請參閱 link:concept_metrics_apis.html["檢視效能指標"]。

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
您可以在Swagger API介面上使用Curl命令、範例、要求和API回應。您可以依照Swagger所示的特定參數來篩選及排序結果。這些API可讓您篩選特定儲存物件（例如叢集、Volume或儲存VM）的結果。

====


== 資料中心儲存物件的API

[cols="3*"]
|===
| HTTP動詞 | 路徑 | 說明 


 a| 
《 Get 》（取得）
 a| 
資料中心/叢集/叢集

「/資料中心/叢集/叢集/\｛key｝」
 a| 
您可以使用此方法來檢視ONTAP 整個資料中心內的各個叢集詳細資料。API會傳回諸如叢集的IPv4或IPv6位址、節點相關資訊（例如節點健全狀況、效能容量和高可用度（HA）配對）、並指出叢集是否為All SAN Array。



 a| 
《 Get 》（取得）
 a| 
資料中心/叢集/授權/授權/資料中心/叢集/授權/授權/\｛key｝
 a| 
傳回資料中心叢集上安裝的授權詳細資料。您可以根據所需的條件篩選結果。傳回授權金鑰、叢集金鑰、到期日及授權範圍等資訊。您可以輸入授權金鑰、以擷取特定授權的詳細資料。



 a| 
《 Get 》（取得）
 a| 
資料中心/叢集/節點

「/資料中心/叢集/節點/\｛key｝」
 a| 
您可以使用此方法來檢視資料中心節點的詳細資料。您可以檢視節點的叢集、節點健全狀況、效能容量和高可用度（HA）配對相關資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/傳輸協定/CIFS/共享 區

資料中心/傳輸協定/CIFS/共享/\｛key｝
 a| 
您可以使用此方法來檢視資料中心內CIFS共用的詳細資料。除了叢集、SVM和Volume詳細資料之外、也會傳回存取控制清單（ACL）的相關資訊。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/傳輸協定/NFS/匯 出原則」

資料中心/傳輸協定/NFS/EXport-Policies /\｛key｝
 a| 
您可以使用此方法來檢視支援NFS服務的匯出原則詳細資料。

您可以查詢叢集或儲存VM的匯出原則、然後重複使用匯出原則金鑰來配置NFS檔案共用。如需指派及重複使用工作負載上匯出原則的詳細資訊、請參閱「Provisioning CIFS and NFS file共享」。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存/集合體

「/資料中心/儲存/集合體/\｛key｝」
 a| 
您可以使用此方法來檢視資料中心的集合體、或是特定的集合體、以便在其上配置或監控工作負載。傳回的資訊包括叢集和節點詳細資料、使用的效能容量、可用空間和已用空間、以及儲存效率。



 a| 
《 Get 》（取得）
 a| 
/'資料中心/儲存設備/LUN'

「/資料中心/儲存設備/LUNs/\｛key｝」
 a| 
您可以使用此方法來檢視整個資料中心的LUN集合。您可以檢視LUN的相關資訊、例如叢集與SVM詳細資料、QoS原則及igroup。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存設備/ QoS /原則

「/資料中心/儲存設備/ QoS /原則/\｛key｝」
 a| 
您可以使用此方法來檢視適用於資料中心儲存物件的所有QoS原則詳細資料。系統會傳回叢集與SVM詳細資料、固定或調適原則詳細資料、以及適用於該原則的物件數目等資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存設備/ qtree

「/資料中心/儲存設備/ qtree /\｛key｝」
 a| 
您可以使用此方法來檢視所有FlexVol 資料中心的qtree詳細資料、以瞭解所有的景區或FlexGroup 是景區。系統會傳回叢集與SVM詳細資料、FlexVol S大批 量及匯出原則等資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存/磁碟區

「/資料中心/儲存設備/磁碟區/｛key｝」
 a| 
您可以使用此方法來檢視資料中心內的Volume集合。傳回磁碟區的相關資訊、例如SVM和叢集詳細資料、QoS和匯出原則、無論磁碟區類型為讀寫、資料保護或負載共用。

對於FlexClone和FlexClone磁碟區、您可以檢視個別集合體的相關資訊。FlexVol若為FlexGroup 某個數據區、查詢會傳回組成集合體的清單。



 a| 
《 Get 》（取得）

貼文

" 刪除 "

《修補程式》
 a| 
資料中心/傳輸協定/ SAN / igroup

資料中心/傳輸協定/ SAN / igroups/{key}
 a| 
您可以指派授權存取特定LUN目標的啟動器群組（igroup）。如果有現有的igroup、您可以指派它。您也可以建立igroup並將其指派給LUN。

您可以使用這些方法分別查詢、建立、刪除及修改igroup。

請注意：

* 「POST：」建立igroup時、您可以指定要指派存取權的儲存VM。
* 「刪除：」您需要提供igroup金鑰作為輸入參數、以刪除特定的igroup。如果已將igroup指派給LUN、則無法刪除該igroup。
* 「修補程式：」您需要提供igroup金鑰作為輸入參數、以修改特定的igroup。您也必須輸入要更新的屬性及其值。




 a| 
《 Get 》（取得）

貼文

" 刪除 "

《修補程式》
 a| 
「/資料中心/ SVM/svms」

資料中心/ SVM/svms/\{key}
 a| 
您可以使用這些方法來檢視、建立、刪除及修改儲存虛擬機器（儲存VM）。

* 「POST：」您必須輸入要建立為輸入參數的儲存VM物件。您可以建立自訂的儲存VM、然後將必要的內容指派給它。
* 「刪除：」您需要提供儲存VM金鑰、才能刪除特定的儲存VM。
* 「修補程式：」您需要提供儲存VM金鑰來修改特定的儲存VM。您也需要輸入要更新的屬性及其值。


|===

NOTE: 請注意：

如果您已在環境中啟用SLO型工作負載資源配置、同時建立儲存VM、請確定它支援所有必要的傳輸協定、以便在其中配置LUN和檔案共用、例如CIFS或SMB、NFS、FCP、 和iSCSI。如果儲存VM不支援所需的服務、資源配置工作流程可能會失敗。建議也在儲存VM上啟用個別工作負載類型的服務。

如果您已在環境中啟用SLO型工作負載資源配置、則無法刪除已配置儲存工作負載的儲存VM。刪除已設定CIFS或SMB伺服器的儲存VM時、此API也會刪除CIFS或SMB伺服器、以及本機Active Directory組態。不過、CIFS或SMB伺服器名稱仍在Active Directory組態中、您必須從Active Directory伺服器手動刪除。



== 資料中心網路元素的API

資料中心類別中的下列API會擷取環境中連接埠和網路介面的相關資訊、尤其是FC連接埠、FC介面、乙太網路連接埠和IP介面。

[cols="3*"]
|===
| HTTP動詞 | 路徑 | 說明 


 a| 
《 Get 》（取得）
 a| 
資料中心/網路/乙太網路/連接埠

「/資料中心/網路/乙太網路/連接埠/｛key｝」
 a| 
擷取資料中心環境中所有乙太網路連接埠的相關資訊。使用連接埠金鑰做為輸入參數、您可以檢視該特定連接埠的資訊。資訊、例如叢集詳細資料、廣播網域、連接埠詳細資料、例如狀態、速度、 並擷取類型、以及是否已啟用連接埠。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/光纖通道/介面

「/資料中心/網路/光纖通道/介面/｛key｝」
 a| 
您可以使用此方法來檢視資料中心環境中FC介面的詳細資料。使用介面金鑰做為輸入參數、您可以檢視該特定介面的資訊。系統會擷取叢集詳細資料、主節點詳細資料及主連接埠詳細資料等資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/光纖通道/連接埠

「/資料中心/網路/光纖通道/連接埠/｛key｝」
 a| 
擷取資料中心環境中節點所使用的所有FC連接埠資訊。使用連接埠金鑰做為輸入參數、您可以檢視該特定連接埠的資訊。系統會擷取叢集詳細資料、連接埠說明、支援的傳輸協定及連接埠狀態等資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/IP/介面

「/資料中心/網路/IP/介面/｛key｝」
 a| 
您可以使用此方法來檢視資料中心環境中IP介面的詳細資料。使用介面金鑰做為輸入參數、您可以檢視該特定介面的資訊。系統會擷取叢集詳細資料、IPspace詳細資料、主節點詳細資料、以及是否啟用容錯移轉等資訊。

|===