---
permalink: api-automation/concept_manage_fileshares_api.html 
sidebar: sidebar 
keywords: manage, file, share 
summary: 您可以使用/storage供應商/檔案共用API來檢視、新增、修改及刪除資料中心環境中的CIFS和NFS檔案共用磁碟區。 
---
= 使用 API 管理文件共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「/storage供應商/檔案共用」API來檢視、新增、修改及刪除資料中心環境中的CIFS和NFS檔案共用磁碟區。

在資源配置檔案共用磁碟區之前、請先確認已建立SVM並以支援的傳輸協定進行資源配置。如果您要指派「效能服務層級」（PSL）或「儲存效率原則」（DDP）、則在進行資源配置時、應該先建立PSL或DDP、然後再建立檔案共用。



== 檢視檔案共用

您可以使用下列方法來檢視Unified Manager環境中可用的檔案共用磁碟區。在ONTAP 將一個叢集新增為Active IQ Unified Manager 資料來源的時候、這些叢集的儲存工作負載會自動新增至您的Unified Manager執行個體。此API會自動擷取檔案共用、並手動新增至Unified Manager執行個體。您可以使用檔案共用金鑰來執行此API、以檢視特定檔案共用區的詳細資料。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
取得
 a| 
「/儲存設備供應商/檔案共用」

儲存設備供應商/檔案共用/\｛key｝

|===


== 新增檔案共用

您可以使用下列方法在SVM中新增CIFS和NFS檔案共用。您必須輸入要建立的檔案共用詳細資料、做為輸入參數。您無法使用此API來新增FlexGroup 功能區。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
貼文
 a| 
「/儲存設備供應商/檔案共用」

|===
[NOTE]
====
視提供的存取控制清單（ACL）參數或匯出原則參數而定、會建立CIFS共用或NFS檔案共用。如果您未提供ACL參數的值、則不會建立CIFS共用、而且預設會建立NFS共用、以提供所有的存取權。

====
*建立資料保護磁碟區*：將檔案共用新增至SVM時、預設掛載的磁碟區類型為「rw」（讀寫）。若要建立資料保護（DP）磁碟區、請指定「dp」作為「type」參數的值。



== 刪除檔案共用

您可以使用下列方法刪除特定的檔案共用。您必須輸入檔案共用金鑰做為輸入參數、才能刪除特定的檔案共用區。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
刪除
 a| 
儲存設備供應商/檔案共用/\｛key｝

|===


== 修改檔案共用

您可以使用下列方法來修改檔案共用區並更新其內容。

您必須提供檔案共用金鑰、才能修改特定的檔案共用區。此外、您還需要輸入要更新的屬性及其值。

[NOTE]
====
請注意、您只能在單一呼叫此API時更新一個屬性。若要執行多個更新、您需要執行此API的次數不限。

====
[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
修補程式
 a| 
儲存設備供應商/檔案共用/\｛key｝

|===