---
permalink: api-automation/concept_manage_psl.html 
sidebar: sidebar 
keywords: manage, performance, service, level 
summary: 您可以使用Active IQ Unified Manager 適用於的儲存供應商API來檢視、建立、修改及刪除Performance Service層級。 
---
= 使用API管理效能服務層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Active IQ Unified Manager 適用於的儲存供應商API來檢視、建立、修改及刪除Performance Service層級。



== 檢視效能服務層級

您可以使用下列方法來檢視效能服務層級、將其指派給儲存工作負載。API會列出系統定義和使用者建立的所有Performance Service層級、並擷取所有Performance Service層級的屬性。若要查詢特定的效能服務層級、您必須輸入效能服務層級的唯一ID、才能擷取其詳細資料。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
取得
 a| 
「/儲存設備供應商/效能服務層級」

儲存設備供應商/效能服務層級/\｛key｝

|===


== 新增效能服務層級

如果系統定義的效能服務層級不符合儲存工作負載所需的服務層級目標（SLO）、您可以使用下列方法來建立自訂的效能服務層級、並將其指派給儲存工作負載。輸入您要建立之效能服務層級的詳細資料。針對IOPS內容、請務必輸入有效的值範圍。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
貼文
 a| 
「/儲存設備供應商/效能服務層級」

|===


== 刪除效能服務層級

您可以使用下列方法刪除特定的效能服務層級。如果效能服務層級已指派給工作負載、或是唯一可用的效能服務層級、則您無法刪除該層級。您必須提供效能服務層級的唯一ID作為輸入參數、才能刪除特定的效能服務層級。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
刪除
 a| 
儲存設備供應商/效能服務層級/\｛key｝

|===


== 修改效能服務層級

您可以使用下列方法來修改效能服務層級、並更新其內容。您無法修改系統定義或指派給工作負載的效能服務層級。您必須提供的唯一ID、才能修改特定的效能服務層級。您也必須輸入要更新的IOPS屬性、以及有效值。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
修補程式
 a| 
儲存設備供應商/效能服務層級/\｛key｝

|===


== 根據效能服務層級檢視Aggregate功能

您可以使用下列方法、根據效能服務層級查詢集合體功能。此API會傳回資料中心可用的集合體清單、並指出這些集合體可支援的效能服務層級功能。在磁碟區上配置工作負載時、您可以檢視集合體的功能、以支援特定的效能服務層級、並根據該功能來配置工作負載。您只有在使用API來配置工作負載時、才能指定集合體。Unified Manager Web UI無法使用此功能。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
取得
 a| 
「/儲存設備供應商/ Aggregate功能」

儲存設備供應商/ Aggregate功能/\{key}

|===