---
permalink: api-automation/concept_metrics_apis.html 
sidebar: sidebar 
keywords: view, performance, metrics 
summary: 利用VMware的支援功能、您可以在資料中心類別下、檢視叢集和儲存物件的效能資料。Active IQ Unified Manager這些API會擷取不同儲存物件的效能資料、例如叢集、節點、LUN、磁碟區、 集合體與儲存VM。 
---
= 使用 API 查看效能指標
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用此功能、您可以在「/資料中心」類別下、檢視叢集和資料中心儲存物件的效能資料。Active IQ Unified Manager這些API會擷取不同儲存物件的效能資料、例如叢集、節點、LUN、磁碟區、集合體、 儲存VM、FC介面、FC連接埠、乙太網路連接埠及IP介面。

「/指標」和「/分析」API提供不同的效能指標檢視、您可以利用這些檢視、針對資料中心中的下列儲存物件深入瞭解不同層級的詳細資料：

* 叢集
* 節點
* 儲存VM
* 集合體
* 磁碟區
* LUN
* FC介面
* FC連接埠
* 乙太網路連接埠
* IP介面


下表比較了「/指標」與「/分析」API、以及擷取的效能資料詳細資料。

[cols="2*"]
|===
| 指標 | 分析 


 a| 
單一物件的效能詳細資料。例如、「/資料中心/叢集/叢集/\｛key｝/度量」API要求輸入叢集金鑰作為路徑參數、以擷取該特定叢集的度量。
 a| 
資料中心內多個相同類型物件的效能詳細資料。例如、「/資料中心/叢集/叢集/分析」API會擷取資料中心內所有叢集的集合度量。



 a| 
儲存物件的效能指標範例、以擷取所需的時間間隔參數為基礎。
 a| 
特定儲存物件類型在特定期間（72小時以上）的高層效能集合值。



 a| 
系統會擷取物件的基本詳細資料、例如節點或叢集的詳細資料。
 a| 
未擷取任何特定詳細資料。



 a| 
針對單一物件擷取累計的計數器、例如最小值、最大值、95百分位數、以及一段時間內的平均效能值、例如讀取、寫入、總計和其他計數器。
 a| 
相同類型的所有物件都會顯示單一彙總值。



 a| 
時間範圍和範例資料是根據下列排程：資料的時間範圍。範例可以是1h、12h、1d、2D、3D、 15d、1W、1公尺、2公尺、3公尺、 6萬。如果範圍超過3天（72小時）、您會得到1小時的樣本、否則只有5分鐘的樣本。每個時間範圍的期間如下：

* 1小時：最近一小時的指標取樣時間超過5分鐘。
* 12小時：最近12小時內的指標取樣時間超過5分鐘。
* 一維：最近一天的指標取樣時間超過5分鐘。
* 2D：最近2天的測量數據取樣時間超過5分鐘。
* 3D：最近3天內的指標取樣時間超過5分鐘。
* 15d：最近15天內的指標、取樣時間超過1小時。
* 1W：最近一週的指標取樣時間超過1小時。
* 1M：最近一個月內的數據取樣時間超過1小時。
* 2百萬：最近2個月的指標取樣時間超過1小時。
* 3M：最近3個月的指標、取樣時間超過1小時。
* 6個月：最近6個月的指標取樣時間超過1小時。
+
可用值：1小時、12小時、一維、二維、三維、 15d、1W、1公尺、2公尺、3公尺、 6萬

+
預設值：1小時


 a| 
72小時以上。計算此樣本的持續時間以ISO-8601標準格式表示。

|===


== 度量API的輸出範例

例如、「/資料中心/叢集/節點/\｛key｝/度量」API會擷取節點的下列詳細資料（其中包括）：


NOTE: 摘要值中的95個百分位數表示、在該期間所收集的95%樣本具有的計數值低於指定的95個百分位數。

[listing]
----
{
     "iops": {
       "local": {
         "other": 100.53,
         "read": 100.53,
         "total": 100.53,
         "write": 100.53
       },
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "latency": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "performance_capacity": {
       "available_iops_percent": 0,
       "free_percent": 0,
       "system_workload_percent": 0,
       "used_percent": 0,
       "user_workload_percent": 0
     },
     "throughput": {
       "other": 100.53,
       "read": 100.53,
       "total": 100.53,
       "write": 100.53
     },
     "timestamp": "2018-01-01T12:00:00-04:00",
     "utilization_percent": 0
   }
 ],
 "start_time": "2018-01-01T12:00:00-04:00",
 "summary": {
   "iops": {
     "local_iops": {
       "other": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "read": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "total": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       },
       "write": {
         "95th_percentile": 28,
         "avg": 28,
         "max": 28,
         "min": 5
       }
     },
----


== 分析API的輸出範例

例如、「/資料中心/叢集/節點/分析」API會擷取所有節點的下列值（包括其他值）：

[listing]
----
{     "iops": 1.7471,
     "latency": 60.0933,
     "throughput": 5548.4678,
     "utilization_percent": 4.8569,
     "period": 72,
     "performance_capacity": {
       "used_percent": 5.475,
       "available_iops_percent": 168350
     },
     "node": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "uuid": "95f94e8d-8b4e-11e9-8974-00a098e0219a",
       "name": "ocum-infinity-01",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/nodes/37387241-8b57-11e9-8974-00a098e0219a:type=cluster_node,uuid=95f94e8d-8b4e-11e9-8974-00a098e0219a"
         }
       }
     },
     "cluster": {
       "key": "37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a",
       "uuid": "37387241-8b57-11e9-8974-00a098e0219a",
       "name": "ocum-infinity",
       "_links": {
         "self": {
           "href": "/api/datacenter/cluster/clusters/37387241-8b57-11e9-8974-00a098e0219a:type=cluster,uuid=37387241-8b57-11e9-8974-00a098e0219a"
         },
     "_links": {
       "self": {
         "href": "/api/datacenter/cluster/nodes/analytics"
       }
     }
   },
----


== 可用API清單

下表詳細說明了「/指標」和「/分析」API。

[NOTE]
====
這些API傳回的IOPS和效能指標是兩倍值、例如「10053」。不支援使用管路（|）和萬用字元（*）來篩選這些浮點值。

====
[cols="3*"]
|===
| HTTP Verb | 路徑 | 說明 


 a| 
《 Get 》（取得）
 a| 
「/資料中心/叢集/叢集/\｛key｝/指標」
 a| 
擷取叢集金鑰輸入參數所指定叢集的效能資料（範例和摘要）。傳回叢集金鑰和UUID、時間範圍、IOPS、處理量及取樣數目等資訊。



 a| 
《 Get 》（取得）
 a| 
資料中心/叢集/叢集/分析
 a| 
擷取資料中心內所有叢集的高層級效能指標。您可以根據所需的條件篩選結果。會傳回彙總IOPS、處理量及收集期間（以小時為單位）等值。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/叢集/節點/\｛key｝/指標」
 a| 
擷取節點金鑰輸入參數所指定節點的效能資料（範例和摘要）。傳回的資訊包括節點UUID、時間範圍、IOPS摘要、處理量、延遲和效能、所收集的樣本數、以及使用百分比。



 a| 
《 Get 》（取得）
 a| 
資料中心/叢集/節點/分析
 a| 
擷取資料中心中所有節點的高層效能度量。您可以根據所需的條件篩選結果。會傳回節點和叢集金鑰等資訊、以及彙總IOPS、處理量和收集期間（以小時為單位）等值。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/儲存/集合體/\｛key｝/指標」
 a| 
擷取Aggregate金鑰輸入參數所指定之Aggregate的效能資料（範例和摘要）。傳回的資訊包括時間範圍、IOPS摘要、延遲、處理量和效能容量、每個計數器所收集的樣本數、以及使用的百分比。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存/集合體/分析
 a| 
擷取資料中心中所有集合體的高層效能指標。您可以根據所需的條件篩選結果。會傳回諸如Aggregate和叢集金鑰等資訊、以及彙總IOPS、處理量和收集期間（以小時為單位）等值。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/儲存設備/LUNs/\｛key｝/指標」

「/資料中心/儲存設備/磁碟區/\｛key｝/指標」
 a| 
擷取LUN或LUN或Volume金鑰輸入參數所指定之檔案共用區（Volume）的效能資料（範例和摘要）。資訊、例如讀取、寫入和IOPS總計、延遲和處理量的最小、最大和平均摘要、 並傳回每個計數器所收集的樣本數。



 a| 
《 Get 》（取得）
 a| 
資料中心/儲存設備/LUN/分析功能

資料中心/儲存/磁碟區/分析
 a| 
擷取資料中心內所有LUN或磁碟區的高層效能度量。您可以根據所需的條件篩選結果。系統會傳回儲存VM和叢集金鑰等資訊、以及彙總IOPS、處理量和收集期間（以小時為單位）等值。



 a| 
《 Get 》（取得）
 a| 
資料中心/ SVM/svms/{key}/dataces'
 a| 
擷取儲存VM金鑰輸入參數所指定之儲存VM的效能資料（範例和摘要）。根據每個支援的傳輸協定（例如「nvmf、FCP、iSCSI」和「NFS」）、處理量、 延遲、以及所收集的樣本數量會傳回。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/ SVM/svms/Analytics」
 a| 
擷取資料中心內所有儲存VM的高階效能指標。您可以根據所需的條件篩選結果。系統會傳回儲存VM UUID、彙總IOPS、延遲、處理量及收集期間（以小時為單位）等資訊。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/網路/乙太網路/連接埠/｛key｝/指標」
 a| 
擷取連接埠金鑰輸入參數所指定之特定乙太網路連接埠的效能度量。當從支援範圍提供時間間隔（時間範圍）時、API會傳回累計的計數器、例如期間內的最小、最大和平均效能值。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/乙太網路/連接埠/分析
 a| 
擷取資料中心環境中所有乙太網路連接埠的高效能度量。傳回叢集和節點金鑰及UUID、處理量、收集期間及連接埠使用率百分比等資訊。您可以根據可用的參數（例如連接埠金鑰、使用率百分比、叢集和節點名稱及UUID等）來篩選結果。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/網路/光纖通道/介面/｛key｝/指標」
 a| 
擷取介面金鑰輸入參數所指定之特定網路FC介面的效能度量。當從支援範圍提供時間間隔（時間範圍）時、API會傳回累計的計數器、例如期間內的最小、最大和平均效能值。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/光纖通道/介面/分析
 a| 
擷取資料中心環境中所有乙太網路連接埠的高效能度量。傳回叢集和FC介面金鑰及UUID、處理量、IOPS、延遲和儲存VM等資訊。您可以根據可用的參數來篩選結果、例如叢集和FC介面名稱與UUID、儲存VM、處理量等。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/網路/光纖通道/連接埠/｛key｝/指標」
 a| 
擷取連接埠金鑰輸入參數所指定之特定FC連接埠的效能度量。當從支援範圍提供時間間隔（時間範圍）時、API會傳回累計的計數器、例如期間內的最小、最大和平均效能值。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/光纖通道/連接埠/分析功能
 a| 
擷取資料中心環境中所有FC連接埠的高層效能指標。傳回叢集和節點金鑰及UUID、處理量、收集期間及連接埠使用率百分比等資訊。您可以根據可用的參數（例如連接埠金鑰、使用率百分比、叢集和節點名稱及UUID等）來篩選結果。



 a| 
《 Get 》（取得）
 a| 
「/資料中心/網路/IP/介面/｛key｝/指標」
 a| 
擷取介面金鑰輸入參數所指定之網路IP介面的效能度量。當從支援範圍提供時間間隔（時間範圍）時、API會傳回資訊、例如取樣數量、累計計數器、處理量、以及接收和傳輸的封包數。



 a| 
《 Get 》（取得）
 a| 
資料中心/網路/IP/介面/分析
 a| 
擷取資料中心環境中所有網路IP介面的高層效能度量。傳回叢集與IP介面金鑰及UUID、處理量、IOPS及延遲等資訊。您可以根據可用的參數來篩選結果、例如叢集和IP介面名稱及UUID、IOPS、延遲、處理量等。

|===