---
permalink: api-automation/concept_manage_sep.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policy 
summary: 您可以使用儲存供應商API來檢視、建立、修改及刪除儲存效率原則。 
---
= 使用 API 管理儲存效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用儲存供應商API來檢視、建立、修改及刪除儲存效率原則。

[NOTE]
====
請注意以下幾點：

* 在Unified Manager上建立工作負載時、不一定要指派儲存效率原則。
* 指派原則後、您無法從工作負載中取消指派儲存效率原則。
* 如果某個工作負載在ONTAP 支援重複資料刪除和壓縮等功能的支援磁碟區上有指定的儲存設定、則當您在Unified Manager上新增儲存工作負載時、所套用的儲存效率原則中所指定的設定、就會覆寫這些設定。


====


== 檢視儲存效率原則

您可以使用下列方法來檢視儲存效率原則、然後再將其指派給儲存工作負載。此API會列出系統定義和使用者建立的所有儲存效率原則、並擷取所有儲存效率原則的屬性。若要查詢特定的儲存效率原則、您必須輸入原則的唯一ID、才能擷取其詳細資料。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
取得
 a| 
「/儲存供應商/儲存效率原則」

儲存設備供應商/儲存效率原則/\{key}

|===


== 新增儲存效率原則

您可以使用下列方法來建立自訂儲存效率原則、並在系統定義的原則不符合儲存工作負載的資源配置需求時、將其指派給儲存工作負載。輸入您要建立的儲存效率原則詳細資料、做為輸入參數。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
貼文
 a| 
「/儲存供應商/儲存效率原則」

|===


== 刪除儲存效率原則

您可以使用下列方法刪除特定的儲存效率原則。如果儲存效率原則已指派給工作負載、或是唯一可用的儲存效率原則、則您無法刪除該原則。您需要提供儲存效率原則的唯一ID作為輸入參數、以刪除特定的儲存效率原則。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
刪除
 a| 
儲存設備供應商/儲存效率原則/\{key}

|===


== 修改儲存效率原則

您可以使用下列方法來修改儲存效率原則、並更新其內容。您無法修改系統定義或指派給工作負載的儲存效率原則。您必須提供儲存效率原則的唯一ID、才能修改特定的儲存效率原則。此外、您還需要提供您要更新的內容及其值。

[cols="3*"]
|===
| 類別 | HTTP動詞 | 路徑 


 a| 
儲存供應商
 a| 
修補程式
 a| 
儲存設備供應商/儲存效率原則/\{key}

|===