---
permalink: api-automation/concept_events_api.html 
sidebar: sidebar 
keywords: view, events, system, details 
summary: 事件API可讓您擷取資料中心內受監控叢集所產生的事件。 
---
= 使用 API 管理事件和警報
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「管理伺服器」類別下的「事件」、「警示」和「指令碼」API、可讓您管理Active IQ Unified Manager 與您的不穩定環境中警示相關的事件、警示和指令碼。



== 查看和修改事件

Unified Manager會接收ONTAP 在以功能為基礎上產生的事件、以供Unified Manager監控及管理的叢集使用。使用這些API、您可以檢視為叢集產生的事件、並加以解析和更新。

藉由執行「管理伺服器/事件」API的「Get」方法、您可以查詢資料中心內的事件、包括歷史資料。使用內建的篩選器、例如名稱、影響層級、影響區域、嚴重性、 狀態、資源名稱和資源類型、以檢視特定事件。資源類型和區域參數會傳回事件發生所在儲存物件的相關資訊、而影響區域會傳回事件發生問題的相關資訊、例如可用度、容量、組態、安全性、 保護與效能。

執行此API的修補程式作業、即可啟用事件的解決工作流程。您可以將事件指派給自己或其他使用者、並確認收到事件。在執行資源上的步驟以解決觸發事件的問題時、您可以使用此API將事件標記為已解決。

如需事件的詳細資訊，請參閱link:../events/concept_manage_events.html["管理活動"]。

[cols="4*"]
|===
| 類別 | HTTP動詞 | 路徑 | 說明 


 a| 
管理伺服器
 a| 
取得
 a| 
管理伺服器/事件「/management server / events /｛key｝」
 a| 
當您執行Get All方法時、回應本文會包含資料中心內所有事件的事件詳細資料。當您依特定金鑰擷取事件詳細資料時、可以檢視特定事件的詳細資料、並在資源上執行下一組作業。回應本文包含該事件的詳細資料。



 a| 
管理伺服器
 a| 
修補程式
 a| 
「管理伺服器/事件/｛key｝」
 a| 
執行此API以指派事件、或將狀態變更為「已確認」或「已解決」。您也可以使用此方法將事件指派給自己或其他使用者。這是同步作業。

|===


== 管理警示

系統會自動持續產生事件。Unified Manager只會在事件符合特定篩選條件時產生警示。您可以選取要產生警示的事件。透過使用「/management server / alerts」API、您可以設定警示、在發生特定嚴重性類型的特定事件或事件時自動傳送通知。

如需警示的詳細資訊，請參閱link:../events/concept_manage_alerts.html["管理警示"]。

[cols="4*"]
|===
| 類別 | HTTP動詞 | 路徑 | 說明 


 a| 
管理伺服器
 a| 
取得
 a| 
「/kmanagement server / alerts」（管理伺服器/警示）、「/management server / alerts/{key}」（管理伺服器/警示）
 a| 
使用警示金鑰查詢環境中的所有現有警示或特定警示。您可以檢視環境中所產生警示的相關資訊、例如警示說明、動作、傳送通知的電子郵件ID、事件和嚴重性。



 a| 
管理伺服器
 a| 
貼文
 a| 
「/管理伺服器/警示」
 a| 
此方法可讓您針對特定事件新增警示。您必須新增警示名稱、實體或邏輯資源、或警示適用的事件、警示是否已啟用、以及是否要發出SNMP設陷。您可以新增要產生警示的其他詳細資料、例如行動、通知電子郵件ID、指令碼詳細資料、以便在新增警示指令碼時使用等等。



 a| 
管理伺服器
 a| 
修補與刪除
 a| 
「管理伺服器/事件/｛key｝」
 a| 
您可以使用這些方法來修改和刪除特定警示。您可以修改不同的屬性、例如說明、名稱、以及啟用和停用警示。您可以在不再需要警示時刪除警示。

|===

NOTE: 選取資源以新增警示時、請注意選取叢集做為資源並不會自動選取該叢集內的儲存物件。例如、如果您為所有叢集的所有重大事件建立警示、您將只會收到叢集重大事件的警示。您不會收到節點、集合體等關鍵事件的警示。



== 管理腳本

透過使用「/management server /scripts」API、您也可以將警示與觸發警示時執行的指令碼建立關聯。您可以使用指令碼、在Unified Manager中自動修改或更新多個儲存物件。指令碼與警示相關聯。當事件觸發警示時、即會執行指令碼。您可以上傳自訂指令碼、並在產生警示時測試其執行。您可以將警示與指令碼建立關聯、以便在Unified Manager中針對事件發出警示時執行指令碼。

如需指令碼的詳細資訊，請參閱link:../events/concept_manage_scripts.html["管理腳本"]。

[cols="4*"]
|===
| 類別 | HTTP動詞 | 路徑 | 說明 


 a| 
管理伺服器
 a| 
取得
 a| 
「管理伺服器/指令碼」
 a| 
使用此API查詢環境中所有現有的指令碼。使用標準篩選器和依作業排序、只檢視特定指令碼。



 a| 
管理伺服器
 a| 
貼文
 a| 
「管理伺服器/指令碼」
 a| 
使用此API新增指令碼的說明、並上傳與警示相關的指令碼檔案。

|===