---
permalink: reporting/concept_unified_manager_databases_accessible_for_reporting.html 
sidebar: sidebar 
keywords: unified manager, databases, access, custom, reporting 
summary: Unified Manager使用MySQL資料庫來儲存其監控叢集的資料。資料會保留在MySQL資料庫的各種架構中。 
---
= Unified Manager資料庫可供自訂報告使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager使用MySQL資料庫來儲存其監控叢集的資料。資料會保留在MySQL資料庫的各種架構中。

下列資料庫中的所有表格資料均可供使用：

[cols="2*"]
|===
| 資料庫 | 說明 


 a| 
NetApp_model
 a| 
關於物件的資料ONTAP 。



 a| 
NetApp_mode_view
 a| 
關於物件的資料ONTAP 、適用於報告工具使用。



 a| 
NetApp_Performance
 a| 
叢集特定效能計數器。



 a| 
奧克姆
 a| 
Unified Manager應用程式資料與資訊、可支援UI篩選、排序及計算某些衍生欄位。



 a| 
ocum_report
 a| 
用於庫存組態和容量相關資訊的資料。



 a| 
ocum_report_BIRT
 a| 
適用於報告工具使用的庫存組態和容量相關資料檢視。



 a| 
OPM
 a| 
效能組態設定與臨界值資訊。



 a| 
scalemonitor
 a| 
Unified Manager應用程式健全狀況與效能問題的相關資料。



 a| 
VMware_model
 a| 
NetApp儲存設備上所裝載之資料存放區的VMware物件資料。



 a| 
VMware_mode_view
 a| 
適用於NetApp儲存設備上所託管之資料存放區的VMware物件資料檢視、適用於報告工具使用量。



 a| 
VMware_Performance
 a| 
VMware效能計數器資料存放區的資料存放區資料存放在NetApp儲存設備上。

|===
報告使用者（具有報告架構角色的資料庫使用者）能夠存取這些表格中的資料。此使用者可直接從Unified Manager資料庫、以唯讀方式存取報告和其他資料庫檢視。請注意、此使用者無權存取任何包含使用者資料或叢集認證資訊的資料表。
