---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: 延遲預測是指預測特定時間的效能值上限和下限。針對工作負載延遲、較高的值會形成效能臨界值。當實際值超過效能臨界值時、Unified Manager會觸發動態效能事件。 
---
= 預期的效能範圍為何
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
延遲預測是指預測特定時間的效能值上限和下限。針對工作負載延遲、較高的值會形成效能臨界值。當實際值超過效能臨界值時、Unified Manager會觸發動態效能事件。

例如、在正常營業時間上午9：00之間下午5：00、大部分員工可能會在上午9：00之間查看電子郵件上午10：30電子郵件伺服器的需求增加、表示在此期間後端儲存設備的工作負載活動增加。員工可能會注意到電子郵件用戶端的回應時間過慢。

午餐時間為下午12：00以及下午1：00而且在工作日結束後下午5：00、大部分員工可能會離開電腦。對電子郵件伺服器的需求通常會減少、也會減少對後端儲存設備的需求。或者、也可以排程工作負載作業、例如儲存備份或掃毒、這些作業會在下午5：00之後開始並增加後端儲存設備的活動。

在數天內、工作負載活動的增加和減少會決定活動的預期範圍（延遲預測）、以及工作負載的上限和下限。當物件的實際工作負載活動超出上限或下限、且在一段時間內仍在邊界之外時、這可能表示物件過度使用或未充分使用。



== 延遲預測的形成方式

Unified Manager必須收集至少3天的工作負載活動、才能開始進行分析、並在GUI中顯示I/O回應時間的延遲預測。所需的最低資料收集量並不包含工作負載活動所發生的所有變更。在收集活動的前3天之後、Unified Manager會在每24小時的上午12：00調整延遲預測以反映工作負載活動變化、並建立更精確的動態效能臨界值。

[NOTE]
====
夏令時間（Dst）會變更系統時間、進而改變監控工作負載效能統計資料的延遲預測。Unified Manager會立即開始修正延遲預測、這大約需要15天才能完成。在此期間、您可以繼續使用Unified Manager、但由於Unified Manager使用延遲預測來偵測動態事件、因此部分事件可能不準確。在時間變更之前偵測到的事件不受影響。

====