---
permalink: performance-checker/reference_what_data_does_workload_analyzer_display.html 
sidebar: sidebar 
keywords: workload analyzer, charts, display, data 
summary: 「工作負載分析器」頁面會顯示任何可能影響工作負載的目前事件資訊、可能修正事件所造成問題的建議、以及分析效能和容量歷程記錄的圖表。 
---
= 工作負載分析器會顯示哪些資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「工作負載分析器」頁面會顯示任何可能影響工作負載的目前事件資訊、可能修正事件所造成問題的建議、以及分析效能和容量歷程記錄的圖表。

在頁面頂端、您可以指定要分析的工作負載名稱（Volume或LUN）、以及要查看統計資料的時間範圍。如果您想要檢視較短或較長的時間、可以隨時變更時間範圍。

頁面的其他區域會顯示分析結果、以及效能與容量圖表。

[NOTE]
====
LUN的工作負載圖表所提供的統計資料層級與磁碟區的圖表不同、因此您在分析這兩種工作負載時會注意到差異。

====
* *活動摘要區域*
+
顯示時間範圍內所發生事件的數量和類型的簡短總覽。當發生來自不同影響領域的事件（例如效能和容量）時、會顯示此資訊、以便您針對感興趣的事件類型選取詳細資料。按一下事件類型以檢視事件名稱清單。

+
如果時間範圍內只有一個事件、則會針對某些事件列出修正問題的建議清單。

* *事件時間表*
+
顯示指定時間範圍內的所有事件。將游標停留在每個事件上、即可檢視事件名稱。

+
如果您按一下「事件詳細資料」頁面上的「*分析工作負載*」按鈕來到本頁、則所選事件的圖示會變大、以便識別事件。

* *效能圖表區域*
+
根據您選取的時間範圍、顯示延遲、處理量（IOPS和MB/s）及使用率（節點和Aggregate）的圖表。您可以按一下「檢視效能詳細資料」連結、顯示工作負載的「效能總管」頁面、以便在您想要執行進一步分析時使用。

+
** *延遲*顯示選定時間範圍內工作負載的延遲。圖表有三種檢視可供您查看：
+
*** *總延遲*
*** *明細*延遲（依讀取、寫入及其他程序劃分）
*** *叢集元件*延遲（依叢集元件劃分）






請參閱 link:concept_cluster_components_and_why_they_can_be_in_contention.html["叢集元件及其爭用的原因"] 以取得此處顯示之叢集元件的說明。*處理量*顯示選定時間範圍內工作負載的IOPS和MB/s處理量。此圖表有四種檢視可供您查看：*總計*處理量**明細*處理量（依讀取、寫入及其他處理程序劃分）**雲端處理量*（用於寫入及讀取雲端資料的MB/s； 對於分層容量至雲端的工作負載）*含Forecast *的IOPS（預測期間內預期IOPS處理量值的上限和下限）。此圖表也會顯示服務品質（QoS）最大和最小處理量臨界值設定（若已設定）、 因此您可以瞭解系統可能會刻意限制QoS原則的處理量。*使用率*顯示工作負載在所選時間範圍內執行之集合體和節點的使用率。您可以從這裡查看您的Aggregate或節點是否過度使用、可能造成高延遲。分析FlexGroup 完這個問題時、使用率圖表上會列出多個節點和多個集合體。

* *容量表區域*
+
顯示過去一個月工作負載的資料容量和Snapshot容量圖表。

+
若為Volume、您可以按一下「View cap」（檢視容量）詳細資料連結、以顯示工作負載的「Health Details」（健全狀況詳細資料）頁面、以便在您想要執行進一步分析時使用。LUN不提供此連結、因為沒有LUN的「健全狀況詳細資料」頁面。

+
** *容量檢視*顯示工作負載分配的總可用空間和邏輯已用空間（在所有NetApp最佳化之後）。
** * Snapshot View*會顯示保留給Snapshot複本的總空間、以及目前使用的空間量。請注意、LUN不提供Snapshot View。
** * Cloud Tier View*會顯示本機效能層使用的容量、以及雲端層使用的容量。這些圖表包括此工作負載在容量滿之前的預估剩餘時間。此資訊係根據歷史使用量而定、至少需要10天的資料。如果剩餘容量少於30天、Unified Manager會將儲存設備識別為「幾乎已滿」。



