---
permalink: performance-checker/reference_types_of_system_defined_performance_threshold_policies.html 
sidebar: sidebar 
keywords: system-defined, performance, threshold, policies, cluster, node. aggregate, qos 
summary: Unified Manager提供一些標準臨界值原則、可監控叢集效能並自動產生事件。這些原則預設為啟用、當受監控的效能臨界值遭到違反時、它們會產生警告或資訊事件。 
---
= 系統定義的效能臨界值原則類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unified Manager提供一些標準臨界值原則、可監控叢集效能並自動產生事件。這些原則預設為啟用、當受監控的效能臨界值遭到違反時、它們會產生警告或資訊事件。

[NOTE]
====
系統定義的效能臨界值原則無法在Cloud Volumes ONTAP VMware、ONTAP VMware或ONTAP Select VMware系統上啟用。

====
如果從任何系統定義的效能臨界值原則接收到不必要的事件、您可以從「事件設定」頁面停用個別原則的事件。



== 叢集臨界值原則

系統定義的叢集效能臨界值原則預設會指派給Unified Manager監控的每個叢集：

* *叢集負載不平衡*
+
識別某個節點的工作負載比叢集中其他節點高得多、因此可能影響工作負載延遲的情況。

+
它會比較叢集中所有節點的效能使用容量值、以查看任何節點之間的負載差異是否為30%。這是一項警告事件。

* *叢集容量不平衡*
+
識別某個Aggregate的使用容量遠高於叢集中其他Aggregate的情況、因此可能會影響作業所需的空間。

+
它會比較叢集中所有集合體的已用容量值、以查看任何集合體之間是否有70%的差異。這是一項警告事件。





== 節點臨界值原則

系統定義的節點效能臨界值原則預設會指派給Unified Manager所監控之叢集中的每個節點：

* *效能容量已超過臨界值*
+
識別單一節點在作業效率範圍之外運作的情況、進而可能影響工作負載延遲。

+
這是為了尋找使用超過100%效能容量達12小時以上的節點。這是一項警告事件。

* *節點HA配對過度使用*
+
識別HA配對中的節點在HA配對作業效率範圍之外運作的情況。

+
它是透過查看HA配對中兩個節點的效能使用容量值來達成此目的。如果兩個節點的合併效能容量超過200%達12小時以上、則控制器容錯移轉將會影響工作負載延遲。這是資訊事件。

* *節點磁碟分割*
+
識別集合體中的磁碟或磁碟已被分割、使關鍵系統服務變慢、並可能影響節點上的工作負載延遲的情況。

+
它是透過查看節點上所有集合體的特定讀取和寫入作業比率來達成此目的。此原則也可能會在SyncMirror 進行不同步時觸發、或在磁碟清理作業期間發現錯誤時觸發。這是一項警告事件。

+
[NOTE]
====
「節點磁碟重組」原則分析純HDD的集合體、不FabricPool 分析Flash Pool、SSD和整合。

====




== Aggregate臨界值原則

系統定義的Aggregate效能臨界值原則預設會指派給Unified Manager所監控之叢集中的每個Aggregate：

* * Aggregate磁碟過度使用*
+
找出集合體在作業效率限制之外運作、因而可能影響工作負載延遲的情況。它會找出集合體、其中集合體中的磁碟使用率超過95%、使用時間超過30分鐘、藉此識別這些情況。接著、此多重條件原則會執行下列分析、以協助判斷問題的原因：

+
** 集合體中的磁碟目前是否正在進行背景維護活動？
+
磁碟可能正在進行的一些背景維護活動包括磁碟重建、磁碟清理、SyncMirror 重新同步及重新修復。

** 磁碟櫃光纖通道互連是否存在通訊瓶頸？
** 集合體中的可用空間是否太小？只有在三個從屬原則中有一個（或多個）也被視為違反時、才會針對此原則發出警告事件。如果僅集合體中的磁碟使用率超過95%、則不會觸發效能事件。




[NOTE]
====
「Aggregate disks over使用率」原則會分析純HDD的集合體和Flash Pool（混合式）集合體、而不會FabricPool 分析SSD和邊狀集合體。

====


== 工作負載延遲臨界值原則

系統定義的工作負載延遲臨界值原則會指派給任何已設定「效能服務層級」原則且具有定義「預期延遲」值的工作負載：

* *工作負載Volume / LUN延遲臨界值超出效能服務層級*所定義的值
+
識別已超過其「預期延遲」限制、且影響工作負載效能的磁碟區（檔案共用）和LUN。這是一項警告事件。

+
這是為了尋找超過前一小時30%時間預期延遲值的工作負載。





== QoS臨界值原則

系統定義的QoS效能臨界值原則會指派給任何已設定ONTAP 「QoS最高處理量」原則（IOPS、IOPS/TB或MB/s）的工作負載。當工作負載處理量值低於設定的QoS值15%時、Unified Manager會觸發事件：

* * QoS最大IOPS或MB/s臨界值*
+
識別已超過QoS最大IOPS或MB/s處理量限制、且影響工作負載延遲的磁碟區和LUN。這是一項警告事件。

+
將單一工作負載指派給原則群組時、會在前一小時的每個收集期間、尋找超出指派QoS原則群組中定義之最大處理量臨界值的工作負載來達成此目標。

+
當多個工作負載共用單一QoS原則時、只要在原則中新增所有工作負載的IOPS或MB/s、並根據臨界值檢查該總負載、即可達成此目標。

* * QoS尖峰IOPS / TB或IOPS / TB、具有區塊大小臨界值*
+
識別已超過調適性QoS尖峰IOPS / TB處理量限制（或IOPS / TB、區塊大小限制）、且影響工作負載延遲的磁碟區。這是一項警告事件。

+
它會根據每個磁碟區的大小、將調適性QoS原則中定義的尖峰IOPS/TB臨界值轉換成QoS最大IOPS值、然後尋找在前一小時每個效能收集期間超過QoS最大IOPS的磁碟區。

+
[NOTE]
====
此原則僅在叢集安裝ONTAP 有更新版本的軟體時、才會套用至Volume。

====
+
在調適性QoS原則中定義「區塊大小」元素時、臨界值會根據每個磁碟區的大小、轉換成QoS最大MB/s值。然後、它會在前一小時的每個效能收集期間、尋找超過QoS最大MB/s的磁碟區。

+
[NOTE]
====
此原則僅適用於使用ONTAP 更新版本的軟體安裝叢集的磁碟區。

====

