---
permalink: performance-checker/task_respond_to_cluster_imbalance_performance_events.html 
sidebar: sidebar 
keywords: cluster, imbalance, performance, events 
summary: 當叢集中的某個節點的工作負載遠高於其他節點時、Unified Manager會產生叢集不平衡警告事件、進而可能影響工作負載延遲。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。 
---
= 回應叢集不平衡的效能事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當叢集中的某個節點的工作負載遠高於其他節點時、Unified Manager會產生叢集不平衡警告事件、進而可能影響工作負載延遲。這些系統定義的事件可在許多工作負載受到延遲影響之前、提供修正潛在效能問題的機會。

.開始之前
您必須具有「操作員」、「應用程式管理員」或「儲存管理員」角色。

Unified Manager會比較叢集中所有節點的效能使用容量值、以查看任何節點之間的負載差異是否為30%、藉此針對叢集不平衡臨界值原則違規事件產生警告事件。

這些步驟可協助您識別下列資源、以便將高效能工作負載移至使用率較低的節點：

* 相同叢集上的節點使用率較低
* 新節點上使用率最低的集合體
* 目前節點上執行效能最高的磁碟區


.步驟
. 顯示「*事件*」詳細資料頁面、以檢視有關事件的資訊。
. 檢閱* Description*、其中說明導致事件的臨界值外洩。
+
例如、「效能使用容量計數器」訊息表示叢集達拉斯1-8上的節點之間的負載差異為62%、並根據系統臨界值30%觸發警告事件。」訊息表示其中一個節點的效能容量過度使用、並會影響節點效能。

. 檢閱*建議動作*中的文字、將高效能磁碟區從具有高效能使用容量值的節點移至效能使用容量值最低的節點。
. 識別具有最高和最低效能容量使用值的節點：
+
.. 在「*事件資訊*」區段中、按一下來源叢集的名稱。
.. 在「*叢集/效能摘要*」頁面中、按一下「*管理物件*」區域中的「*節點*」。
.. 在「*節點*」目錄頁中、依「*效能使用容量*」欄位排序節點。
.. 識別具有最高和最低效能容量使用值的節點、並記下這些名稱。


. 在具有最高效能容量使用值的節點上、使用最多IOPS來識別磁碟區：
+
.. 按一下具有最高效能使用容量值的節點。
.. 在「*節點/效能檔案總管*」頁面中、從*「檢視與比較*」功能表中選取*「此節點*上的集合體」。
.. 按一下具有最高效能使用容量值的Aggregate。
.. 在「* Aggregate / Performance Explorer/*」（*集合體/效能檔案總管*）頁面中、從*「View and Compare*」（檢視與比較*）功能表選取*「Volume on this Aggreg
.. 依* IOPS *欄位排序磁碟區、並使用最大IOPS記下磁碟區名稱、以及磁碟區所在的集合體名稱。


. 在具有最低效能容量使用值的節點上、以最低使用率識別集合體：
+
.. 按一下「*儲存設備*>* Aggregate *」以顯示「* Aggregate *」目錄頁。
.. 選取*效能：All Aggregate *檢視。
.. 按一下「篩選器*」按鈕、然後新增篩選器、其中「節點」等於您在步驟4中寫下效能容量使用值最低的節點名稱。
.. 記下效能容量使用值最低的集合體名稱。


. 將磁碟區從過載節點移至您在新節點上識別為使用率偏低的集合體。
+
您可以使用ONTAP 下列OnCommand Workflow Automation 工具來執行「移動」作業：《系統管理程式》、《VMware指令集》、ONTAP 《VMware指令集》或《VMware指令集》。



幾天後、請檢查您是否從這個叢集收到相同的叢集不平衡事件。
