---
permalink: storage-mgmt/concept_all_workloads.html 
sidebar: sidebar 
keywords: view, workloads, add, provision, storage, filter, analyze, performance, capacity, criteria 
summary: All工作負載檢視會顯示資料中心叢集上所有可用工作負載的清單。 
---
= 檢視工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
All工作負載檢視會顯示資料中心叢集上所有可用工作負載的清單。

All工作負載檢視會列出與ONTAP Unified Manager所管理的各個叢集相關的儲存工作負載。此頁面也可讓您指派儲存效率原則（DDP）和效能服務層級（PSL）給儲存工作負載。

當您將叢集新增至Unified Manager時、系統會自動探索並顯示每個叢集上的儲存工作負載、FlexGroup 但不包括下列項目：

Unified Manager只會在儲存工作負載上開始執行I/O作業之後、才開始分析工作負載的建議（建議的PSL）。對於未執行I/O作業的新發現儲存工作負載、狀態為「waiting for I/O（正在等待I/O）」。在儲存工作負載上開始執行I/O作業之後、Unified Manager會開始分析、工作負載狀態會變更為「Learning ...」。分析完成後（從I/O作業開始算起24小時內）、儲存工作負載會顯示建議的PSL。

使用*工作負載*>*所有工作負載*選項、您可以執行多項工作：

* 新增或配置儲存工作負載
* 檢視及篩選工作負載清單
* 將PSL指派給儲存工作負載
* 評估系統建議的PSL、並將其指派給工作負載
* 將DDP指派給儲存工作負載




== 新增或配置儲存工作負載

您可以新增或配置儲存工作負載至支援的LUN（同時支援iSCSI和FCP傳輸協定）、NFS檔案共用和SMB共用。



== 檢視及篩選工作負載

在「All工作負載」畫面上、您可以檢視資料中心中的所有工作負載、或根據其PSL或名稱搜尋特定的儲存工作負載。您可以使用篩選圖示輸入搜尋的特定條件。您可以依不同的篩選條件（例如主機叢集或儲存VM）進行搜尋。*容量總計*選項可依工作負載的總容量（以MB為單位）進行篩選。不過、在此案例中、傳回的工作負載數量可能會有所不同、因為總容量是以位元組層級進行比較。

針對每個工作負載、會顯示主機叢集和儲存VM等資訊、以及指派的PSL和SEP。

此頁面也可讓您檢視工作負載的效能詳細資料。您可以按一下「*選擇/訂單欄*」按鈕、然後選取要檢視的特定欄、以檢視工作負載的IOPS、容量和延遲等詳細資訊。「效能檢視」欄會顯示工作負載的平均和尖峰IOPS、您可以按一下工作負載分析器圖示來檢視詳細的IOPS分析。「IOPS分析」快顯視窗上的「分析工作負載*」按鈕會帶您前往「工作負載分析」頁面、您可在其中選取時間範圍、並檢視所選工作負載的延遲、處理量和容量趨勢。如需工作負載分析器的詳細資訊、請參閱_使用工作負載分析器疑難排解工作負載_



== 分析工作負載的效能與容量條件

您可以按一下「*效能檢視*」欄中的橫條圖圖示、檢視工作負載的效能資訊、以協助疑難排解。若要在「工作負載分析」頁面上檢視效能與容量圖表以分析物件、請按一下「*分析工作負載*」按鈕。
