---
permalink: storage-mgmt/concept_manage_storage_efficiency_policies.html 
sidebar: sidebar 
keywords: manage, storage, efficiency, policies, guidelines, create, custom 
summary: 儲存效率原則（SEP）可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時、或之後編輯工作負載、將SEP指派給工作負載。 
---
= 管理儲存效率策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存效率原則（SEP）可讓您定義工作負載的儲存效率特性。您可以在最初建立工作負載時、或之後編輯工作負載、將SEP指派給工作負載。

儲存效率包括使用精簡配置、重複資料刪除及資料壓縮等技術、以提高儲存使用率並降低儲存成本。在建立DDP時、您可以個別或一起使用這些節省空間的技術、以達到最大儲存效率。當您將原則與儲存工作負載建立關聯時、系統會將指定的原則設定指派給這些原則。Unified Manager可讓您指派系統定義和使用者定義的DDP、以最佳化資料中心的儲存資源。

Unified Manager提供兩種系統定義的DDP：高和低。這些DDP適用於資料中心的大部分儲存工作負載、不過、如果系統定義的DDP不符合您的需求、您可以自行建立原則。

您無法修改系統定義或目前指派給工作負載的SEP。您無法刪除指派給工作負載的SEP、或是唯一可用的SEP。

「儲存效率原則」頁面會列出可用的DDP、並可讓您新增、編輯及刪除自訂的DDP。此頁面顯示下列資訊：

|===
| 欄位 | 說明 


 a| 
名稱
 a| 
SEP的名稱。



 a| 
類型
 a| 
原則是由系統定義還是由使用者定義。



 a| 
空間保留
 a| 
磁碟區是精簡配置或完整配置。



 a| 
重複資料刪除
 a| 
是否在工作負載上啟用重複資料刪除：

* 即時：在工作負載上寫入重複資料刪除時、會發生重複資料刪除
* 背景：重複資料刪除會在工作負載中執行
* 停用：工作負載上的重複資料刪除功能已停用




 a| 
壓縮
 a| 
是否在工作負載上啟用資料壓縮：

* 即時：在工作負載上寫入資料時、會進行資料壓縮
* 背景：資料壓縮會發生在工作負載中
* 停用：工作負載上的資料壓縮已停用




 a| 
工作負載
 a| 
指派給SEP的儲存工作負載數量

|===


== 建立自訂儲存效率原則的準則

如果現有的DDP不符合儲存工作負載的原則需求、您可以建立自訂的SEP。不過、建議您嘗試針對儲存工作負載使用系統定義的DDP、並視需要僅建立自訂的DDP。

您可以在「所有工作負載」頁面和「Volume / Health」（磁碟區/健全狀況）詳細資料頁面中、檢視指派給工作負載的SEP。您可以在儀表板的「容量」面板和「容量：所有叢集」檢視中、根據這些儲存效率、檢視叢集層級的資料減量比率（不含 Snapshot 複本）。
