---
permalink: storage-mgmt/concept_what_options_do_i_have_in_fix_it_button.html 
sidebar: sidebar 
keywords: fix it,fix all 
summary: 「管理動作」頁面提供「修正」或「全部修正」按鈕、可修正Unified Manager透過事件收到通知的問題。 
---
= 當我看到「修正」或「全部修正」按鈕時、我有哪些選項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「管理動作」頁面提供*修正*或*全部修正*按鈕、可修正Unified Manager透過事件收到通知的問題。

建議您按一下按鈕、視需要修正問題。不過、如果您不確定是否要依照Unified Manager的建議來解決問題、可以執行下列動作：

|===
| 您想要做什麼？ | *行動* 


 a| 
讓Unified Manager修正所有識別物件的問題。
 a| 
按一下「*全部修復*」按鈕。



 a| 
此時請勿修正任何已識別物件的問題、並隱藏此管理動作、直到再次提出事件為止。
 a| 
按一下向下箭頭、然後按一下*「全部關閉」*。



 a| 
僅修正部分識別物件的問題。
 a| 
按一下管理動作的名稱以展開清單、並顯示所有個別的*修復動作*動作、然後依照步驟修正或取消個別的管理動作。

|===
|===
| 您想要做什麼？ | 行動 


 a| 
讓Unified Manager修正問題。
 a| 
按一下「*修正*」按鈕。



 a| 
此時請勿修正此問題、並隱藏此管理動作、直到再次提出事件為止。
 a| 
按一下向下箭頭、然後按一下*「Dismiss」（關閉）*。



 a| 
顯示此活動的詳細資料、以便您更深入瞭解問題。
 a| 
* 按一下「*修正*」按鈕、然後檢閱將套用到產生對話方塊中的修正程式。
* 按一下向下箭頭、然後按一下*檢視事件詳細資料*、以顯示「事件詳細資料」頁面。


如果您想要修正此問題、請從上述任一頁面中按一下「*修正*」。



 a| 
顯示此儲存物件的詳細資料、以便您更深入瞭解問題。
 a| 
按一下儲存物件的名稱、即可在「效能總管」或「健全狀況詳細資料」頁面中顯示詳細資料。

|===
在某些情況下、此修正會反映在接下來15分鐘的組態輪詢中。在其他情況下、驗證組態變更和淘汰事件可能需要許多小時的時間。

若要查看已完成或進行中的管理動作清單、請按一下篩選圖示、然後選取*已完成*或*進行中*。

修復以序列方式執行的所有作業、因此當您檢視「*進行中*」面板時、有些物件會有「狀態*進行中*」、而其他物件則會有「狀態*排程*」、表示它們仍在等待實作。
