---
permalink: storage-mgmt/concept_workloads_dashboard.html 
sidebar: sidebar 
keywords: workloads, overview, data center, sections 
summary: 工作負載代表儲存物件（例如Volume或LUN）的輸入/輸出（I/O）作業。儲存設備的配置方式取決於預期的工作負載需求。只有在儲存物件進出有流量時、才能使用Active IQ Unified Manager 物件來追蹤工作負載統計資料。例如、使用者開始使用資料庫或電子郵件應用程式之後、就可以使用工作負載IOPS和延遲值。 
---
= 工作負載總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作負載代表儲存物件（例如Volume或LUN）的輸入/輸出（I/O）作業。儲存設備的配置方式取決於預期的工作負載需求。只有在儲存物件進出有流量時、才能使用Active IQ Unified Manager 物件來追蹤工作負載統計資料。例如、使用者開始使用資料庫或電子郵件應用程式之後、就可以使用工作負載IOPS和延遲值。

「工作負載」頁面會顯示ONTAP 由Unified Manager管理之各個叢集的儲存工作負載摘要。它提供符合效能服務層級的儲存工作負載、以及不符合需求的儲存工作負載的累積性概覽資訊。它也能讓您評估整個資料中心叢集的總容量、可用容量和使用量（IOPS）。

[NOTE]
====
建議您評估不符合標準、無法使用或未受任何效能服務層級管理的儲存工作負載數量、並採取必要行動以確保其一致性、容量使用量及IOPS。

====
「工作負載」頁面有下列兩個區段：

* 工作負載總覽：概述ONTAP 由Unified Manager管理的各個叢集上的儲存工作負載數量。
* 資料中心總覽：概述資料中心儲存工作負載的容量與IOPS。相關資料會顯示在資料中心層級和個別的。




== 工作負載總覽區段

「工作負載總覽」區段提供儲存工作負載的累計概覽資訊。儲存工作負載的狀態會根據指派和未指派的效能服務層級來顯示。

* *已指派*：針對已指派效能服務層級的儲存工作負載、報告下列狀態：
+
** *符合*：儲存工作負載的效能取決於指派給它們的效能服務層級。如果儲存工作負載處於關聯的效能服務層級所定義的臨界值延遲範圍內、則會標示為「符合」。符合的工作負載會以藍色標示。
** *不符合*：在效能監控期間、如果儲存工作負載延遲超過相關效能服務層級所定義的臨界值延遲、則儲存工作負載會標示為「不符合」。不符合的工作負載會以橘色標示。
** *不可用*：如果儲存工作負載離線、或是無法連線至對應的叢集、則會標示為「'unable'（無法使用）」。無法使用的工作負載會以紅色標示。


* *未指派*：未指派效能服務層級的儲存工作負載、會報告為「未指派」。此號碼會由資訊圖示表示。


工作負載總數是指派和未指派工作負載的總和。

您可以按一下本節所顯示的工作負載總數、然後在「工作負載」頁面上檢視這些工作負載。

「符合效能服務層級」子區段顯示可用儲存工作負載的總數：

* 符合各種效能服務層級
* 指派的效能服務層級與建議的效能服務層級不相符




== 資料中心總覽區段

資料中心總覽區段以圖形方式呈現資料中心內所有叢集的可用和已用容量、以及IOPS。使用這些資料、您應該管理儲存工作負載的容量和IOPS。本節也會針對所有叢集的儲存工作負載顯示下列資訊：

* 資料中心內所有叢集的總容量、可用容量和已用容量
* 資料中心內所有叢集的總IOPS、可用IOPS和已使用IOPS
* 可用容量和已用容量、以每個效能服務層級為基礎
* 根據每個效能服務層級、提供可用和使用的IOPS
* 未指派效能服務層級的工作負載所使用的總空間和IOPS


*資料中心的容量與效能如何根據效能服務層級來計算*

擷取已用容量和IOPS時、會根據叢集中所有儲存工作負載的總使用容量和效能來擷取。

可用的IOPS是根據節點上的預期延遲和建議的效能服務層級來計算。其中包括所有預期延遲低於或等於其預期延遲之Performance Service層級的可用IOPS。

可用容量是根據集合體上的預期延遲和建議效能服務層級來計算。其中包括所有預期延遲低於或等於其預期延遲的Performance Service層級可用容量。
