---
permalink: storage-mgmt/concept_monitor_vms.html 
sidebar: sidebar 
keywords: monitor, virtual, machines, view, summary, topology, expand 
summary: 對於虛擬機器（VM）應用程式的任何延遲問題、您可能需要監控VM、以分析並疑難排解原因。VM可在其vCenter Server和ONTAP 託管VM儲存設備的VMware叢集新增至Unified Manager時使用。 
---
= 監控虛擬機器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於虛擬機器（VM）應用程式的任何延遲問題、您可能需要監控VM、以分析並疑難排解原因。VM可在其vCenter Server和ONTAP 託管VM儲存設備的VMware叢集新增至Unified Manager時使用。

您可以在「* VMware*>>*虛擬機器*」頁面上看到虛擬機器的詳細資料。系統會顯示可用度、狀態、已使用和已分配容量、網路延遲、以及VM、資料存放區和主機的IOPS和延遲等資訊。對於支援多個資料存放區的VM、網格會顯示延遲最短的資料存放區度量、並以星號圖示（*）表示其他資料存放區。如果按一下圖示、則會顯示其他資料存放區的度量。其中有些欄無法進行排序和篩選。

[NOTE]
====
若要檢視VM及其詳細資料、ONTAP 必須完成探索（輪詢或收集指標）。如果從Unified Manager移除叢集、則在下一個探索週期之後、虛擬機器將不再可用。

====
在此頁面中、您也可以檢視VM的詳細拓撲、顯示與VM相關的元件、例如主機、虛擬磁碟及與其相連的資料存放區。拓撲檢視會依下列順序、以其特定層級顯示基礎元件：*虛擬磁碟*>* VM*>*主機*>*網路*>*資料存放區*>* VMDK *。

您可以從拓撲層面判斷I/O路徑和元件層級延遲、並識別儲存設備是否是造成效能問題的原因。拓撲的摘要檢視會顯示I/O路徑、並強調有IOPS和延遲問題的元件、供您決定疑難排解步驟。您也可以展開拓撲檢視、分別描述每個元件以及該元件的延遲。您可以選取元件、以決定在各層中反白顯示的I/O路徑。



== 檢視摘要拓撲

若要在摘要拓撲中檢視VM來判斷效能問題：

. 轉至* VMware*>*虛擬機器*。
. 在搜尋方塊中輸入VM名稱、即可搜尋VM。您也可以按一下「*篩選*」按鈕、根據特定條件篩選搜尋結果。不過、如果找不到VM、請確定已新增並探索對應的vCenter Server。
+
[NOTE]
====
vCenter Server允許使用特殊字元（例如%、&、*、$、#、 @、！、\、/、：、 *、？、"、"、<、>、 在vSphere實體名稱中、例如VM、叢集、資料存放區、資料夾、 或檔案。VMware vCenter Server和ESX/ESXi Server不會轉義顯示名稱中使用的特殊字元。不過、在Unified Manager中處理名稱時、其顯示方式會有所不同。例如、vCenter Server中名為「%$VC_AIQUM_clone」的VM、在Unified Manager中顯示為「%25$VC_AIQUM_clone _19124%25」。當您查詢名稱中有特殊字元的VM時、必須記下此問題。

====
. 檢查VM的狀態。VM狀態會從vCenter Server擷取。下列狀態可供使用。如需這些狀態的詳細資訊、請參閱VMware文件。
+
** 正常
** 警告
** 警示
** 未監控
** 不明


. 按一下VM旁的向下箭頭、即可查看整個運算、網路和儲存層元件拓撲的摘要檢視。出現延遲問題的節點會反白顯示。摘要檢視會顯示元件的最短延遲時間。例如、如果VM有多個虛擬磁碟、此檢視會顯示所有虛擬磁碟之間延遲最短的虛擬磁碟。
. 若要分析資料存放區一段時間內的延遲和處理量、請按一下資料存放區物件圖示頂端的*工作負載分析器*按鈕。您可以前往「工作負載分析」頁面、選取時間範圍並檢視資料存放區的效能圖表。如需工作負載分析器的詳細資訊、請參閱_使用工作負載分析器疑難排解工作負載_。




== 檢視擴充拓撲

您可以檢視VM的擴充拓撲、分別深入各個元件。

.步驟
. 在摘要拓撲檢視中、按一下*展開拓撲*。您可以分別查看每個元件的詳細拓撲、以及每個物件的延遲數。如果類別中有多個節點（例如資料存放區或VMDK中有多個節點）、則延遲時間最短的節點會以紅色強調顯示。
. 若要檢查特定物件的IO路徑、請按一下該物件以查看IO路徑和對應。例如、若要查看虛擬磁碟的對應關係、請按一下虛擬磁碟、以檢視其反白顯示的對應關係至各自的VMDK。如果這些元件的效能延遲、您可以從ONTAP VMware收集更多資料、並疑難排解問題。
+
[NOTE]
====
不會報告VMDK的度量。在拓撲中、只會顯示VMDK名稱、而不會顯示度量。

====


*相關資訊*

link:../performance-checker/concept_troubleshooting_workloads_using_workload_analyzer.html["使用工作負載分析程式疑難排解工作負載"]
