---
permalink: storage-mgmt/concept_manage_performance_service_levels.html 
sidebar: sidebar 
keywords: manage, performance, service, levels 
summary: 效能服務層級可讓您定義工作負載的效能與儲存目標。您可以在最初建立工作負載時、或之後編輯工作負載、將效能服務層級指派給工作負載。 
---
= 管理效能服務層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能服務層級可讓您定義工作負載的效能與儲存目標。您可以在最初建立工作負載時、或之後編輯工作負載、將效能服務層級指派給工作負載。

儲存資源的管理與監控是以服務層級目標（SLO）為基礎。SLO是由服務層級協議所定義、這些協議是以所需的效能和容量為基礎。在Unified Manager中、SLO是指在NetApp儲存設備上執行之應用程式的PSL定義。儲存服務會根據基礎資源的效能與使用率而有所差異。PSL是儲存服務目標的說明。PSL可讓儲存供應商指定工作負載的效能與容量目標。

Unified Manager提供幾種無法變更的既定原則。這些預先定義的效能服務層級包括：極致效能、效能和價值。極致效能、效能和價值的PSL適用於資料中心的大多數常見儲存工作負載。Unified Manager也針對資料庫應用程式提供三種PSL：「資料庫記錄的極限」、「資料庫共享資料的極限」、以及「資料庫資料的極限」。這些是極高效能的PSL、可支援爆發式IOPS、適合處理量需求最高的資料庫應用程式。如果這些預先定義的PSL不符合您的需求、您可以建立新的PSL來滿足您的需求。

您可以從「*原則*>*效能服務層級*」頁面、以及使用儲存供應商API來存取PSL。指派PSL來管理儲存工作負載非常方便、因為您不需要個別管理儲存工作負載。您也可以重新指派另一個PSL來管理任何修改、而非個別管理。

您無法修改系統定義或目前指派給工作負載的PSL。您無法刪除指派給工作負載的PSL、或是唯一可用的PSL。

「效能服務層級」頁面會列出可用的PSL原則、並可讓您新增、編輯及刪除這些原則。此頁面顯示下列資訊：

|===
| 欄位 | 說明 


 a| 
名稱
 a| 
效能服務層級的名稱。



 a| 
類型
 a| 
原則是由系統定義還是由使用者定義。



 a| 
預期的IOPS
 a| 
預期應用程式在LUN或檔案共用區上執行的IOPS下限。預期IOPS會根據儲存物件配置的大小、指定所配置的預期IOPS下限。



 a| 
尖峰IOPS
 a| 
應用程式可在LUN或檔案共用區上執行的IOPS上限。尖峰IOPS會根據儲存物件配置的大小或儲存物件使用的大小、指定可能配置的IOPS上限。

尖峰IOPS是以配置原則為基礎。分配原則為已配置空間或已使用空間。當分配原則設定為分配空間時、尖峰IOPS會根據儲存物件的大小來計算。當分配原則設定為已用空間時、尖峰IOPS會根據儲存物件中儲存的資料量來計算、並考量儲存效率。根據預設、配置原則會設為「已使用空間」。



 a| 
絕對最低IOPS
 a| 
當預期的IOPS低於此值時、絕對最低IOPS會被用作置換。系統定義的PSL的預設值如下：

* 極致效能：如果預期IOPS >= 6144/TB、則絕對最小IOPS = 1000
* 效能：如果預期IOPS >= 2048/ TB及< 6144/TB、則絕對最小IOPS = 500
* 值：如果預期IOPS >= 128/TB及< 2010/TB、則絕對最小IOPS = 75


系統定義的資料庫PSL預設值如下：

* 資料庫記錄的極致效能：如果預期IOPS >= 22528、則絕對最低IOPS = 4000
* 資料庫共享資料的極致效能：如果預期IOPS >= 16384、則絕對最小IOPS = 2000
* 資料庫資料的極致效能：如果預期IOPS >= 12288、則絕對最低IOPS = 2000


自訂PSL的絕對最小IOPS值越高、最高可達75000。較低值的計算方式如下：

每預期延遲1000次



 a| 
預期延遲
 a| 
每次作業的儲存IOPS預期延遲（毫秒/秒）。



 a| 
容量
 a| 
叢集中的可用和已用容量總計。



 a| 
工作負載
 a| 
已指派PSL的儲存工作負載數量。

|===
如需IOPS尖峰和預期IOPs如何協助ONTAP 在VMware叢集上實現一致的差異化效能、請參閱下列知識庫文章：

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/Active_IQ_Unified_Manager/What_is_Performance_Budgeting%3F["什麼是績效預算？"]

請注意、如果工作負載超過前一小時30%的預期延遲值、Unified Manager將產生下列其中一項事件、通知您可能發生的效能問題： 「工作負載Volume延遲臨界值違反效能服務層級原則定義」或「工作負載LUN延遲臨界值違反效能服務層級原則定義」。您可能想要分析工作負載、以瞭解造成較高延遲值的原因。

下表提供系統定義的PSL相關資訊：

|===
| 效能服務層級 | 說明與使用案例 | 預期延遲（毫秒/作業） | 尖峰IOPS | 預期的IOPS | 絕對最低IOPS 


 a| 
極致效能
 a| 
以極低的延遲提供極高的處理量

適用於對延遲敏感的應用程式
 a| 
1.
 a| 
12288
 a| 
6144
 a| 
1000



 a| 
效能
 a| 
以低延遲提供高處理量

非常適合資料庫與虛擬化應用程式
 a| 
2.
 a| 
4096
 a| 
2048
 a| 
500



 a| 
價值
 a| 
提供高儲存容量和中度延遲

適用於電子郵件、網路內容、檔案共用及備份目標等高容量應用程式
 a| 
17
 a| 
512
 a| 
128/128
 a| 
75



 a| 
資料庫記錄的極致功能
 a| 
以最低延遲提供最大處理量。

非常適合支援資料庫記錄的資料庫應用程式。此PSL提供最高的處理量、因為資料庫記錄檔極具爆發性、而且記錄功能持續需求。
 a| 
1.
 a| 
45056
 a| 
22528
 a| 
4000



 a| 
極致資料庫共享資料
 a| 
以最低延遲提供極高的處理量。

適用於儲存在通用資料儲存區中、但跨資料庫共用的資料庫應用程式資料。
 a| 
1.
 a| 
32768
 a| 
16384
 a| 
2000年



 a| 
資料庫資料的極致利器
 a| 
以最低延遲提供高處理量。

非常適合資料庫應用程式資料、例如資料庫表格資訊和中繼資料。
 a| 
1.
 a| 
24576
 a| 
12288
 a| 
2000年

|===