---
permalink: storage-mgmt/concept_assign_policies_on_workloads.html 
sidebar: sidebar 
keywords: assign, policies, workloads, single, multiple, storage, system-recommended, psls 
summary: 您可以使用不同的導覽選項、從「所有工作負載」頁面將儲存效率原則（DDP）和效能服務層級（PSL）指派給儲存工作負載。 
---
= 指派原則給工作負載
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用不同的導覽選項、從「所有工作負載」頁面將儲存效率原則（DDP）和效能服務層級（PSL）指派給儲存工作負載。



== 指派原則給單一工作負載

您可以將PSL或SEP或兩者指派給單一工作負載。請遵循下列步驟：

. 選取工作負載。
. 按一下該列旁的編輯圖示、然後按一下*編輯*。
+
「*指派的效能服務層級*」和「*儲存效率原則*」欄位已啟用。

. 選取所需的PSL或SEP、或兩者。
. 按一下核取圖示以套用變更。


[NOTE]
====
您也可以選取工作負載、然後按一下*「更多動作」*指派原則。

====


== 指派原則給多個儲存工作負載

您可以將一個PSL或一個SEP指派給多個儲存工作負載。請遵循下列步驟：

. 選取您要指派原則之工作負載的核取方塊、或選取資料中心內的所有工作負載。
. 按一下*更多動作*。
. 若要指派PSL、請選取*指派效能服務層級*。若要指派SEP、請選取*指派儲存效率原則*。隨即顯示快顯視窗、供您選取原則。
. 選取適當的原則、然後按一下*「Apply *（套用*）」。顯示指派原則的工作負載數目。也會列出未指派原則的工作負載、以及原因。
+
[NOTE]
====
根據所選的工作負載數量、在大量工作負載上套用原則可能需要一些時間。您可以按一下*在背景中執行*按鈕、然後在作業於背景中執行時繼續執行其他工作。當大量指派完成時、您可以檢視完成狀態。如果您要在多個工作負載上套用PSL、則無法在執行上一個大量指派工作時觸發另一個要求。

====




== 將系統建議的PSL指派給工作負載

您可以將系統建議的PSL指派給資料中心中未指派任何PSL的儲存工作負載、或指派的PSL與系統建議不符。若要使用此功能、請按一下*指派系統建議的PSL*按鈕。您不需要選取特定的工作負載。

建議由系統分析內部決定、並針對IOPS和其他參數與任何可用PSL定義不一致的工作負載跳過。此外、還會排除「等待I/O」和「學習」狀態的儲存工作負載。

[NOTE]
====
Unified Manager會在工作負載名稱中尋找特殊關鍵字、以覆寫系統分析、並針對工作負載建議不同的PSL。如果工作負載名稱中有字母「'ora'」、建議使用「**極致效能」。當工作負載名稱中有字母「VM」時、建議使用「**效能」。

====