---
permalink: storage-mgmt/reference_dashboard_page.html 
sidebar: sidebar 
keywords: dashboard page, 
summary: 「儀表板」頁面有「面板」、顯示您所監控叢集的高層容量、效能和安全性健全狀況。本頁也提供「管理動作」面板、其中列出Unified Manager解決特定事件時所能做的修正。 
---
= 儀表板頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「儀表板」頁面有「面板」、顯示您所監控叢集的高層容量、效能和安全健全狀況。本頁也提供「管理動作」面板、其中列出Unified Manager解決特定事件時所能做的修正。

大部分面板也會顯示該類別中的作用中事件數目、以及在過去24小時內新增的新事件數目。此資訊可協助您決定需要進一步分析哪些叢集才能解決事件。按一下事件會顯示最常發生的事件、並提供已篩選事件管理詳細目錄頁面的連結、以顯示該類別中的作用中事件。

在儀表板頂端、您可以選取面板顯示所有受監控叢集（「所有叢集」）或個別叢集的資訊。您可以先檢視所有叢集的狀態、然後在想要檢視詳細資訊時深入檢視個別叢集。

[NOTE]
====
下列部分面板會根據您的組態顯示在儀表板上。

====


== 「管理行動」面板

Unified Manager可能會徹底診斷並提供單一解決方案、如果可用、這些解析度會顯示在此面板中、並顯示*修正*或*全部修正*按鈕。您可以從Unified Manager立即修正這些問題、而不需要使用ONTAP 功能介紹系統管理程式或ONTAP 功能介紹CLI。若要檢視所有問題、請按一下「請參閱」 link:concept_fix_ontap_issues_directly_from_unified_manager.html["直接從ONTAP Unified Manager修正各種問題"] 以取得更多資訊。



== 容量面板

檢視所有叢集時、此面板會顯示每個叢集的實體已用容量（套用儲存效率節約效益之後）和實體可用容量（不包括可能的儲存效率節約）、預計磁碟滿之前的天數、 資料減量比率則是根據設定ONTAP 的整套儲存效率設定而來。也會列出任何已設定雲端層的已用容量。按一下長條圖、即可前往該叢集的Aggregate詳細目錄頁面。按一下「待滿天數」文字會顯示一則訊息、指出該Aggregate的剩餘容量天數最少；按一下Aggregate名稱即可查看更多詳細資料。

檢視單一叢集時、此面板會顯示資料集合的實體已用容量和實體可用容量、這些資料集合體會依本機層和雲端層上的每個個別磁碟類型進行排序。按一下磁碟類型的長條圖、即可前往使用該磁碟類型之磁碟區的「Volumes」（磁碟區）詳細目錄頁面。



== 效能容量面板

檢視所有叢集時、此面板會顯示每個叢集的效能容量值（過去1小時的平均值）、以及效能容量達到上限的天數（根據每日成長率而定）。按一下長條圖、即可前往該叢集的「節點」目錄頁面。請注意、節點庫存頁面會顯示過去72小時內的平均效能容量。按一下「待滿天數」文字會顯示一則訊息、指出該節點的剩餘效能容量天數最少；按一下節點名稱即可查看更多詳細資料。

檢視單一叢集時、此面板會顯示所用叢集效能容量百分比、IOPS總計和總處理量（MB/s）值、以及預計這三項指標達到上限之前的天數。



== 工作負載IOPS面板

檢視單一叢集時、此面板會顯示目前在特定IOPS範圍內執行的工作負載總數、並在游標停留在圖表上時指出每個磁碟類型的數目。



== 工作負載效能面板

此面板會顯示指派給每個效能服務層級（PSL）原則的符合性和不符合性工作負載總數。也會顯示未指派PSL的工作負載數量。按一下長條圖、即可在「工作負載」頁面中找到指派給該原則的符合性工作負載。按一下長條圖後的數字、即可前往指派給該原則的符合性和不符合要求的工作負載。



== 安全性面板

「安全性」面板會根據您目前的檢視、顯示所有叢集或單一叢集的高層級安全性狀態。此面板顯示：

* 過去24小時內收到的安全事件清單。按一下事件、即可在「活動詳細資料」頁面上檢視詳細資料
* 叢集安全性狀態（相容和不相容叢集的數量）
* 儲存VM安全狀態（相容與不相容儲存VM的數量）
* Volume加密狀態（已加密或未加密的磁碟區數）
* Volume反勒索軟體狀態（已啟用或停用反勒索軟體的Volume數）


您可以按一下相容和不相容叢集、儲存VMS、加密和未加密磁碟區、以及Volume反勒索軟體狀態的長條圖、前往各自的頁面、檢視篩選後叢集、儲存VM和磁碟區的安全詳細資料。

法規遵循是以為基礎 http://www.netapp.com/us/media/tr-4569.pdf["《NetApp ONTAP 資訊安全強化指南》（英文）9"]。按一下面板頂端的向右箭頭、即可在「安全性」頁面上檢視所有叢集的安全性詳細資料。如需相關資訊、請參閱link:../health-checker/task_view_detailed_security_status_for_clusters_and_svms.html["檢視叢集和儲存VM的詳細安全狀態"]。



== 資料保護面板

此面板會顯示資料中心中單一或所有叢集的資料保護摘要。它會顯示資料保護事件總數、MetroCluster 不實事件、ONTAP 以及過去24小時內提出的作用中事件數。按一下每個事件的連結、即可前往「活動詳細資料」頁面。您可以按一下「*檢視全部*」連結、在「事件管理」目錄頁面中檢視所有作用中的保護事件。面板會顯示：

* 叢集中的磁碟區數目、或是資料中心內受Snapshot複本保護的所有叢集數目。
* 叢集中的磁碟區數目、或是資料中心內受SnapMirror關係保護的所有叢集數目。對於SnapMirror關係、會考量來源叢集的磁碟區數。
* 透過MetroCluster IP或FC進行的靜態組態保護資料中心內的叢集或所有叢集數目。
* 根據延遲狀態、與SnapMirror恢復點目標（RPO）的磁碟區關係數。


您可以將滑鼠游標暫留、以檢視各個計數和圖例。您可以按一下面板頂端的向右箭頭、在「資料保護」頁面上檢視單一或所有叢集的詳細資料。此外、您也可以按一下：

* 受Snapshot複本保護之未受保護的磁碟區和磁碟區的長條圖、可前往「Volumes（磁碟區）」頁面並檢視詳細資料。
* 受保護或未受MetroCluster 等化組態保護之叢集的橫條圖、可前往「叢集」頁面並檢視詳細資料。
* 所有關聯的長條圖會移至「關聯」頁面、其中的詳細資料會根據來源叢集進行篩選。


如需詳細資訊、請參閱 link:../data-protection/view-protection-status.html["檢視Volume保護狀態"]。



== 使用概觀面板

檢視所有叢集時、您可以選擇檢視依最高IOPS、最高處理量（MB/s）或最高使用實體容量排序的叢集。

檢視單一叢集時、您可以選擇依最高IOPS、最高處理量（MB/s）或使用量最高的邏輯容量來檢視工作負載。

*相關資訊*

link:../events/task_fix_issues_using_um_automatic_remediations.html["使用Unified Manager自動修正來修正問題"]

link:../performance-checker/task_display_information_about_performance_event.html["顯示效能事件的相關資訊"]

link:../performance-checker/concept_manage_performance_using_perf_capacity_available_iops.html["使用效能容量和可用IOPS資訊來管理效能"]

link:../health-checker/reference_health_volume_details_page.html["Volume / Health詳細資料頁面"]

link:../performance-checker/reference_performance_event_analysis_and_notification.html["效能事件分析與通知"]

link:../events/reference_description_of_event_severity_types.html["事件嚴重性類型說明"]

link:../performance-checker/concept_sources_of_performance_events.html["效能事件來源"]

link:../health-checker/concept_manage_cluster_security_objectives.html["管理叢集安全目標"]

link:../performance-checker/concept_monitor_cluster_performance_from_cluster_landing_page.html["從效能叢集登陸頁面監控叢集效能"]

link:../performance-checker/concept_monitor_performance_using_object_performance.html["使用「效能詳細目錄」頁面監控效能"]
