---
permalink: storage-mgmt/reference_what_ontap_issues_can_unified_manager_fix.html 
sidebar: sidebar 
keywords: ontap issues, fix it action, automatic remediation feature, remediation events, fix-it messages, fix-it events 
summary: 下表說明ONTAP Unified Manager可直接從Unified Manager使用者介面按一下「修正」或「全部修正」按鈕來解決的各種問題。 
---
= Unified Manager可以修正哪些問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過Active IQ Unified Manager 使用VMware的自動補救功能、您可以選擇透過ONTAP Unified Manager有效解決某些問題、或管理ONTAP 某些功能、例如防勒索軟體監控。

下表說明ONTAP 這些可直接透過Unified Manager網路UI上的*修正*或*修復全部*按鈕來管理的問題或功能。

|===
| 活動名稱與說明 | 管理行動 | 「修正」作業 


 a| 
Volume空間已滿

磁碟區幾乎空間不足、而且已超出容量已滿臨界值。此臨界值預設為磁碟區大小的90%。
 a| 
啟用Volume自動擴充
 a| 
Unified Manager會判斷此磁碟區未設定自動擴充磁碟區、因此會啟用此功能、以便磁碟區在需要時能夠增加容量。



 a| 
inode已滿

此磁碟區已用完inode、無法接受任何新檔案。
 a| 
增加Volume上的inode數量
 a| 
將Volume上的inode數量增加2%。



 a| 
偵測到儲存層原則不符

磁碟區有許多非作用中資料、而目前的分層原則設定為「純快照」或「無」。
 a| 
實現自動雲端分層
 a| 
由於Volume已位於FabricPool 某個物件上、因此它會將分層原則變更為「自動」、以便將非作用中資料移至成本較低的雲端層。



 a| 
偵測到儲存層不符

磁碟區有大量的非使用中資料、但並未存放在雲端型儲存層FabricPool （簡稱「）」上。
 a| 
變更磁碟區的儲存層
 a| 
將磁碟區移至具備雲端功能的儲存層、並將分層原則設為「自動」、以便將非使用中的資料移至雲端層。



 a| 
稽核記錄已停用

未針對儲存VM啟用稽核記錄
 a| 
啟用儲存VM的稽核記錄
 a| 
在儲存VM上啟用稽核記錄。

請注意、儲存VM必須已設定本機或遠端稽核記錄位置。



 a| 
登入橫幅已停用

應啟用叢集的登入橫幅、以便清除存取限制、以提高安全性。
 a| 
設定叢集的登入橫幅
 a| 
將叢集登入橫幅設定為「存取限制為授權使用者」。



 a| 
登入橫幅已停用

應啟用儲存VM的登入橫幅、以清楚明瞭存取限制、藉此提高安全性。
 a| 
設定儲存VM的登入橫幅
 a| 
將儲存VM登入橫幅設定為「僅限授權使用者存取」。



 a| 
SSH正在使用不安全的密碼

以「-CBC」為結尾的密碼被視為不安全。
 a| 
從叢集移除不安全的密碼
 a| 
從叢集移除不安全的密碼（例如aes192-CBC和AES120-CBC）。



 a| 
SSH正在使用不安全的密碼

以「-CBC」為結尾的密碼被視為不安全。
 a| 
從儲存VM移除不安全的密碼
 a| 
從儲存VM移除不安全的密碼（例如aes192-CBC和AES120-CBC）。



 a| 
已停用支援HTTPS傳輸AutoSupport

用來傳送AutoSupport 資訊給技術支援的傳輸傳輸傳輸協定應加密。
 a| 
將HTTPS設為AutoSupport 傳輸傳輸傳輸傳輸協定、以利傳達資訊
 a| 
將HTTPS設為AutoSupport 叢集上的傳輸傳輸傳輸傳輸傳輸協定。



 a| 
叢集負載不平衡臨界值已超出

表示叢集中節點之間的負載不平衡。當節點之間的效能容量使用量差異超過30%時、就會產生此事件。
 a| 
平衡叢集工作負載
 a| 
Unified Manager可識別從一個節點移至另一個節點的最佳磁碟區、以降低不平衡、然後移動磁碟區。



 a| 
叢集容量不平衡臨界值已超出

表示叢集中的集合體之間的容量不平衡。當集合體之間使用的容量差異超過70%時、就會產生此事件。
 a| 
平衡叢集容量
 a| 
Unified Manager可識別從一個集合體移至另一個集合體的最佳磁碟區、以減少不均衡的情況、然後移動該磁碟區。



 a| 
效能容量已用臨界值超出

表示如果您未減少一或多個高作用中工作負載的使用率、則節點上的負載可能會過度使用。當節點效能使用容量值超過100%達12小時以上時、就會產生此事件。
 a| 
限制節點的高負載
 a| 
Unified Manager會識別IOPS最高的磁碟區、並使用預期的歷史和尖峰IOPS層級來套用QoS原則、以降低節點上的負載。



 a| 
已違反動態事件警告臨界值

表示由於部分工作負載的負載異常高、因此節點已處於過載狀態。
 a| 
減少節點過載
 a| 
Unified Manager會識別IOPS最高的磁碟區、並使用預期的歷史和尖峰IOPS層級來套用QoS原則、以降低節點上的負載。



 a| 
無法接管

容錯移轉目前已停用、因此在中斷運作或重新開機期間、存取節點資源的權限將會遺失、直到節點再次可用為止。
 a| 
啟用節點容錯移轉
 a| 
Unified Manager會傳送適當的命令、在叢集中的所有節點上啟用容錯移轉。



 a| 
選項Cf.takeake.on_p恐慌 已設定為關閉

nodesdrof選項"cf.takee.on_poc"設定為* off*、這可能會在HA設定的系統上造成問題。
 a| 
在緊急情況下啟用接管
 a| 
Unified Manager會傳送適當的命令給叢集、將此設定變更為*開啟*。



 a| 
停用nodesdro解除 選項SnapMirror。enable

舊的nodesdro重 選項"SnapMirror．enable（SnapMirror．enable）設置爲* on*（打開*），在升級ONTAP 至版本9.3或更新版本後引導時可能會出現問題。
 a| 
將SnapMirror.enable選項設為Off
 a| 
Unified Manager會傳送適當的命令給叢集、將此設定變更為*關*。



 a| 
已啟用遠端登入

表示潛在的安全問題、因為遠端登入不安全、而且以未加密的方式傳輸資料。
 a| 
停用遠端登入
 a| 
Unified Manager會傳送適當的命令給叢集、以停用遠端登入。



 a| 
設定儲存VM反勒索軟體學習

定期檢查具有授權的叢集、以進行反勒索軟體監控。驗證儲存VM是否僅支援這類叢集中的NFS或SMB磁碟區。
 a| 
將儲存虛擬機器置於防勒索軟體監控的「學習」模式
 a| 
Unified Manager會透過叢集管理主控台、將儲存VM的反勒索軟體監控設定為「學習」狀態。在儲存VM上建立的所有新磁碟區上進行的反勒索軟體監控、會自動移至學習模式。透過這項功能、ONTAP 我們可以瞭解磁碟區上的活動模式、並偵測潛在惡意攻擊所造成的異常狀況。



 a| 
設定Volume反勒索軟體學習

定期檢查具有授權的叢集、以進行反勒索軟體監控。驗證磁碟區是否僅支援這類叢集中的NFS或SMB服務。
 a| 
將Volume置於「學習」模式的反勒索軟體監控
 a| 
Unified Manager會透過叢集管理主控台、將磁碟區的反勒索軟體監控設定為「學習」狀態。透過這項功能、ONTAP 我們可以瞭解磁碟區上的活動模式、並偵測潛在惡意攻擊所造成的異常狀況。



 a| 
啟用Volume反勒索軟體

定期檢查具有授權的叢集、以進行反勒索軟體監控。偵測磁碟區是否處於禁勒索軟體監控的「學習」模式達45天以上、並判斷是否有可能將其置於主動模式。
 a| 
將磁碟區置於「主動」模式的反勒索軟體監控
 a| 
Unified Manager會透過叢集管理主控台、將磁碟區上的勒索軟體監控設定為「主動」。透過這項功能、ONTAP 我們可以瞭解磁碟區上的活動模式、偵測潛在惡意攻擊所造成的異常狀況、並建立資料保護行動警示。



 a| 
停用Volume反勒索軟體

定期檢查具有授權的叢集、以進行反勒索軟體監控。在磁碟區上監控主動式勒索軟體期間偵測重複通知（例如、在30天內傳回多個可能勒索軟體攻擊的警告）。
 a| 
停用磁碟區上的勒索軟體監控功能
 a| 
Unified Manager會透過叢集管理主控台停用磁碟區上的勒索軟體監控功能。

|===