---
permalink: storage-mgmt/task_change_time_um_retains_event_performance_data.html 
sidebar: sidebar 
keywords: change, length, time, unified manager, retains, event, performance, data 
summary: 根據預設、Unified Manager會將所有受監控叢集的事件資料和效能資料儲存6個月。在此之後、舊資料會自動刪除、以便保留新資料的空間。此預設時間範圍適用於大多數組態、但對於許多叢集和節點的大型組態而言、可能需要縮短保留時間、以便Unified Manager以最佳方式運作。 
---
= 更改 Unified Manager 保留事件和效能資料的時間長度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據預設、Unified Manager會將所有受監控叢集的事件資料和效能資料儲存6個月。在此之後、舊資料會自動刪除、以便保留新資料的空間。此預設時間範圍適用於大多數組態、但對於許多叢集和節點的大型組態而言、可能需要縮短保留時間、以便Unified Manager以最佳方式運作。

.開始之前
您必須具有應用程式管理員角色。

您可以在「資料保留」頁面中變更這兩種資料類型的保留期間。這些設定會影響此Unified Manager執行個體所監控之所有叢集的資料保留。

[NOTE]
====
Unified Manager每5分鐘收集一次效能統計資料。每天5分鐘的統計資料都會摘要整理成每小時的效能統計資料。它保留30天的5分鐘歷史效能資料、以及6個月的每小時彙總效能資料（預設）。

====
只有當空間不足、或備份和其他作業需要很長時間才能完成時、才應縮短保留期間。縮短保留期間會產生下列影響：

* 舊的效能資料會在午夜後從Unified Manager資料庫中刪除。
* 舊的事件資料會立即從Unified Manager資料庫中刪除。
* 保留期間之前的事件將不再可在使用者介面中檢視。
* UI中顯示每小時效能統計資料的位置、在保留期間之前將會空白。
* 如果事件保留期間超過效能資料保留期間、效能滑桿下方會顯示一則訊息、警告舊的效能事件在相關圖表中可能沒有備用資料。


.步驟
. 在左導覽窗格中、按一下*原則*>*資料保留*。
. 在「*資料保留*」頁面中、選取「事件保留」或「效能資料保留」區域中的滑桿工具、並將其移至應保留資料的月份數、然後按一下「*儲存*」。

