---
permalink: storage-mgmt/task_export_storage_data_as_reports.html 
sidebar: sidebar 
keywords: export, storage, data, reports 
summary: 您可以匯出各種輸出格式的儲存資料、然後使用匯出的資料來建置報告。例如、如果有10個尚未解決的重大事件、您可以從「事件管理」目錄頁匯出資料以建立報告、然後將報告傳送給可解決問題的管理員。 
---
= 將儲存資料匯出為報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以匯出各種輸出格式的儲存資料、然後使用匯出的資料來建置報告。例如、如果有10個尚未解決的重大事件、您可以從「事件管理」目錄頁匯出資料以建立報告、然後將報告傳送給可解決問題的管理員。

您可以從* Storage *和* Network *目錄頁匯出資料至「.csv'」檔案、「.xlsx'」檔案或「.pdf」文件、並使用匯出的資料來建置報告。產品中還有其他只能產生「.csv"或「.pdf」檔案的位置。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您要匯出... | 執行此動作... 


 a| 
儲存物件詳細目錄
 a| 
按一下左導覽功能表中的「*儲存設備*」或「*網路*」、然後選取儲存物件。選擇系統提供的其中一個檢視、或是您建立的任何自訂檢視。



 a| 
QoS原則群組詳細資料
 a| 
從左側導覽功能表中按一下「*儲存設備*>* QoS原則群組*」。



 a| 
儲存容量與保護記錄詳細資料
 a| 
按一下「*儲存設備*>*集合體*」或「*儲存設備*>*磁碟區*」、然後選取單一集合體或磁碟區。



 a| 
活動詳細資料
 a| 
從左側導覽功能表中按一下*事件管理*。



 a| 
儲存物件前10大效能詳細資料
 a| 
按一下「*儲存設備*>*叢集*>*效能：所有叢集*」、然後選取一個叢集、再選擇「*效能最佳者*」索引標籤。然後選取儲存物件和效能計數器。

|===
. 按一下「* Reports*（報告*）」按鈕（或是某些UI頁面中的「* Export *（匯出*）」按鈕）。
. 按一下*下載CSV*、*下載PDF*或*下載Excel*以確認匯出要求。
+
您可以從「績效最佳者」索引標籤、選擇下載您正在檢視之單一叢集或資料中心內所有叢集的統計資料報告。

+
檔案即會下載。

. 在適當的應用程式中開啟檔案。


*相關資訊*

link:["健全狀況/叢集資源清冊頁面"]

link:../reporting/task_schedule_report.html["排程報告"]
