---
permalink: storage-mgmt/task_monitor_metrocluster_replication.html 
sidebar: sidebar 
keywords: monitor, metrocluster, replication 
summary: 鏡射資料時、您可以監控及診斷邏輯連線的整體健全狀況。您可以識別中斷叢集元件鏡射（例如集合體、節點和儲存虛擬機器）的問題或任何風險。 
---
= 監控MetroCluster 功能複寫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
鏡射資料時、您可以監控及診斷邏輯連線的整體健全狀況。您可以識別中斷叢集元件鏡射（例如集合體、節點和儲存虛擬機器）的問題或任何風險。

Unified Manager會使用系統健全狀況警示來監控MetroCluster 元件的狀態、以及在功能性方面的連線能力。

*您需要的是什麼*

必須在Unified Manager中新增本地和遠端MetroCluster 叢集的不二項功能



== 檢視MetroCluster 透過IP組態進行的複寫

對於透過IP進行的靜態組態、資料複寫狀態會顯示在「拓撲預覽」檢視中、以透過Unified Manager左側導覽窗格的下列檢視畫面來顯示受透過IP保護的叢集：MetroCluster MetroCluster

* *儲存設備*>*叢集*>*保護：MetroCluster Section*檢視
* *保護*>*關係**關係：MetroCluster 參考*檢視


如需相關資訊、請參閱 link:../storage-mgmt/task_monitor_metrocluster_configurations.html#monitor-connectivity-issues-in-metrocluster-over-ip["監控MetroCluster IP上的連接問題"]。



== 檢視MetroCluster 透過FC組態進行的複寫

請遵循下列步驟、判斷MetroCluster 資料複寫中是否有任何問題、以利利用FC組態進行資料複寫。

.步驟
. 在左導覽窗格中、按一下「*儲存設備*>*叢集*」。
+
隨即顯示受監控叢集的清單。

. 在「*健全狀況：所有叢集*」檢視中、按一下您要檢視MetroCluster 其內容的叢集名稱。在「*叢集/健全狀況詳細資料*」頁面上、按一下「* MetroCluster 還原複寫*」索引標籤。
+
要複寫之版本資訊的拓撲MetroCluster 會顯示在對應叢集物件區域的本機站台上、並顯示有關正在鏡射資料之遠端站台的資訊。如果將指標移到圖示上、您可以檢視所產生事件的詳細資訊。



您可以使用叢集/健全狀況詳細資料頁面中顯示的資訊來修正任何複寫問題。如果MetroCluster 發現在您的支援功能組態中有鏡射問題、您必須登入System Manager或存取ONTAP 該CLI來解決問題。

*相關資訊*

link:../health-checker/reference_health_cluster_details_page.html["叢集/健全狀況詳細資料頁面"]
