---
permalink: storage-mgmt/task_provision_fileshares.html 
sidebar: sidebar 
keywords: provision, file, share, volumes 
summary: 您可以從「資源配置工作負載」頁面、在現有叢集和儲存虛擬機器（儲存VM）上建立支援CIFS/SMB和NFS傳輸協定的檔案共用磁碟區。 
---
= 資源配置檔案共用磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「資源配置工作負載」頁面、在現有叢集和儲存虛擬機器（儲存VM）上建立支援CIFS/SMB和NFS傳輸協定的檔案共用磁碟區。

*您需要的是什麼*

* 儲存虛擬機器必須有空間來配置檔案共用磁碟區。
* 您的儲存VM上應同時啟用SMB和NFS服務的其中一項或兩項。
* 若要在工作負載上選取並指派效能服務層級（PSL）和儲存效率原則（SEP）、必須先建立原則、才能開始建立工作負載。


.步驟
. 在「*資源配置工作負載*」頁面上、新增您要建立的工作負載名稱、然後從「可用」清單中選取叢集。
. 根據您選取的叢集、*儲存VM*欄位會篩選該叢集的可用儲存VM。從清單中選取所需的儲存VM。
+
根據儲存VM上支援的SMB和NFS服務、NAS選項會在Host Information（主機資訊）區段中啟用。

. 在「Storage and Optimization（儲存與最佳化）」區段中、指派儲存容量和PSL、並選擇性指派工作負載的SEP。
+
SEP的規格會指派給LUN、而PSL的定義會在工作負載建立時套用至該工作負載。

. 如果您想要強制執行指派給工作負載的PSL、請選取*強制效能限制*核取方塊。
+
將PSL指派給工作負載、可確保建立工作負載的集合體能夠支援個別原則中定義的效能和容量目標。例如、如果指派「極致效能」「PSL」給某個工作負載、則要配置工作負載的集合體應該能夠支援「極致效能」原則的效能與容量目標、例如SSD儲存設備。

+
[NOTE]
====
除非選取此核取方塊、否則不會將PSL套用至工作負載、儀表板上的工作負載狀態會顯示為未指派。

====
. 選取「* NAS *」選項。
+
如果您看不到「* NAS *」選項已啟用、請確認您選取的儲存VM是否支援SMB或NFS、或兩者皆支援。

+
[NOTE]
====
如果您的儲存VM同時啟用SMB和NFS服務、您可以選取*「Share by NFS*」和「* Share by SMB*」核取方塊、然後建立同時支援NFS和SMB傳輸協定的檔案共用區。如果您想要建立SMB或CIFS共用區、請選取「Only the b及 其各自的」核取方塊。

====
. 對於NFS檔案共用磁碟區、請指定主機或網路的IP位址、以存取檔案共用磁碟區。您可以為多個主機輸入以逗號分隔的值。
+
在新增主機IP位址時、會執行內部檢查、以將主機詳細資料與儲存VM配對、並建立該主機的匯出原則、或是在現有原則存在的情況下、重新使用該原則。如果有多個NFS共用是針對同一部主機所建立、則相同主機的可用匯出原則會針對所有檔案共用重複使用符合的規則。當您使用API來配置NFS共用時、可以使用指定個別原則規則或提供特定原則金鑰來重複使用原則的功能。

. 針對SMB共用區、指定哪些使用者或使用者群組可以存取SMB共用區、並指派所需的權限。針對每個使用者群組、在建立檔案共用期間會產生新的存取控制清單（ACL）。
. 按一下「 * 儲存 * 」。
+
工作負載會新增至儲存工作負載清單。


