---
permalink: storage-mgmt/task_add_clusters.html 
sidebar: sidebar 
keywords: add cluster 
summary: 您可以將叢集新增Active IQ Unified Manager 至支援功能、以便監控叢集。這包括取得叢集資訊（例如叢集的健全狀況、容量、效能和組態）的能力、以便找出並解決可能發生的任何問題。 
---
= 新增叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將叢集新增Active IQ Unified Manager 至支援功能、以便監控叢集。這包括取得叢集資訊（例如叢集的健全狀況、容量、效能和組態）的能力、以便找出並解決可能發生的任何問題。

*您需要的是什麼*

* 您必須具有應用程式管理員角色或儲存管理員角色。
* 您必須擁有叢集的主機名稱或叢集管理IP位址（IPV4或IPV6）。
+
使用主機名稱時、必須解析為叢集管理LIF的叢集管理IP位址。如果您使用節點管理LIF、則作業會失敗。

* 您必須擁有使用者名稱和密碼才能存取叢集。
+
此帳戶必須將「應用程式」存取權限設為_ontapi_、_ssh _和_http _的_admin_角色。

* 您必須知道使用HTTPS傳輸協定（通常為連接埠443）連線至叢集的連接埠號碼。
* 叢集必須執行ONTAP 的是版本不穩定的9.1軟體或更新版本。
* 您必須在Unified Manager伺服器上有足夠的空間。當超過90%的空間已用完時、您將無法將叢集新增至伺服器。
* 您擁有必要的憑證。需要兩種類型的憑證：
+
*伺服器憑證*：用於登錄。新增叢集需要有效的憑證。如果伺服器憑證過期、您應該重新產生該憑證、然後重新啟動Unified Manager、以便重新自動登錄服務。如需建立憑證的相關資訊、請參閱知識庫（KB）文章： https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_renew_an_SSL_certificate_in_ONTAP_9["如何在ONTAP 更新SSL憑證的過程中進行更新9"]

+
*用戶端憑證*：用於驗證。新增叢集需要有效的憑證。您無法將已過期憑證的叢集新增至Unified Manager、如果用戶端憑證已過期、則應在新增叢集之前重新產生叢集。不過、如果此憑證已新增且正由Unified Manager使用的叢集過期、則EMS訊息會繼續與過期的憑證搭配運作。您不需要重新產生用戶端憑證。



[NOTE]
====
您可以使用Unified Manager NAT IP位址、新增位於NAT/防火牆後方的叢集。任何連線的Workflow Automation或SnapProtect 非功能性系統也必須位於NAT/防火牆之後、SnapProtect 而非功能性API呼叫則必須使用NAT IP位址來識別叢集。

====
* 必須個別新增每個MetroCluster 採用此功能組態的叢集。
* Unified Manager的單一執行個體可支援特定數量的節點。如果您需要監控超出支援節點數的環境、則必須安裝Unified Manager的其他執行個體、以監控部分叢集。
* 只要您已在叢集上設定第二個叢集管理LIF、讓Unified Manager的每個執行個體都透過不同的LIF連線、您就可以使用兩個Unified Manager執行個體來監控單一叢集。


.步驟
. 在左導覽窗格中、按一下*儲存管理*>*叢集設定*。
. 在「叢集設定」頁面上、按一下*「新增*」。
. 在「新增叢集」對話方塊中、依需要指定值、然後按一下「*提交*」。
. 在「授權主機」對話方塊中、按一下「*檢視憑證*」以檢視叢集的憑證資訊。
. 按一下「*是*」。
+
Unified Manager只會在一開始新增叢集時檢查憑證。Unified Manager不會檢查每個API呼叫ONTAP 的認證資料以供參考。



在探索新叢集的所有物件之後、Unified Manager會開始收集前15天的歷史效能資料。這些統計資料是使用資料持續性收集功能來收集。此功能可在新增叢集之後、立即為叢集提供超過兩週的效能資訊。在資料持續性收集週期完成之後、系統會依預設每五分鐘收集一次即時叢集效能資料。

[NOTE]
====
由於收集15天的效能資料會佔用大量CPU資源、因此建議您將新增的叢集重新分段、以使資料持續性收集輪詢不會同時在太多叢集上執行。此外、如果您在資料持續性收集期間重新啟動Unified Manager、收集作業將會暫停、而且效能圖表中會出現遺漏時間範圍的落差。

====
[TIP]
====
如果您收到無法新增叢集的錯誤訊息、請檢查下列問題是否存在：

* 如果兩個系統上的時鐘未同步、且Unified Manager HTTPS憑證開始日期晚於叢集上的日期。您必須確保時鐘是使用NTP或類似服務來同步。
* 如果叢集已達到EMS通知目的地的最大數量、則無法新增Unified Manager位址。根據預設、叢集上只能定義20個EMS通知目的地。


====
*相關資訊*

link:../config/task_add_users.html["新增使用者"]

link:../health-checker/task_view_cluster_list_and_details.html["檢視叢集清單和詳細資料"]
