---
permalink: storage-mgmt/task_provision_luns.html 
sidebar: sidebar 
keywords: provision, luns 
summary: 您可以從「資源配置工作負載」頁面、在現有叢集和儲存虛擬機器（儲存VM）上建立支援CIFS/SMB和NFS傳輸協定的LUN。 
---
= 資源配置LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從「資源配置工作負載」頁面、在現有叢集和儲存虛擬機器（儲存VM）上建立支援CIFS/SMB和NFS傳輸協定的LUN。

*您需要的是什麼*

* 儲存VM必須有空間來配置LUN。
* iSCSI和FCP都必須在您建立LUN的儲存VM上啟用。
* 若要在工作負載上選取並指派效能服務層級（PSL）和儲存效率原則（SEP）、必須先建立原則、才能開始建立工作負載。


.步驟
. 在「*資源配置工作負載*」頁面上、新增您要建立的工作負載名稱、然後從「可用」清單中選取叢集。
+
根據您選取的叢集、*儲存VM*欄位會篩選該叢集的可用儲存VM。

. 從支援iSCSI和FCP服務的清單中選取儲存VM。
+
根據您的選擇、SAN選項會在「主機資訊」區段中啟用。

. 在「*儲存與最佳化*」區段中、指派儲存容量和PSL、以及選擇性指派工作負載的SEP。
+
SEP的規格會指派給LUN、而PSL的定義會在工作負載建立時套用至該工作負載。

. 如果您要在工作負載上強制執行指派的PSL、請選取*強制執行效能限制*核取方塊。
+
將PSL指派給工作負載、可確保建立工作負載的集合體能夠支援個別原則中定義的效能和容量目標。例如、如果指派工作負載為「極致效能」PSL、則要配置工作負載的集合體應該能夠支援「極致效能」原則的效能與容量目標、例如SSD儲存設備。

+
[NOTE]
====
除非選取此核取方塊、否則不會將PSL套用至工作負載、而且儀表板上的工作負載狀態會顯示為「未指派」。

====
. 選擇* SAN*選項。如果您看不到* SAN*選項已啟用、請確認您選取的儲存VM是否支援iSCSI和FCP。
. 選取主機作業系統。
. 指定主機對應、以控制啟動器對LUN的存取。您可以指派現有的啟動器群組（igroup）、或定義及對應新的igroup。
+
[NOTE]
====
如果您在配置LUN時建立新的igroup、則需要等到下一個探索週期（最多15分鐘）才能使用。因此、建議您使用可用igroup清單中現有的igroup。

====
+
如果您要建立新的igroup、請選取*建立新的啟動器群組*按鈕、然後輸入igroup的資訊。

. 按一下「 * 儲存 * 」。
+
LUN會新增至儲存工作負載清單。


