---
permalink: health-checker/concept_configure_destination_and_schedule_for_database_dump_backups.html 
sidebar: sidebar 
keywords: configure, destination, schedule, database dump, backups, snapshot copy, copies 
summary: 您可以設定Unified Manager資料庫傾印備份設定、以設定資料庫備份路徑、保留計數和備份排程。您可以啟用每日或每週排程備份。根據預設、排程備份會停用、但您應該設定備份排程。 
---
= 配置資料庫轉儲備份的目標和計劃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定Unified Manager資料庫傾印備份設定、以設定資料庫備份路徑、保留計數和備份排程。您可以啟用每日或每週排程備份。根據預設、排程備份會停用、但您應該設定備份排程。

.開始之前
* 您必須具有「操作員」、「應用程式管理員」或「儲存管理員」角色。
* 在您定義為備份路徑的位置、至少必須有150 GB的可用空間。
+
建議您使用Unified Manager主機系統外部的遠端位置。

* 在Linux系統上安裝Unified Manager並使用MySQL備份時、請確定備份目錄已設定下列權限和擁有權。
+
權限：0750、擁有者：Jboss：維護

* 在Windows系統上安裝Unified Manager並使用MySQL備份時、請確保只有系統管理員有權存取備份目錄。


第一次執行備份所需的時間比後續備份多、因為第一次備份是完整備份。完整備份可能超過1 GB、可能需要三到四小時。後續備份是遞增的、所需時間較短。

[NOTE]
====
* 如果您發現遞增備份檔案的數量對於配置用於備份的空間而言太大、您可以定期進行完整備份、以取代舊的備份及其遞增檔案。另一個選項是使用Snapshot複本進行備份。
* 在新增叢集的最初15天內所進行的備份、可能不夠準確、無法取得先前的效能資料。


====
.步驟
. 在左導覽窗格中、按一下*一般*>*資料庫備份*。
. 在「*資料庫備份*」頁面中、按一下「*備份設定*」。
. 設定備份路徑、保留計數和排程的適當值。
+
保留計數的預設值為10；您可以使用0建立無限備份。

. 選取*排程每日*或*排程每週*按鈕、然後指定排程詳細資料。
. 按一下「 * 套用 * 」。


資料庫傾印備份檔案是根據排程建立。您可以在「資料庫備份」頁面中看到可用的備份檔案。
