---
permalink: health-checker/concept_common_unified_manager_administrative_workflows_and_tasks.html 
sidebar: sidebar 
keywords: Common, unified, manager, health, workflows, tasks 
summary: 與Unified Manager相關的一些常見管理工作流程和工作包括：選取要監控的儲存叢集；診斷對資料可用度、容量和保護造成不良影響的情況；還原遺失的資料；設定和管理磁碟區；以及將診斷資料綁定並傳送給技術支援（必要時）。 
---
= 通用的Unified Manager健全狀況工作流程與工作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
與Unified Manager相關的一些常見管理工作流程和工作包括：選取要監控的儲存叢集；診斷對資料可用度、容量和保護造成不良影響的情況；還原遺失的資料；設定和管理磁碟區；以及將診斷資料綁定並傳送給技術支援（必要時）。

Unified Manager可讓儲存管理員檢視儀表板、評估受管理儲存叢集的整體容量、可用度及保護健全狀況、然後快速識別、找出、診斷及指派以解決可能發生的任何特定問題。

與叢集、儲存虛擬機器（SVM）、磁碟區或FlexGroup 物件的儲存容量或資料可用度有關的最重要問題、會顯示在儀表板頁面的系統健全狀況圖和事件中。當發現關鍵問題時、本頁會提供連結、以支援適當的疑難排解工作流程。

Unified Manager也可納入包含相關管理工具（例如OnCommand Workflow Automation 、VMware®VMware®VMware®）的工作流程、以支援儲存資源的直接組態。

本文件說明與下列管理工作相關的一般工作流程：

* 診斷及管理可用度問題
+
如果硬體故障或儲存資源組態問題導致儀表板頁面顯示資料可用度事件、儲存管理員可以依照內嵌的連結來檢視受影響儲存資源的連線資訊、檢視疑難排解建議、並將問題解決指派給其他管理員。

* 設定及監控效能事件
+
管理員可以監控及管理所監控之儲存系統資源的效能。請參閱 link:../performance-checker/concept_introduction_to_unified_manager_performance_monitoring.html["《叢集效能管理工作流程指南》Active IQ Unified Manager"] 以取得更多資訊。

* 診斷及管理Volume容量問題
+
如果「儀表板」頁面顯示Volume儲存容量問題、儲存管理員可以依照內嵌連結來檢視與受影響磁碟區儲存容量相關的目前和歷史趨勢、檢視疑難排解建議、並將問題解決指派給其他管理員。

* 設定、監控及診斷保護關係問題
+
建立及設定保護關係之後、儲存管理員可以檢視與保護關係、保護關係的目前狀態、受影響關係的目前與歷史保護工作成功資訊、以及疑難排解建議等相關的潛在問題。請參閱 link:../data-protection/concept_create_and_monitor_protection_relationships.html["《保護指南》Active IQ Unified Manager"] 以取得更多資訊。

* 建立備份檔案並從備份檔案還原資料。
* 將儲存物件與附註建立關聯
+
儲存物件與附註建立關聯後、儲存管理員即可篩選及檢視與儲存物件相關的事件、讓儲存管理員能夠排定優先順序、並解決與事件相關的問題。

* 使用REST API檢視Unified Manager擷取的健全狀況、容量和效能資訊、協助管理叢集。請參閱 link:../api-automation/concept_get_started_with_um_apis.html["《NetApp API開發人員指南》Active IQ Unified Manager"] 以取得更多資訊。
* 傳送支援服務包給技術支援人員
+
儲存管理員可以使用維護主控台擷取支援套件、並將其傳送給技術支援部門。當問題需要比AutoSupport 消息所提供的更詳細的診斷和疑難排解時、必須將支援服務組合寄送給技術支援部門。


