---
permalink: health-checker/reference_cluster_compliance_categories.html 
sidebar: sidebar 
keywords: cluster compliance, categories 
summary: 此表說明Unified Manager評估的叢集安全性法規遵循參數、NetApp建議、以及此參數是否會影響要抱怨或不抱怨的叢集整體判斷。 
---
= 叢集規範類別
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
此表說明Unified Manager評估的叢集安全性法規遵循參數、NetApp建議、以及此參數是否會影響要抱怨或不抱怨的叢集整體判斷。

在叢集上使用不相容的SVM、將會影響叢集的法規遵循值。因此在某些情況下、您可能需要先修正SVM的安全性問題、然後才能將叢集安全性視為相容。

請注意、並非所有安裝都會顯示下列每個參數。例如、如果您沒有對等的叢集、或是在AutoSupport 叢集上停用了某些功能、AutoSupport 您就不會在UI頁面中看到叢集對等或是物件式HTTPS傳輸項目。

[cols="4*"]
|===
| 參數 | 說明 | 建議 | 影響叢集規範 


 a| 
全球FIPS
 a| 
指出是否已啟用或停用全域FIPS（聯邦資訊處理標準）140-2相容模式。啟用FIPS時、會停用TLSv1和SSLv3、而且只允許使用TLSv1.1和TLSv1.2。
 a| 
已啟用
 a| 
是的



 a| 
遠端登入
 a| 
表示是否已啟用或停用對系統的遠端登入存取。NetApp建議使用安全Shell（SSH）進行安全遠端存取。
 a| 
已停用
 a| 
是的



 a| 
不安全的SSH設定
 a| 
指出SSH是否使用不安全的密碼、例如以* CBC開頭的密碼。
 a| 
否
 a| 
是的



 a| 
登入橫幅
 a| 
表示存取系統的使用者是否已啟用或停用登入橫幅。
 a| 
已啟用
 a| 
是的



 a| 
叢集對等
 a| 
指出對等叢集之間的通訊是否已加密或未加密。必須在來源叢集和目的地叢集上設定加密、此參數才視為符合法規。
 a| 
加密
 a| 
是的



 a| 
網路時間傳輸協定
 a| 
指出叢集是否有一個或多個已設定的NTP伺服器。為了提供備援和最佳服務、NetApp建議您將至少三部NTP伺服器與叢集建立關聯。
 a| 
已設定
 a| 
是的



 a| 
OCSP
 a| 
從 9.14.1 開始， Active IQ Unified Manager 會在儲存虛擬機器（ SVM ，前身為 vserver ）層級提供線上憑證狀態傳輸協定（ OCSP ）狀態資訊。這表示 OCSP 驗證會套用至所有與 SVM 建立的 SSL/TLS 連線，並確保這些連線所使用的憑證完整性和有效性。
 a| 
已啟用
 a| 
否



 a| 
遠端稽核記錄
 a| 
表示記錄轉送（Syslog）是否已加密或未加密。
 a| 
加密
 a| 
是的



 a| 
支援HTTPS傳輸AutoSupport
 a| 
表示HTTPS是否作為預設傳輸傳輸傳輸傳輸傳輸傳輸傳輸傳輸協定、以傳送AutoSupport 不支援的消息給NetApp。
 a| 
已啟用
 a| 
是的



 a| 
預設管理使用者
 a| 
指出預設的管理使用者（內建）是啟用還是停用。NetApp建議鎖定（停用）任何不需要的內建帳戶。
 a| 
已停用
 a| 
是的



 a| 
SAML使用者
 a| 
表示是否已設定SAML。SAML可讓您將多因素驗證（MFA）設定為單一登入的登入方法。
 a| 
否
 a| 
否



 a| 
Active Directory使用者
 a| 
指出是否已設定Active Directory。Active Directory和LDAP是存取叢集的使用者偏好的驗證機制。
 a| 
否
 a| 
否



 a| 
LDAP使用者
 a| 
表示是否已設定LDAP。Active Directory和LDAP是管理叢集的使用者優先使用的驗證機制、而不使用本機使用者。
 a| 
否
 a| 
否



 a| 
憑證使用者
 a| 
指出是否已將憑證使用者設定為登入叢集。
 a| 
否
 a| 
否



 a| 
本機使用者
 a| 
指出本機使用者是否已設定登入叢集。
 a| 
否
 a| 
否



 a| 
遠端Shell
 a| 
表示是否已啟用RSH。基於安全考量、應停用RSH。建議使用安全Shell（SSH）進行安全遠端存取。
 a| 
已停用
 a| 
是的



 a| 
使用中的MD5
 a| 
表示ONTAP 不安全的使用者帳戶是否使用不安全的MD5雜湊功能。建議使用將使用者帳戶的密碼編譯雜湊功能（如SHA-512）移轉至更安全的密碼編譯雜湊功能。
 a| 
否
 a| 
是的



 a| 
憑證發卡行類型
 a| 
指出所使用的數位憑證類型。
 a| 
CA簽署
 a| 
否

|===