---
permalink: health-checker/task_perform_diagnotstic_actions_for_volume_offline_conditions.html 
sidebar: sidebar 
keywords: perform, diagnostic actions, volume, offline, conditions 
summary: 在瀏覽至報告為離線的Volume / Health詳細資料頁面之後、您可以搜尋其他有助於診斷Volume離線狀況的資訊。 
---
= 對磁碟區離線情況執行診斷操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在瀏覽至報告為離線的Volume / Health詳細資料頁面之後、您可以搜尋其他有助於診斷Volume離線狀況的資訊。

.開始之前
您必須具有「操作員」、「應用程式管理員」或「儲存管理員」角色。

如果回報為離線的磁碟區並非刻意離線、則該磁碟區可能會因為數種原因而離線。

從離線磁碟區的Volume / Health詳細資料頁面開始、您可以瀏覽至其他頁面和窗格、以確認或消除可能的原因：

* 按一下* Volume / Health*詳細資料頁面連結、以判斷磁碟區是否離線、因為其主機節點當機、而且儲存設備容錯移轉至HA配對合作夥伴也失敗。
+
請參閱 link:task_determine_if_volume_offline_condition_is_by_down_cluster_node.html["判斷磁碟區離線狀況是否是由當機節點所造成"]。

* 按一下* Volume / Health*詳細資料頁面連結、以判斷該磁碟區是否離線、且其主機儲存虛擬機器（SVM）是否因為裝載該SVM根磁碟區的節點關閉而停止。
+
請參閱 link:task_determine_if_volume_is_offline_and_its_svm_is_stopped.html["判斷磁碟區是否離線、以及SVM是否因為節點當機而停止"]。

* 按一下* Volume / Health*詳細資料頁面連結、以判斷磁碟區是否因為主機Aggregate中的磁碟毀損而離線。
+
請參閱 link:task_determine_if_volume_is_offline_because_of_broken_disks.html["判斷磁碟區是否因為集合體中的磁碟毀損而離線"]。



*相關資訊*

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager使用者角色與功能"]
