---
permalink: health-checker/task_restore_snapshot_backup.html 
sidebar: sidebar 
keywords: restore, linux, snapshot, backup, windows 
summary: 如果發生資料遺失或資料毀損、您可以將Unified Manager還原至先前的穩定狀態、並將資料遺失降至最低。您可以使用Unified Manager維護主控台、將Unified Manager Snapshot資料庫還原至本機或遠端作業系統。 
---
= 還原適用於Linux和Windows的Snapshot備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果發生資料遺失或資料毀損、您可以將Unified Manager還原至先前的穩定狀態、並將資料遺失降至最低。您可以使用Unified Manager維護主控台、將Unified Manager Snapshot資料庫還原至本機或遠端作業系統。

*您需要的是什麼*

* 您必須擁有Linux主機的root使用者認證、以及安裝Unified Manager的Windows主機機器的管理權限。
* 您必須擁有授權使用者ID和密碼、才能登入Unified Manager伺服器的維護主控台。


還原功能是針對平台和版本而設計。您只能在相同版本的Unified Manager上還原Unified Manager備份。

.步驟
. 連線至Unified Manager系統的IP位址或完整網域名稱。
+
|===


 a| 
* Linux *



 a| 
安全Shell



 a| 
* Windows *



 a| 
Power Shell

|===
. 使用root使用者認證登入系統。
. 輸入命令「maintainess_Console」、然後按Enter。
. 在維護主控台*主功能表*中、輸入*備份還原*選項的編號。
. 輸入*使用NetApp Snapshot備份與還原*的號碼。
+
如果您要在新伺服器上執行還原、安裝Unified Manager之後、安裝完成後、不會啟動UI或設定任何叢集、使用者或驗證設定。輸入* Configure NetApp Snapshot Backup（配置NetApp Snapshot備份）*的編號、並依照在原始系統上設定的方式來設定Snapshot備份設定。

. 輸入*使用NetApp Snapshot還原*的號碼。
. 選取您要還原的Snapshot備份檔案、然後按* Enter *。
. 還原程序完成後、請登入Unified Manager使用者介面。


還原備份之後、如果Workflow Automation伺服器無法運作、請執行下列步驟：

. 在Workflow Automation伺服器上、將Unified Manager伺服器的IP位址變更為指向最新機器。
. 在Unified Manager伺服器上、如果擷取在步驟1中失敗、請重設資料庫密碼。

