---
permalink: health-checker/task_view_node_list_and_details.html 
sidebar: sidebar 
keywords: view, node list, details 
summary: 您可以使用健全狀況：所有節點檢視來檢視叢集中的節點清單。您可以使用「叢集/健全狀況」詳細資料頁面來檢視受監控叢集一部分的節點詳細資訊。 
---
= 檢視節點清單和詳細資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用健全狀況：所有節點檢視來檢視叢集中的節點清單。您可以使用「叢集/健全狀況」詳細資料頁面來檢視受監控叢集一部分的節點詳細資訊。

.開始之前
您必須具有「操作員」、「應用程式管理員」或「儲存管理員」角色。

您可以檢視詳細資料、例如節點狀態、包含節點的叢集、Aggregate容量詳細資料（已使用和總計）、以及原始容量詳細資料（可用、備援和總計）。您也可以取得HA配對、磁碟櫃和連接埠的相關資訊。

.步驟
. 在左側導覽窗格中、按一下「*儲存設備*>*節點*」。
. 在「*健全狀況：所有節點*」檢視中、按一下您要檢視其詳細資料的節點。
+
所選節點的詳細資訊會顯示在叢集/健全狀況詳細資料頁面。左窗格會顯示HA配對清單。依預設、HA詳細資料會開啟、顯示HA狀態詳細資料及與所選HA配對相關的事件。

. 若要檢視有關節點的其他詳細資料、請執行適當的動作：
+
[cols="2*"]
|===
| 若要檢視... | 按一下... 


 a| 
磁碟櫃的詳細資料
 a| 
*磁碟櫃*。



 a| 
連接埠相關資訊
 a| 
*連接埠*。

|===


如需詳細資訊、請參閱：

* link:../performance-checker/performance-view-all.html#performance-all-nodes-view["效能：All Node檢視"]
* link:../performance-checker/concept_view_node_and_aggregate_available_iops_values.html["檢視節點和Aggregate可用IOPS值"]
* link:../performance-checker/concept_view_node_and_aggregate_performance_capacity_used_values.html["檢視節點和Aggregate效能使用容量值"]

