---
permalink: health-checker/task_determine_if_volume_is_offline_because_of_broken_disks.html 
sidebar: sidebar 
keywords: determine, volume, offline, broken disks, aggregate 
summary: 您可以使用Unified Manager Web UI來確認或消除磁碟區離線的可能性、因為RAID磁碟問題已使其主機Aggregate離線。 
---
= 確定磁碟區是否因聚合中的磁碟損壞而處於離線狀態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Unified Manager Web UI來確認或消除磁碟區離線的可能性、因為RAID磁碟問題已使其主機Aggregate離線。

.開始之前
您必須具有「操作員」、「應用程式管理員」或「儲存管理員」角色。

若要判斷磁碟區離線狀況是否是由使託管Aggregate離線的RAID磁碟問題所造成、請執行下列動作：

.步驟
. 在「* Volume / Health*詳細資料」頁面的「* Related Devices*」（*相關裝置*）窗格中、找到並按一下Aggregate下方顯示的超文字連結。
+
Aggregate / Health詳細資料頁面會顯示主機Aggregate的線上或離線狀態。如果Aggregate狀態為「線上」、則RAID磁碟問題並不是磁碟區離線的原因。

. 如果Aggregate狀態為離線、請按一下「*磁碟資訊*」、然後在「*磁碟資訊*」索引標籤的「*事件*」清單中尋找毀損的磁碟事件。
. 若要進一步識別毀損的磁碟、請按一下「*相關裝置*」窗格中「節點」下方顯示的超文字連結。
+
隨即顯示叢集/健全狀況詳細資料頁面。

. 按一下「*磁碟*」、然後在「*篩選器*」窗格中選取「*毀損*」、以列出所有處於中斷狀態的磁碟。
+
如果處於中斷狀態的磁碟導致主機Aggregate的離線狀態、則Aggregate的名稱會顯示在「Impacted Aggregate（受影響的Aggregate）」欄中。



在確認磁碟區離線狀況是由毀損的RAID磁碟及其後的離線主機Aggregate所造成之後、請聯絡適當的管理員或操作員、手動更換毀損的磁碟、並將Aggregate重新連線。
