---
permalink: health-checker/task_restore_mysql_database_backup_on_windows.html 
sidebar: sidebar 
keywords: restore, windows, mysql, database, backup 
summary: 在資料遺失或資料毀損的情況下、您可以使用還原功能、將Unified Manager還原至先前的穩定狀態、同時將遺失降至最低。您可以使用Unified Manager維護主控台、將Unified Manager MySQL資料庫還原至本機Windows系統或遠端Windows系統。 
---
= 在Windows上還原MySQL資料庫備份
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在資料遺失或資料毀損的情況下、您可以使用還原功能、將Unified Manager還原至先前的穩定狀態、同時將遺失降至最低。您可以使用Unified Manager維護主控台、將Unified Manager MySQL資料庫還原至本機Windows系統或遠端Windows系統。

*您需要的是什麼*

* 您必須擁有Windows系統管理員權限。
* 您必須將Unified Manager備份檔案和資料庫儲存庫目錄的內容複製到要執行還原作業的系統。
+
建議您將備份檔案複製到預設目錄「\ProgramData\NetApp\OnCommandAppData\ocum\Backup」。必須將資料庫儲存庫檔案複製到「\backup」目錄下的「\database_dump _repo」子目錄。

* 備份檔案必須為「.7z」類型。


還原功能是針對平台和版本而設計。您只能在相同版本的Unified Manager上還原Unified Manager MySQL備份、而且只能在Windows平台上還原Windows備份。

[TIP]
====
如果資料夾名稱包含空格、您必須在雙引號中包含備份檔案的絕對路徑或相對路徑。

====
.步驟
. 如果您要在新伺服器上執行還原、安裝Unified Manager之後、安裝完成後、不會啟動UI或設定任何叢集、使用者或驗證設定。備份檔案會在還原程序期間填入此資訊。
. 以系統管理員認證登入Unified Manager系統。
. 以Windows系統管理員身分啟動PowerShell。
. 輸入命令「maintainess_Console」、然後按Enter。
. 在維護主控台*主功能表*中、輸入*備份還原*選項的編號。
. 輸入*還原MySQL備份*的編號。
. 出現提示時、請輸入備份檔案的絕對路徑。
+
[listing]
----
Bundle to restore from: \ProgramData\NetApp\OnCommandAppData\ocum\backup\UM_9.8.N151118.2300_backup_windows_02-20-2020-02-51.7z
----
+
還原作業完成後、您可以登入Unified Manager。



還原備份之後、如果OnCommand Workflow Automation 無法使用此伺服器、請執行下列步驟：

. 在Workflow Automation伺服器上、將Unified Manager伺服器的IP位址變更為指向最新機器。
. 在Unified Manager伺服器上、如果擷取在步驟1中失敗、請重設資料庫密碼。

