---
permalink: health-checker/task_edit_individual_volume_health_threshold_settings.html 
sidebar: sidebar 
keywords: edit, individual, volume, health, threshold, settings 
summary: 您可以編輯一個或多個磁碟區的磁碟區容量、成長、配額和空間保留的健全狀況臨界值設定。超過臨界值時、系統會產生警示並通知您。這些通知可協助您根據所產生的事件採取預防措施。 
---
= 編輯單一卷健康閾值設置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以編輯一個或多個磁碟區的磁碟區容量、成長、配額和空間保留的健全狀況臨界值設定。超過臨界值時、系統會產生警示並通知您。這些通知可協助您根據所產生的事件採取預防措施。

.開始之前
您必須具有應用程式管理員或儲存管理員角色。

根據臨界值的變更、會在下一個監控週期產生或淘汰事件。

請注意、在磁碟區上啟用「自動擴充」時、容量臨界值會根據自動擴充所設定的最大磁碟區大小而非原始磁碟區大小而被視為違反。

[NOTE]
====
1000個Snapshot複本的預設值僅適用於FlexVol 當版本為9.4或更新版本時的版本、ONTAP 而當版本為9.8或更新版本時、則適用於FlexGroup 不含更新ONTAP 版本的版本。對於安裝ONTAP 舊版的更新版的叢集、每個磁碟區最多可有250個Snapshot複本。對於這些舊版、Unified Manager會將此數字1000（以及介於1000和250之間的任何數字）解譯為250；這表示當Snapshot複本數量達到250個時、您將會繼續收到事件。如果您想要將這些舊版的此臨界值設為小於250、您必須在「Health：All Volumes（健全狀況：所有磁碟區）」檢視或「Volume / Health（Volume /健全狀況）」詳細資料頁面中、將臨界值設為250或更低。

====
.步驟
. 在左導覽窗格中、按一下「*儲存設備*>*磁碟區*」。
. 在「*健全狀況：所有磁碟區*」檢視中、選取一或多個磁碟區、然後按一下「*編輯臨界值*」。
. 在*編輯Volume臨界值*對話方塊中、選取適當的核取方塊、然後修改設定、以編輯下列其中一項的臨界值設定：容量、Snapshot複本、qtree配額、成長或inode。
. 按一下「 * 儲存 * 」。


*相關資訊*

link:../config/task_add_users.html["新增使用者"]
