---
permalink: health-checker/task_generate_and_upload_support_bundle.html 
sidebar: sidebar 
keywords: generate, upload, support bundle 
summary: 您可以產生包含診斷資訊的支援服務組合、以便將其傳送至技術支援部門以取得疑難排解說明。您也可以從維護主控台將支援服務組合上傳至NetApp。 
---
= 產生及上傳支援服務組合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以產生包含診斷資訊的支援服務組合、以便將其傳送至技術支援部門以取得疑難排解說明。

從Unified Manager 9.8開始、如果Unified Manager伺服器已連線至網際網路、您也可以從維護主控台將支援服務組合上傳至NetApp。

*您需要的是什麼*

您必須以維護使用者的身分存取維護主控台。

由於某些類型的支援資料可能會使用大量的叢集資源、或需要很長時間才能完成、因此當您選取完整的支援服務組合時、可以指定要納入或排除的資料類型、以減少支援服務組合的大小。您也可以選擇建立一個輕量級支援套件、其中只包含30天的記錄和組態資料庫記錄、不包括效能資料、擷取記錄檔和伺服器堆疊傾印。

Unified Manager僅儲存兩個最近產生的支援組合。舊版支援服務組合將從系統中刪除。

.步驟
. 在維護主控台*主功能表*中、選取*支援/診斷*。
. 根據您想要在支援服務組合中提供的詳細資料層級、選取*產生輕度支援服務組合*或*產生支援服務組合*。
. 如果您選擇完整支援服務組合、請選取或取消選取下列資料類型、以納入或排除支援服務組合：
+
** *資料庫傾印*
+
MySQL Server資料庫的傾印。

** *堆傾印*
+
Unified Manager主要伺服器程序狀態的快照。此選項預設為停用、只有在客戶支援要求時才應選取。

** *擷取錄影*
+
記錄Unified Manager與受監控叢集之間的所有通訊。



+
[NOTE]
====
如果您取消選取所有資料類型、仍會使用其他Unified Manager資料產生支援服務組合。

====
. 輸入「g」、然後按Enter鍵以產生支援服務組合。
+
由於產生支援服務包是一項記憶體密集作業、因此系統會提示您確認是否確定要在此時產生支援服務組合。

. 輸入「y」、然後按Enter鍵以產生支援服務組合。
+
如果您目前不想產生支援服務組合、請輸入「n」、然後按Enter。

. 如果您在完整支援套裝組合中加入資料庫傾印檔案、系統會提示您指定要納入效能統計資料的時間段。包括效能統計資料可能需要大量時間和空間、因此您也可以在不包含效能統計資料的情況下傾印資料庫：
+
.. 以「月份-月份-月份-月份-月份-日期」格式輸入開始日期。
+
例如、在2021年1月1日輸入「2021101」。如果您不想包含效能統計資料、請輸入「n」。

.. 輸入統計資料的天數、從上午12點開始算起在指定的開始日期。
+
您可以輸入1到10之間的數字。



+
如果您要納入效能統計資料、系統會顯示收集效能統計資料的期間。

. 建立支援服務組合之後、系統會提示您是否要將其上傳至NetApp。輸入「y」、然後按Enter。
+
系統會提示您輸入支援案例編號。

. 如果您已經有個案編號、請輸入編號、然後按Enter。否則請按Enter。
+
支援服務組合已上傳至NetApp。



如果Unified Manager伺服器未連線至網際網路、或由於任何其他原因而無法上傳支援服務組合、則您可以擷取並手動傳送。您可以使用SFTP用戶端或UNIX或Linux CLI命令來擷取。在Windows安裝上、您可以使用遠端桌面（RDP）來擷取支援服務組合。

產生的支援服務組合位於VMware系統的/support目錄、Linux系統的/opp/NetApp/data/support/、以及Windows系統上的ProgramData \NetApp\OnCommandAppData\ocum\supports。

*相關資訊*

link:../config/reference_unified_manager_roles_and_capabilities.html["Unified Manager使用者角色與功能"]
