---
permalink: install-vapp/reference_vmware_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: vmware, software, installation, requirements 
summary: 安裝Unified Manager的VMware vSphere系統需要特定版本的作業系統和支援軟體。 
---
= VMware軟體與安裝需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝Unified Manager的VMware vSphere系統需要特定版本的作業系統和支援軟體。



== 作業系統軟體

支援下列版本的VMware ESXi：

* ESXi 6.5、6.7和7.2.x


[NOTE]
====
VMware vSphere系統上的Unified Manager OVA可在內部執行Debian OS 11（鬥牛）。如需受支援ESXi伺服器版本所支援之虛擬機器硬體版本的相關資訊、請參閱VMware文件。

====
支援下列vSphere版本：

* VMware vCenter Server 6.5、6.7和7.2.x


請參閱互通性對照表、以取得支援的ESXi版本完整且最新的清單。

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"]

VMware ESXi伺服器時間應與NTP伺服器時間相同、虛擬應用裝置才能正常運作。將VMware ESXi伺服器時間與NTP伺服器時間同步、可避免時間故障。



== 安裝需求

支援適用於Unified Manager虛擬應用裝置的VMware High Availability。

如果您在執行ONTAP VMware軟體的儲存系統上部署NFS資料存放區、請使用適用於VMware VAAI的NetApp NFS外掛程式來使用完整資源配置。

如果由於資源不足而無法使用啟用高可用度的環境進行部署、您可能需要停用VM重新啟動優先順序、並保持主機隔離回應開啟、以修改叢集功能虛擬機器選項。


NOTE: 在安裝或升級Unified Manager時、所需的協力廠商軟體和安全性修補程式會自動安裝或升級至VMware vSphere系統。由於Unified Manager的安裝與升級程序控制這些元件、因此您不應嘗試獨立安裝或升級任何協力廠商元件。
