---
permalink: install-windows/task_change_jboss_password_on_windows.html 
sidebar: sidebar 
keywords: change, jboss, password 
summary: 您可以重設安裝期間所設定的執行個體專屬的jboss密碼。您可以選擇性地重設密碼、以防站台需要此安全功能來覆寫Unified Manager安裝設定。此作業也會變更jboss存取MySQL所用的密碼。 
---
= 變更jboss密碼
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以重設安裝期間所設定的執行個體專屬的jboss密碼。您可以選擇性地重設密碼、以防站台需要此安全功能來覆寫Unified Manager安裝設定。此作業也會變更jboss存取MySQL所用的密碼。

*您需要的是什麼*

* 您應該擁有安裝Unified Manager的系統的Windows管理員權限。
* 您應該擁有MySQL root使用者的密碼。
* 您應該能夠存取目錄中NetApp提供的「密碼.bat」指令碼
+
Program Files\NetApp\Essentials \Bin。



.步驟
. 以管理使用者身分登入Unified Manager主機。
. 使用Windows服務主控台停止下列Unified Manager服務：
+
** NetApp Active IQ 收購服務（Ocia-au）
** NetApp Active IQ 產品資料管理伺服器服務（Oncommandsvc）


. 啟動「密碼.bat」指令碼、開始密碼變更程序：
+
「C：\Program Files\NetApp\Cements\BIN> password.bat resetterJBossPassword」

. 出現提示時、請輸入MySQL root使用者密碼。
. 出現提示時、請輸入新的jboss使用者密碼、然後再次輸入以供確認。
+
請注意、密碼應介於8到16個字元之間、且必須包含至少一個數字、大小寫和大小寫字元、以及至少其中一個特殊字元：

+
「+！@%」*-_+=[]:<>.?/~+

. 指令碼完成後、請使用Windows服務主控台啟動Unified Manager服務：
+
** NetApp Active IQ 產品資料管理伺服器服務（Oncommandsvc）
** NetApp Active IQ 收購服務（Ocia-au）


. 所有服務啟動後、您就可以登入Unified Manager UI。

