---
permalink: config/concept_security_dashboard.html 
sidebar: sidebar 
keywords: security compliance settings, security feature settings, ONTAP hardening guide, AutoSupport settings, authentication settings 
summary: 您可以在Unified Manager上啟用或停用法規遵循監控的安全參數。 
---
= 啟用和停用合規性安全性設置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用「功能設定」頁面的「*安全性儀表板*」面板上的*自訂*按鈕、即可在Unified Manager上啟用或停用法規遵循監控的安全參數。

此頁面啟用或停用的設定、會管理Unified Manager上叢集和儲存VM的整體法規遵循狀態。根據所選內容、對應的欄位可在「叢集」清單頁面的「*安全性：所有叢集*」檢視和「儲存VM」目錄頁的「*安全性：所有儲存VM*」檢視中看到。

[NOTE]
====
只有具備系統管理員角色的使用者才能編輯這些設定。

====
根據中定義的建議、評估您的叢集、儲存VM和Volume的安全性條件ONTAP link:https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf["《NetApp ONTAP 安全強化指南》9"]。儀表板和「安全性」頁面上的「安全性」面板會顯示叢集、儲存VM和磁碟區的預設安全性法規遵循狀態。也會針對發生安全性違規的叢集和儲存VM、產生安全性事件並啟用管理動作。



== 自訂安全設定

若要根據ONTAP 您的需求自訂法規遵循監控的設定、請依照下列步驟操作：

.步驟
. 按一下*一般>功能設定>安全性儀表板>自訂*。「*自訂安全性儀表板設定*」快顯視窗隨即出現。
+
[NOTE]
====
您啟用或停用的安全性法規遵循參數、會直接影響叢集和儲存VM畫面上的預設安全性檢視、報告和排程報告。如果您在修改安全性參數之前、已從這些畫面上傳Excel報告、則下載的Excel報告可能有問題。

====
. 若要啟用或停用ONTAP 您的還原叢集的自訂設定、請在*叢集*下選取所需的一般設定。如需自訂叢集規範選項的相關資訊、請參閱 link:../health-checker/reference_cluster_compliance_categories.html["叢集規範類別"]。
. 若要啟用或停用儲存VM的自訂設定、請在* Storage VM*下選取所需的一般設定。如需自訂儲存VM法規遵循選項的相關資訊、請參閱 link:../health-checker/reference_svm_compliance_categories.html["儲存VM法規遵循類別"]。




== 自訂 AutoSupport 和身份驗證設置

在* AutoSupport 《*》「設定*」區段中、您可以指定是否要使用HTTPS傳輸來傳送AutoSupport 來自該區域的訊息ONTAP 。

從*驗證設定*區段、您可以針對預設ONTAP 的管理員使用者、啟用Unified Manager警示。

'''