---
permalink: config/concept_audit_logging.html 
sidebar: sidebar 
keywords: audit, logging 
summary: 您可以使用稽核日誌來偵測稽核日誌是否已洩漏。使用者執行的所有活動都會受到監控、並記錄在稽核記錄中。稽核是針對Active IQ Unified Manager 所有使用者介面和公開揭露的API功能執行、如所示。 
---
= 稽核記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用稽核日誌來偵測稽核日誌是否已洩漏。使用者執行的所有活動都會受到監控、並記錄在稽核記錄中。稽核是針對Active IQ Unified Manager 所有使用者介面及公開API功能執行的、

您可以使用*稽核記錄：檔案檢視*來檢視Active IQ Unified Manager 及存取您的整個過程中的所有稽核記錄檔。稽核記錄：檔案檢視中的檔案會根據建立日期列出。此檢視會顯示從安裝或升級到系統中現有的所有稽核記錄的資訊。每當您在Unified Manager中執行動作時、資訊都會更新、並可在記錄中使用。每個記錄檔的狀態都是使用「檔案完整性狀態」屬性擷取、該屬性會主動受到監控、以偵測記錄檔的竄改或刪除。稽核日誌可在系統中使用時、具有下列其中一種狀態：

[cols="2*"]
|===
| 州/省 | 說明 


 a| 
使用中
 a| 
記錄目前所在的檔案。



 a| 
正常
 a| 
非作用中、已壓縮並儲存在系統中的檔案。



 a| 
遭竄改
 a| 
已遭手動編輯檔案之使用者破壞的檔案。



 a| 
手冊刪除
 a| 
已由授權使用者刪除的檔案。



 a| 
指標移轉刪除
 a| 
因為根據循環組態原則進行復原而刪除的檔案。



 a| 
Unexpected刪除
 a| 
因為不明原因而刪除的檔案。

|===
「稽核記錄」頁面包含下列命令按鈕：

* 設定
* 刪除
* 下載


「*刪除*」按鈕可讓您刪除「稽核記錄」檢視中所列的任何稽核記錄。您可以刪除稽核記錄、並選擇性地提供刪除檔案的理由、以便日後判斷有效刪除。原因欄會列出原因、以及執行刪除作業的使用者名稱。

[NOTE]
====
刪除記錄檔會導致從系統刪除檔案、但不會刪除資料庫表格中的項目。

====
您可以Active IQ Unified Manager 使用「稽核記錄」區段中的「*下載*」按鈕、從更新下載稽核記錄檔、然後匯出稽核記錄檔。標示為「正常」或「竄改」的檔案會以壓縮的「.gzip」格式下載。

稽核記錄檔會定期歸檔、並儲存至資料庫以供參考。在歸檔之前、稽核記錄會經過數位簽署、以維持安全性和完整性。

當產生完整AutoSupport 的支援套件組合時、支援套件會同時包含已歸檔和作用中的稽核記錄檔。但是當產生輕度支援套件時、它只會包含作用中的稽核記錄。不包含歸檔的稽核記錄。
