---
permalink: config/concept_policy_based_storage_management.html 
sidebar: sidebar 
keywords: slo, storage efficiency policy, storage workloads 
summary: 原則型儲存管理選項可根據服務層級目標（SLO）進行儲存管理。此選項預設為啟用。 
---
= 實現原則型儲存管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
*原則型儲存管理*選項可根據服務層級目標（SLO）進行儲存管理。此選項預設為啟用。

啟用此功能時、您可以在ONTAP 新增Active IQ Unified Manager 至您的物件執行個體的物件叢集上配置儲存工作負載、並根據指派的效能服務層級和儲存效率原則來管理這些工作負載。

您可以從*一般*>*功能設定*>*原則型儲存管理*選擇啟動或停用此功能。啟動此功能時、下列頁面可供操作及監控：

* 資源配置（儲存工作負載資源配置）
* *原則*>*效能服務層級*
* *原則*>*儲存效率*
* 「叢集設定」頁面上的「依效能服務層級管理的工作負載」欄
* 「*儀表板*」上的「工作負載效能」面板


您可以使用畫面來建立效能服務層級和儲存效率原則、以及配置儲存工作負載。您也可以監控符合指派之效能服務層級的儲存工作負載、以及不符合的工作負載。「工作負載效能與工作負載IOPS」面板也可讓您根據資料中心上所配置的儲存工作負載、評估整個資料中心叢集的總容量、可用容量及已使用容量與效能（IOPS）。

啟動此功能之後、您可以執行Unified Manager REST API、從*功能表列*>*說明按鈕*>* API Documentation *>*儲存設備供應商*類別執行部分功能。或者、您也可以輸入主機名稱或IP位址和URL、以+https://<hostname>/docs/api/+格式存取REST API頁面

如需API的詳細資訊、請參閱_ Active IQ Unified Manager 《_景點API開發人員指南》_。

link:../api-automation/concept_get_started_with_um_apis.html["《NetApp API開發人員指南》Active IQ Unified Manager"]
