---
permalink: config/task_configure_event_notification_settings.html 
sidebar: sidebar 
keywords: configure, event, notification, settings 
summary: 您可以設定Unified Manager在事件產生或事件指派給使用者時傳送警示通知。您可以設定用於傳送警示的SMTP伺服器、也可以設定各種通知機制、例如、警示通知可作為電子郵件或SNMP設陷傳送。 
---
= 設定事件通知設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定Unified Manager在事件產生或事件指派給使用者時傳送警示通知。您可以設定用於傳送警示的SMTP伺服器、並設定各種通知機制、例如、警示通知可以以電子郵件或SNMP設陷傳送。

.開始之前
您必須具備下列資訊：

* 傳送警示通知的電子郵件地址
+
電子郵件地址會出現在「已傳送警示通知」的「寄件者」欄位中。如果由於任何原因而無法傳送電子郵件、此電子郵件地址也會作為無法傳送郵件的收件者。

* 用於存取伺服器的SMTP伺服器主機名稱、以及使用者名稱和密碼
* 接收SNMP設陷之設陷目的地主機的主機名稱或IP位址、以及SNMP版本、傳出設陷連接埠、社群及其他必要的SNMP組態值
+
若要指定多個設陷目的地、請以逗號分隔每個主機。在此情況下、清單中所有主機的所有其他SNMP設定（例如版本和傳出陷阱連接埠）必須相同。



您必須具有應用程式管理員或儲存管理員角色。

.步驟
. 在左側導覽窗格中、按一下*一般*>*通知*。
. 在「通知」頁面中、設定適當的設定。
+
* 附註： *

+
** 如果寄件者地址已預先填入「+ActiveIQUnifiedManager@localhost.com」地址、您應該將其變更為實際有效的電子郵件地址、以確保所有電子郵件通知都能順利傳送。
** 如果無法解析SMTP伺服器的主機名稱、您可以指定SMTP伺服器的IP位址（IPv4或IPv6）、而非主機名稱。


. 按一下「 * 儲存 * 」。
. 如果您選取了「*使用ARTTLS*或*使用SSL*」選項、在您按一下「*儲存*」按鈕之後、就會顯示憑證頁面。驗證憑證詳細資料、並接受憑證以儲存通知設定。
+
您可以按一下「*檢視憑證詳細資料*」按鈕來檢視憑證詳細資料。如果現有的憑證已過期、請取消勾選「*使用ARTTLS*或*使用SSL*」方塊、儲存通知設定、然後再次勾選「*使用ARTTLS*或*使用SSL*」方塊以檢視新的憑證。


