---
permalink: config/task_add_space_to_data_directory_of_um_linux_host.html 
sidebar: sidebar 
keywords: add, space, data directory, linux, host 
summary: 如果您在最初設定Linux主機並安裝Unified Manager時、將磁碟空間不足分配給「/opt/NetApp/data」目錄以支援Unified Manager、則可在安裝後增加磁碟空間、方法是在「/opt/NetApp/data」目錄中增加磁碟空間。 
---
= 將空間新增至Linux主機的資料目錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您在最初設定Linux主機並安裝Unified Manager時、將磁碟空間不足分配給「/opt/NetApp/data」目錄以支援Unified Manager、則可在安裝後增加磁碟空間、方法是在「/opt/NetApp/data」目錄中增加磁碟空間。

.開始之前
您必須具有 root 使用者存取權限，才能存取安裝 Unified Manager 的 Red Hat Enterprise Linux 機器。

建議您先備份Unified Manager資料庫、再增加資料目錄的大小。

.步驟
. 以root使用者身分登入您要新增磁碟空間的Linux機器。
. 依照下列順序停止Unified Manager服務及相關的MySQL軟體：
+
《神祕世界》

. 建立具有足夠磁碟空間的暫用備份資料夾（例如：「/backup-data」）、以將資料包含在目前的「/opt/NetApp/data」目錄中。
. 將現有的「/opt/NetApp/data（選擇/ NetApp）目錄的內容和權限組態複製到備份資料目錄：
+
「cp -arp /opt/NetApp/data/*/backup-data」

. 如果已啟用SE Linux：
+
.. 在現有的「/opt/NetApp/data」資料夾中取得資料夾的SE Linux類型：
+
`se_type= ls -Z /opt/netapp/data | awk '{print $4}' | awk -F: '{print $3}' | head -1`

+
系統會傳回類似下列的確認訊息：

+
[listing]
----
echo $se_type
mysqld_db_t
----
.. 執行chcon命令、為備份目錄設定SE Linux類型：
+
「chcon -R --type = mysqld_db_t/backup-data」



. 移除「/opt/NetApp/data（選擇/ NetApp /資料）目錄的內容：
+
.. 「CD /opt/NetApp/data」
.. 「rm -RF *」


. 透過LVM命令或新增額外的磁碟、將「/opt/NetApp/data」目錄的大小擴充至至少150 GB。
+
[NOTE]
====
如果您已從磁碟建立了「/opt/NetApp/data」、則不應嘗試將「/ops/NetApp/data」掛載為NFS或CIFS共用。在這種情況下、如果您嘗試擴充磁碟空間、某些LVM命令（例如「大小」和「擴充」）可能無法如預期般運作。

====
. 確認「/opt/NetApp/data'目錄擁有者（mySQL）和群組（root）沒有變更：
+
「ls -ltr /opt/netapp/| grep data」

+
系統會傳回類似下列的確認訊息：

+
[listing]
----
drwxr-xr-x.  17 mysql root  4096 Aug 28 13:08 data
----
. 如果已啟用SE Linux、請確認「/opt/netapp/data'」目錄的內容仍設定為mysqld_db_t:
+
.. 「Touch /opt/NetApp/data/abc」
.. 「ls -Z /opt/NetApp/data/abc」
+
系統會傳回類似下列的確認訊息：

+
[listing]
----
-rw-r--r--. root root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/abc
----


. 刪除abc檔案、以避免此無關檔案在未來造成資料庫錯誤。
. 將內容從備份資料複製回擴充的「/ope/NetApp/data'目錄：
+
「cp -arp /backup-data/*/opt/NetApp/data/」

. 如果已啟用SE Linux、請執行下列命令：
+
「chcon -R --type=mysqld_db_t /opp/netapp/data'

. 啟動MySQL服務：
+
《stystemctl start mysqld》

. MySQL服務啟動後、請依下列順序啟動ocie和ocieau服務：
+
《神祕之星》

. 所有服務啟動後、請刪除備份資料夾「/backup-data」：
+
「rm -rf /backup-data」


