---
permalink: config/task_generate_an_https_security_certificate_ocf.html 
sidebar: sidebar 
keywords: generate, https, security, certificate 
summary: 首次安裝時、會安裝預設的HTTPS憑證。Active IQ Unified Manager您可能會產生新的HTTPS安全性憑證來取代現有的憑證。 
---
= 產生HTTPS安全性憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
首次安裝時、會安裝預設的HTTPS憑證。Active IQ Unified Manager您可能會產生新的HTTPS安全性憑證來取代現有的憑證。

*您需要的是什麼*

您必須具有應用程式管理員角色。

重新產生憑證可能有多種原因、例如您想要擁有更好的辨別名稱（DN）值、或是想要較高的金鑰大小、或是較長的過期期間、或是目前的憑證已過期。

如果您無法存取Unified Manager Web UI、可以使用維護主控台重新產生具有相同值的HTTPS憑證。重新產生憑證時、您可以定義金鑰大小和金鑰的有效期間。如果您從維護主控台使用「重設伺服器憑證」選項、則會建立新的HTTPS憑證、有效期為397天。此憑證的RSA金鑰大小為2048位元。

.步驟
. 在左導覽窗格中、按一下*一般*>* HTTPS憑證*。
. 按一下*重新產生HTTPS憑證*。
+
此時會顯示重新產生HTTPS憑證對話方塊。

. 根據您要產生憑證的方式、選取下列其中一個選項：
+
[cols="2*"]
|===
| 如果您想要... | 執行此動作... 


 a| 
以目前值重新產生憑證
 a| 
按一下*使用目前的憑證屬性重新產生*選項。



 a| 
使用不同的值產生憑證
 a| 
按一下*更新目前的憑證屬性*選項。

如果您未輸入新值、「一般名稱」和「替代名稱」欄位會使用現有憑證的值。「Common Name」（一般名稱）應設定為主機的FQDN。其他欄位不需要值、但您可以輸入值、例如電子郵件、公司、部門、 城市、州/省和國家/地區（如果您希望在證書中填入這些值）。您也可以從可用的金鑰大小（金鑰演算法為「'rSA'」）和有效期間中進行選擇。

[NOTE]
====
** 允許的金鑰大小值為「2048」、「3072」和「4096」。
** 有效期間最短為1天、最長為36500天。
+
即使允許使用36500天的有效期間、建議您使用不超過397天或13個月的有效期間。因為如果您選取超過3997天的有效期間、並計畫匯出此憑證的CSR並由已知的CA簽署、CA傳回給您的已簽署憑證的有效性將減至3997天。

** 如果您要從憑證的替代名稱欄位中移除本機識別資訊、可以選取「排除本機識別資訊（例如localhost）」核取方塊。選取此核取方塊時、替代名稱欄位中只會使用您在欄位中輸入的內容。如果保留空白、則產生的憑證將完全沒有替代名稱欄位。


====
|===
. 按一下「*是*」以重新產生憑證。
. 重新啟動Unified Manager伺服器、使新的憑證生效。
. 檢視HTTPS憑證來驗證新的憑證資訊。

