---
permalink: install-linux/qsg-linux.html 
sidebar: sidebar 
keywords: quick start guide, getting started, QSG, Linux QSG, RHEL QSG, quick installation 
summary: Linux平台上的Unified Manager快速入門指南。 
---
= Linux安裝的快速入門指示
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以下載安裝套件、並在實體或虛擬Red Hat Enterprise Linux或CentOS平台上安裝Unified Manager。



== 系統需求

* 作業系統：Red Hat Enterprise Linux 7.x版和8.x版或CentOS 7.x版（以x86_64架構為基礎）、安裝時使用作業系統安裝程式*軟體選擇*選項中的「Server with GUI」基礎環境
* RAM：12 GB、CPU：總共9572 MHz
* 可用磁碟空間：在「/opt/NetApp/data」目錄中有100 GB的磁碟空間、在根分割區中有50 GB的磁碟空間。對於單獨掛載的「/opt」和「/var/log」目錄、請確定「/opt」有15 GB、「/var/log/log」有16 GB、「/tmp」有10 GB可用空間。


如需詳細的系統需求、以及在安全站台安裝產品的相關資訊、請參閱 link:../install-linux/concept_requirements_for_install_unified_manager.html["安裝Unified Manager的需求"] 和 link:http://mysupport.netapp.com/matrix["互通性對照表"]。



== 安裝Active IQ Unified Manager



=== 下載安裝程式

. 下載 `ActiveIQUnifiedManager-<version>.zip` 安裝套件及程式碼簽署憑證 (`.pem`）和數位簽章 (`.sig`）。
. 在您下載安裝檔案的目錄中、執行：
+
解壓縮ActiveIQUnifiedManager-<版本>.Zip





=== 驗證完整性

執行下列命令來驗證安裝程式套件的完整性：

* 執行 `openssl x509 -pubkey -noout -in AIQUM-RHEL-CLIENT-INTER-ROOT.pem > <public_key_file_name>` 從程式碼簽署憑證建立具有公開金鑰的檔案。
* 執行 `openssl dgst -sha256 -verify <public_key_file_name> -signature <signature_file_name> ActiveIQUnifiedManager-<version>.zip` 以驗證安裝程式套件上的簽名。




=== 驗證儲存庫組態

設定Red Hat Enterprise Linux或CentOS儲存庫的程序是站台專屬的。您可以使用安裝套件隨附的「pre_install_re支票.sh」指令碼來驗證作業系統的組態。如果您的系統已連線至網際網路、您會自動收到設定Red Hat Enterprise Linux或CentOS儲存庫的指示。

按#Sudo ./pre_install_cet.sh'



=== 安裝Unified Manager

Unified Manager使用「yum」公用程式來安裝軟體和任何相依軟體。由於Red Hat Enterprise Linux或CentOS的映像各不相同、因此安裝的套件取決於映像中的軟體。「yum」公用程式會決定要安裝的相依軟體套件。如果您需要有關相依軟體套件的詳細資訊、請參閱 link:../install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html["Linux軟體與安裝需求"]。

若要安裝Unified Manager、請以root使用者身分或使用「show」命令、從解壓縮安裝檔案的目錄執行下列命令：

yum安裝NetApp-um<版本>.x86_64。rpm'

或

% Sudo yum install NetApp-um<版本>.x86_64 .rpm'

安裝結束時、會顯示連線至Unified Manager Web UI的資訊。如果您無法連線至Web UI、請參閱軟體隨附的「README」檔案、以取得連接埠443限制的詳細資訊。
