---
permalink: install-linux/reference_red_hat_and_centos_software_and_installation_requirements.html 
sidebar: sidebar 
keywords: linux software, installation requirements, system, authorization,  requirements 
summary: 安裝Unified Manager的Linux系統需要特定版本的作業系統和支援軟體。 
---
= Linux軟體與安裝需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安裝Unified Manager的Linux系統需要特定版本的作業系統和支援軟體。



== 作業系統軟體

Linux系統必須安裝下列版本的作業系統和支援軟體：

* Red Hat Enterprise Linux 8.x 與 9.4 版，以 x86_64 架構為基礎。


請參閱互通性對照表，以取得支援的 Red Hat Enterprise Linux 版本完整且最新的清單。

http://mysupport.netapp.com/matrix["mysupport.netapp.com/matrix"^]

伺服器應專供執行Unified Manager。伺服器上不應安裝其他應用程式。由於公司法規、 Linux 系統上可能會安裝 Qualys 等弱點掃描工具。安裝 Unified Manager 之前、您應該先停用弱點掃描程式、以避免安裝失敗。


NOTE: 弱點掃描工具（例如 Qualys ）在內部（ Unified Manager 和弱點掃描工具安裝在同一部 VM 上）或外部掃描虛擬機器（ VM ）時、可能會導致 CPU 使用率偏高 （ Unified Manager 和弱點掃描程式安裝在兩部不同的伺服器上、弱點掃描程式會掃描安裝 Unified Manager 的 VM ）。此問題通常會導致 VM 無回應、並影響 Unified Manager 服務。因此、 NetApp 建議在安裝 Unified Manager 的 VM 中停用弱點掃描程式。如果無法停用掃描器、請在非上班時間掃描 VM 、並在掃描完成後重新啟動服務。



== 第三方軟體

Unified Manager部署在Wildfly Web伺服器上。WildFly 26.1.3 已隨附於 Unified Manager 、並已設定。

Unified Manager需要下列協力廠商套件、但未隨附於其中。這些套件會在安裝期間由「yum」安裝程式自動安裝、前提是您已依照下列各節所述設定儲存庫。

* MySQL Community Edition 8.0.37 版（來自 MySQL 儲存庫）。
* OpenJDK 11.0.23 版（來自 Red Hat Extra Enterprise Linux Server 儲存庫）
* Python 3.6.x
* p7Zip版本16.02或更新版本（來自Red Hat Extra Packaged for Enterprise Linux儲存庫）


[NOTE]
====
在升級任何協力廠商軟體之前、您必須先關閉正在執行的Unified Manager執行個體。第三方軟體安裝完成後、您可以重新啟動Unified Manager。

====


== 使用者授權要求

在Linux系統上安裝Unified Manager可以由root使用者或非root使用者使用「show」命令來執行。



== 安裝需求

以下列出在系統上安裝 Red Hat Enterprise Linux 和相關儲存庫的最佳實務做法。安裝或設定不同的系統、或是部署在異地（雲端）、可能需要額外的步驟、而Unified Manager可能無法在這類部署中正常運作。

* 您必須根據 Red Hat 最佳實務做法來安裝 Red Hat Enterprise Linux ，並應選取下列預設選項，這需要選取「使用 GUI 伺服器」基礎環境。
* 在 Red Hat Enterprise Linux 上安裝 Unified Manager 時，系統必須能夠存取適當的儲存庫，以便安裝程式能夠存取及安裝所有必要的軟體相依性。
* 若要讓「yum」安裝程式在Red Hat Enterprise Linux儲存庫中找到相依軟體、您必須在Red Hat Enterprise Linux安裝期間或之後使用有效的Red Hat訂閱來註冊系統。
+
如需Red Hat訂購管理程式的相關資訊、請參閱Red Hat說明文件。

* 您必須啟用Enterprise Linux（E規劃）的額外套件儲存庫、才能在系統上成功安裝所需的協力廠商公用程式。
+
如果系統上未設定Epel儲存庫、您必須手動下載及設定儲存庫。

+
請參閱 link:task_manually_configure_epel_repository.html["手動設定Epel儲存庫"]。

* 如果未安裝正確版本的MySQL、您必須啟用MySQL儲存庫、才能在系統上成功安裝MySQL軟體。
+
如果您的系統上未設定MySQL儲存庫、則必須手動下載及設定儲存庫。

+
請參閱 link:task_manually_configure_mysql_repository.html["手動設定MySQL儲存庫"]。



如果您的系統無法存取網際網路、而且儲存庫並未從連線至未連線系統的網際網路連線系統鏡射到未連線的系統、則應遵循安裝指示來判斷系統的外部軟體相依性。然後，您可以將必要的軟體下載到連線網際網路的系統，並將檔案複製 `.rpm`到您計畫安裝 Unified Manager 的系統。若要下載成品和套件，您必須使用 `yum install`命令。您必須確保兩個系統執行相同的作業系統版本，且訂閱授權適用於適當的 Red Hat Enterprise Linux 。

[NOTE]
====
您不得從此處列出的儲存庫以外的儲存庫安裝所需的協力廠商軟體。從Red Hat儲存庫安裝的軟體是專為Red Hat Enterprise Linux所設計、並符合Red Hat最佳實務做法（目錄配置、權限等）。來自其他位置的軟體可能不遵守這些準則、這可能會導致Unified Manager安裝失敗、或是在未來升級時造成問題。

====


== 連接埠443需求

Red Hat Enterprise Linux 的一般映像可能會封鎖連接埠 443 的外部存取。由於此限制、您可能無法在安裝Unified Manager之後連線至系統管理員Web UI。執行下列命令可讓一般 Red Hat Enterprise Linux 上的所有外部使用者和應用程式存取連接埠 443 。

防火牆-cmd --partni=public-add-port=443/tcp --fur永久性；防火牆-cmd --relev'

您必須安裝 Red Hat Enterprise Linux 搭配「 Server with GUI 」基礎環境。它提供Unified Manager安裝說明所使用的命令。其他基礎環境可能需要您安裝額外的命令來驗證或完成安裝。如果系統上沒有可用的 `firewall-cmd`，您必須執行下列命令來安裝：

#Sudo yum install firewalld'

執行命令之前、請先聯絡您的IT部門、以瞭解您的安全性原則是否需要不同的程序。

[NOTE]
====
應在 Red Hat 系統上停用 THP （透明的大頁面）。啟用時、在某些情況下、當某些程序耗用過多記憶體並終止時、可能會導致Unified Manager關機。

====