---
permalink: install-linux/task_upgrade_unified_manager.html 
sidebar: sidebar 
keywords: upgrade, unified manager 
summary: 您可以在Red Hat平台上下載並執行安裝檔案、以升級Unified Manager。 
---
= 升級Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Red Hat平台上下載並執行安裝檔案、從Unified Manager 9.8或9.9升級至9.10。

*您需要的是什麼*

* 您要升級Unified Manager的系統必須符合系統和軟體需求。
+
link:concept_virtual_infrastructure_or_hardware_system_requirements.html["硬體系統需求"]

+
link:reference_red_hat_and_centos_software_and_installation_requirements.html["Red Hat與CentOS軟體與安裝需求"]

* 升級Unified Manager之前、您必須先安裝或升級至正確版本的OpenJDK。
+
link:task_upgrade_openjdk_on_linux_ocum.html["升級Linux上的JRE"]

* 您必須訂閱Red Hat Enterprise Linux訂閱管理程式。
* 為了避免資料遺失、您必須先建立Unified Manager資料庫的備份、以防升級期間發生問題。此外、建議您將備份檔案從「/ope/NetApp/data」目錄移至外部位置。
* 在升級期間、系統可能會提示您確認是否要保留先前的預設設定、以保留13個月的效能資料、或將其變更為6個月。確認後、系統會清除6個月後的歷史效能資料。
* 您應該已經完成所有執行中的作業、因為Unified Manager在升級過程中無法使用。
* * MySQL需求*：MySQL社群版會在Unified Manager升級期間自動升級。如果您系統上安裝的MySQL版本早於8.0.27、Unified Manager升級程序會自動將MySQL升級至8.0.27。
+
不過、您可能想要將MySQL升級至系統上最新的次要版本。在升級至下一個次要版本之前、請確定您系統上的MySQL基礎版本為8.0.27。

+
如果您的站台沒有設定MySQL 8.0.27的儲存庫、您可能無法升級Unified Manager。若要在升級前設定儲存庫、請執行下列步驟：

+
.. 下載MySQL RPM套件、並將其儲存在儲存「NetApp-um<版本>.x86_64 .rpm」的相同目錄中（本例為8.0.27）。
.. 執行此命令以安裝新版本：「yum install *。rpm」
.. 啟動Unified Manager伺服器。執行下列命令：
+
... 《stystemcl start ocie》
... 《stystemcl start ocieau》






.步驟
. 登入目標Red Hat Enterprise Linux或CentOS伺服器。
. 將Unified Manager產品組合下載至伺服器。
+
link:task_download_unified_manager.html["下載適用於Red Hat或CentOS的Unified Manager"]

. 瀏覽至目標目錄並展開Unified Manager套裝組合：
+
「unzip ActiveIQUnifiedManager-<版本>.Zip」

+
Unified Manager所需的RPM模組會解壓縮至目標目錄。

. 驗證目錄中是否有下列模組可用：
+
「ls *。rpm」

+
「netapp-um<版本>.x86_64。rpm」

. *選用：*若系統未連線至網際網路、或未使用Red Hat Enterprise Linux儲存庫、請執行下列步驟、判斷是否遺漏任何必要的套件、然後下載這些套件：
+
.. 檢視可用和不可用套件的清單：
+
「yum install NetApp-um<版本>.x86_64.rpm --assumeno'

+
「正在安裝：」區段中的項目是目前目錄中可用的套件、而「正在安裝相依套件：」區段中的項目是您系統上遺失的套件。

.. 在可存取網際網路的其他系統上、執行下列命令來下載遺失的套件。
+
「yum install package_name --downloadonly ---downloadloaddidr=.」

+
這些套件會下載到指定為「-Downloaddyr=s」的目錄中。

+
由於Red Hat Enterprise Linux系統並未一律啟用外掛程式「yum外掛程式-downloadonly」、因此您可能需要啟用下載套件的功能、而不需安裝：

+
「yum install yum plugin-downloadonly」

.. 在安裝系統中建立新目錄、然後從連網際網路的系統複製下載的套件。
.. 將目錄變更為安裝系統上的新目錄、然後執行下列命令來安裝MySQL Community Edition及其相依性。
+
「yum install *。rpm」



. 執行安裝前指令碼、確保沒有系統組態設定或任何可能與升級衝突的安裝軟體：
+
「Udo ./pre_install_re支票.sh」

+
安裝前指令碼會檢查系統是否有有效的Red Hat訂閱、以及是否有權存取所需的軟體儲存庫。如果指令碼發現任何問題、您必須先修正問題、然後再升級Unified Manager。

. 使用下列指令碼升級Unified Manager：
+
"升級.sh"

+
此指令碼會自動執行RPM模組、並升級必要的支援軟體及其上執行的Unified Manager模組。此外、升級指令碼會檢查是否有任何系統組態設定或任何可能與升級衝突的安裝軟體。如果指令碼發現任何問題、您必須先修正問題、然後再升級Unified Manager。

. 升級完成後、捲動回訊息、直到看到訊息顯示Unified Manager Web UI的IP位址或URL、維護使用者名稱（umadmin）和預設密碼。
+
此訊息類似於下列內容：

+
[listing]
----
Active IQ Unified Manager upgraded successfully.
Use a web browser and one of the following URLs to access the Unified Manager GUI:

https://default_ip_address/    (if using IPv4)
https://[default_ip_address]/  (if using IPv6)
https://fully_qualified_domain_name/
----


在支援的網頁瀏覽器中輸入指定的IP位址或URL、以啟動Unified Manager網路UI、然後使用您先前設定的相同維護使用者名稱（umadmin）和密碼登入。
