---
permalink: install-linux/task_upgrade_host_os.html 
sidebar: sidebar 
keywords: upgrade, host OS, red hat enterprise, linux 7.x, 8.x 
summary: 如果您先前在Red Hat Enterprise Linux 7.x系統上安裝Unified Manager、且需要升級至Red Hat Enterprise Linux 8.x、則必須遵循本主題所列的其中一個程序。在這兩種情況下、您都必須在Red Hat Enterprise Linux 7.x系統上建立Unified Manager備份、然後將備份還原至Red Hat Enterprise Linux 8.x系統。 
---
= 將主機作業系統從 Red Hat Enterprise Linux 7.x 升級到 8.x
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您先前在Red Hat Enterprise Linux 7.x系統上安裝Unified Manager、而且需要升級至Red Hat Enterprise Linux 8.x、則必須遵循本主題所列的其中一個程序。在這兩種情況下、您都必須在Red Hat Enterprise Linux 7.x系統上建立Unified Manager備份、然後將備份還原至Red Hat Enterprise Linux 8.x系統。請注意、支援的 Red Hat Enterprise Linux 版本從 8.0 到 8.10 。

下列兩個選項的差異在於：在一種情況下、您要在新的8.x伺服器上執行Unified Manager還原、而在另一種情況下、您要在同一部伺服器上執行還原作業。

因為這項工作需要您在Red Hat Enterprise Linux 7.x系統上建立Unified Manager備份、所以只有在準備好完成整個升級程序、Unified Manager才能離線最短時間時、才應該建立備份。在Red Hat Enterprise Linux 7.x系統關閉期間、以及新的Red Hat Enterprise Linux 8.x啟動之前、Unified Manager UI中會出現所收集資料的落差。

請參閱 link:../health-checker/concept_manage_backup_and_restore_operations.html["管理備份與還原作業"] 如果您需要檢閱備份與還原程序的詳細指示。

如果您有備用系統、可以在其中安裝Red Hat Enterprise Linux 8.x軟體、以便在Red Hat Enterprise Linux 7.x系統仍可使用時、在該系統上執行Unified Manager還原、請遵循下列步驟。

. 使用Red Hat Enterprise Linux 8.x軟體安裝及設定新伺服器。
+
請參閱。 link:reference_red_hat_software_and_installation_requirements.html["Linux軟體與安裝需求"]

. 在Red Hat Enterprise Linux 8.x系統上、安裝與現有Red Hat Enterprise Linux 7.x系統相同版本的Unified Manager軟體。
+
請參閱。 link:concept_install_unified_manager_on_rhel.html["在Linux上安裝Unified Manager"]

+
安裝完成時、請勿啟動UI或設定任何叢集、使用者或驗證設定。備份檔案會在還原程序期間填入此資訊。

. 在Red Hat Enterprise Linux 7.x系統上、從Web UI的管理功能表建立Unified Manager備份、然後將備份檔案（`.7z檔案）和資料庫儲存庫目錄（`/database-dump -repo'子目錄）的內容複製到外部位置。
. 在Red Hat Enterprise Linux 7.x系統上、關閉Unified Manager。
. 在Red Hat Enterprise Linux 8.x系統上、將備份檔案（如「.7z」檔案）從外部位置複製到「/opt/NetApp/data/ocum-backup/」、並將資料庫儲存庫檔案複製到「/database-dump -repo」子目錄下的「/ocum-Backup」目錄下。
. 輸入下列命令、從備份檔案還原Unified Manager資料庫：
+
「um備份還原-f /opt/netapp/data/ocum-backup/<backup_file_name>」

. 在網頁瀏覽器中輸入IP位址或URL、以啟動Unified Manager網路UI、然後登入系統。


驗證系統是否正常運作之後、您就可以從Red Hat Enterprise Linux 7.x系統移除Unified Manager。

*升級同一部伺服器上的主機作業系統*

如果您沒有可安裝Red Hat Enterprise Linux 8.x軟體的備用系統、請遵循下列步驟。

. 從Web UI的「管理」功能表中、建立Unified Manager備份、然後將備份檔案（`.7z檔案）和資料庫儲存庫目錄（`/database-dump -repo'子目錄）的內容複製到外部位置。
. 從系統中移除Red Hat Enterprise Linux 7.x映像、然後完全抹除系統。
. 在同一個系統上安裝及設定Red Hat Enterprise Linux 8.x軟體。
+
請參閱。 link:reference_red_hat_software_and_installation_requirements.html["Linux軟體與安裝需求"]

. 在Red Hat Enterprise Linux 8.x系統上、安裝與Red Hat Enterprise Linux 7.x系統相同版本的Unified Manager軟體。
+
請參閱。 link:concept_install_unified_manager_on_rhel.html["在Linux上安裝Unified Manager"]

+
安裝完成時、請勿啟動UI或設定任何叢集、使用者或驗證設定。備份檔案會在還原程序期間填入此資訊。

. 將備份檔案（如「.7z」檔案）從外部位置複製到「/opt/netapp/data/ocum-backup/」、並將資料庫儲存庫檔案複製到「/ocum-Backup」目錄下的「/database-dump -repo」子目錄。
. 輸入下列命令、從備份檔案還原Unified Manager資料庫：
+
「um備份還原-f /opt/netapp/data/ocum-backup/<backup_file_name>」

. 在網頁瀏覽器中輸入IP位址或URL、以啟動Unified Manager網路UI、然後登入系統。

