---
permalink: events/concept_guidelines_for_adding_alerts.html 
sidebar: sidebar 
keywords: guidelines, adding, alerts 
summary: 您可以根據資源（例如叢集、節點、Aggregate或Volume）以及特定嚴重性類別的事件來新增警示。最佳實務做法是在新增物件所屬的叢集之後、針對任何重要物件新增警示。 
---
= 新增警示的準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以根據資源（例如叢集、節點、Aggregate或Volume）以及特定嚴重性類別的事件來新增警示。最佳實務做法是在新增物件所屬的叢集之後、針對任何重要物件新增警示。

您可以使用下列準則和考量來建立警示、以有效管理系統：

* 警示說明
+
您應該提供警示說明、以便有效追蹤警示。

* 資源
+
您應該決定哪些實體或邏輯資源需要警示。您可以視需要納入和排除資源。例如、如果您想要透過設定警示來密切監控集合體、則必須從資源清單中選取所需的集合體。

+
如果您選取資源類別、例如*+ User or Group Quotas+*、您將會收到該類別中所有物件的警示。

+
[NOTE]
====
選取叢集做為資源並不會自動選取該叢集內的儲存物件。例如、如果您為所有叢集的所有重大事件建立警示、您將只會收到叢集重大事件的警示。您不會收到節點、集合體等關鍵事件的警示。

====
* 事件嚴重性
+
您應該決定是否應觸發指定嚴重性類型（嚴重、錯誤、警告）的警示、如果是、則應觸發何種嚴重性類型。

* 所選事件
+
如果您根據所產生的事件類型新增警示、則應決定哪些事件需要警示。

+
如果您選取事件嚴重性、但未選取任何個別事件（如果您將「選取的事件」欄保留空白）、則會收到類別中所有事件的警示。

* 行動
+
您必須提供接收通知之使用者的使用者名稱和電子郵件地址。您也可以將SNMP設陷指定為通知模式。您可以將指令碼與警示建立關聯、以便在產生警示時執行。

* 通知頻率
+
您可以設定警示、在指定時間內重複傳送通知給收件者。您應該決定警示的事件通知啟動時間。如果您想要在事件被確認之前重複發出事件通知、您應該決定要重複通知的頻率。

* 執行指令碼
+
您可以將指令碼與警示建立關聯。指令碼會在產生警示時執行。


