---
permalink: events/reference_event_details_page.html 
sidebar: sidebar 
keywords: event, details, page 
summary: 從「事件詳細資料」頁面、您可以檢視所選事件的詳細資料、例如事件嚴重性、影響層級、影響區域及事件來源。您也可以檢視有關可能修正的其他資訊、以解決此問題。 
---
= 活動詳細資料頁面
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從「事件詳細資料」頁面、您可以檢視所選事件的詳細資料、例如事件嚴重性、影響層級、影響區域及事件來源。您也可以檢視有關可能修正的其他資訊、以解決此問題。

* *活動名稱*
+
事件名稱和事件上次出現的時間。

+
對於非效能事件、當事件處於「New（新增）」或「Known（已確認）」狀態時、不會知道最後看到的資訊、因此會隱藏。

* *事件說明*
+
活動的簡短說明。

+
在某些情況下、事件說明會提供觸發事件的原因。

* *元件爭用中*
+
對於動態效能事件、本節會顯示代表叢集邏輯和實體元件的圖示。如果元件發生爭用、其圖示會圈選並反白顯示為紅色。

+
請參閱_叢集元件及其爭用原因_、以瞭解此處顯示的元件說明。



其他主題將說明「事件資訊」、「系統診斷」及「建議動作」等區段。



== 命令按鈕

命令按鈕可讓您執行下列工作：

* *附註圖示*
+
可讓您新增或更新事件的相關附註、並檢閱其他使用者留下的所有附註。



*動作功能表*

* *指派給我*
+
將事件指派給您。

* *指派給其他人*
+
開啟「指派擁有者」對話方塊、可讓您指派或重新指派事件給其他使用者。

+
當您將事件指派給使用者時、系統會在所選事件的事件清單中新增使用者名稱和指派事件的時間。

+
您也可以將擁有權欄位保留空白、以取消指派事件。

* *認知*
+
確認所選的事件、以免您繼續收到重複警示通知。

+
當您確認某個事件時、您的使用者名稱和您確認該事件的時間會新增至所選事件的事件清單（確認者）。當您確認某個事件時、您必須負責管理該事件。

* *標示為已解決*
+
可讓您將事件狀態變更為「已解決」。

+
解決事件時、您的使用者名稱和解決事件的時間會新增至所選事件的事件清單（解決者）。針對事件採取修正行動之後、您必須將事件標示為「已解決」。

* *新增警示*
+
顯示「新增警示」對話方塊、可讓您新增所選事件的警示。


