---
permalink: events/reference_cluster_events.html 
sidebar: sidebar 
keywords: cluster events, impact, area, availability, capacity, configuration, performance, security 
summary: 叢集事件提供有關叢集狀態的資訊、可讓您監控叢集是否有潛在問題。這些事件會依影響區域分組、包括事件名稱、陷阱名稱、影響層級、來源類型和嚴重性。 
---
= 叢集事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
叢集事件提供有關叢集狀態的資訊、可讓您監控叢集是否有潛在問題。這些事件會依影響區域分組、包括事件名稱、陷阱名稱、影響層級、來源類型和嚴重性。



== 影響領域：可用度

星號（*）表示已轉換為Unified Manager事件的EMS事件。

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
叢集缺乏備用磁碟（ocumEvtDisksNoSpare）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集無法連線（ocumEvtClusterUnreachable）
 a| 
風險
 a| 
叢集
 a| 
錯誤



 a| 
叢集監控失敗（ocumEvtClusterMonitoring監控失敗）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集FabricPool 不受授權容量限制（ocumEvtExternalCapacityTierSpaceFull）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
NVMe寬限期開始時間*（nvmfGracePeriodStart）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
NVMe寬限期有效*（nvmfGracePeriodActive）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
NVMe寬限期已過期*（nvmfGracePeriodExpired）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
物件維護視窗已啟動（物件維護視窗已啟動）
 a| 
活動
 a| 
叢集
 a| 
關鍵



 a| 
物件維護視窗已結束（物件維護視窗已編碼）
 a| 
活動
 a| 
叢集
 a| 
資訊



 a| 
支援的備用磁碟（ocumEvtSpareDiskLeftBehind）MetroCluster
 a| 
風險
 a| 
叢集
 a| 
錯誤



 a| 
停用自動非計畫性切換（ocumEvtMccAutomaticUnplannedSwitchOverDisabled）MetroCluster
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集使用者密碼已變更*（cluster.passwd.changed）
 a| 
活動
 a| 
叢集
 a| 
資訊

|===


== 影響領域：容量

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
叢集容量不平衡臨界值已超出（ocumConformanceNodeImpalanceWarnings）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集雲端層規劃（叢集CloudTierPlanningWarnings）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
完成的鏡射複寫重新同步*（waflCafresyncdet）FabricPool
 a| 
活動
 a| 
叢集
 a| 
警告



 a| 
幾乎已滿*（fabricPoolNearlyFull）的空間FabricPool
 a| 
風險
 a| 
叢集
 a| 
錯誤

|===


== 影響領域：組態

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
新增節點（不適用）
 a| 
活動
 a| 
叢集
 a| 
資訊



 a| 
節點已移除（不適用）
 a| 
活動
 a| 
叢集
 a| 
資訊



 a| 
已移除叢集（不適用）
 a| 
活動
 a| 
叢集
 a| 
資訊



 a| 
叢集新增失敗（不適用）
 a| 
活動
 a| 
叢集
 a| 
錯誤



 a| 
叢集名稱已變更（不適用）
 a| 
活動
 a| 
叢集
 a| 
資訊



 a| 
收到緊急EMS（不適用）
 a| 
活動
 a| 
叢集
 a| 
關鍵



 a| 
收到關鍵EMS（不適用）
 a| 
活動
 a| 
叢集
 a| 
關鍵



 a| 
收到警示EMS（不適用）
 a| 
活動
 a| 
叢集
 a| 
錯誤



 a| 
收到EMS錯誤（不適用）
 a| 
活動
 a| 
叢集
 a| 
警告



 a| 
收到EMS警告（不適用）
 a| 
活動
 a| 
叢集
 a| 
警告



 a| 
偵錯EMS已收到（不適用）
 a| 
活動
 a| 
叢集
 a| 
警告



 a| 
收到EMS通知（不適用）
 a| 
活動
 a| 
叢集
 a| 
警告



 a| 
收到資訊性EMS（不適用）
 a| 
活動
 a| 
叢集
 a| 
警告

|===
將EMS事件分為三個Unified Manager事件嚴重性等級。ONTAP

|===


| Unified Manager事件嚴重性層級 | 不支援緊急服務事件嚴重性等級ONTAP 


 a| 
關鍵
 a| 
緊急狀況

關鍵



 a| 
錯誤
 a| 
警示



 a| 
警告
 a| 
錯誤

警告

偵錯

注意

資訊

|===


== 影響領域：效能

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
叢集負載不平衡臨界值已突破（）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集IOPS臨界臨界值已違反（ocumClusterIopsIncident）
 a| 
事件
 a| 
叢集
 a| 
關鍵



 a| 
叢集IOPS警告臨界值已超出（ocumClusterIopsWarnings）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集MB/s重大臨界值已超出（ocumClusterMbps突 發事件）
 a| 
事件
 a| 
叢集
 a| 
關鍵



 a| 
叢集MB/s警告臨界值已超出（ocumClusterMbpsWarnings）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集動態臨界值已超出（ocumClusterDynamicEventWarnings[叢集動態臨界值]）
 a| 
風險
 a| 
叢集
 a| 
警告

|===


== 影響領域：安全性

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
停用SUTHTTPS傳輸（ocumClusterASUPHttpsConfigured已停用）AutoSupport
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
記錄轉送未加密（ocumClusterAuditLogUnEncrypted）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
啟用預設本機管理使用者（ocumClusterDefaultAdminEnabled）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
FIPS模式已停用（ocumClusterFipsDisabled）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
停用登入橫幅（ocumClusterLoginBannerDisabled）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
登入橫幅已變更（ocumClusterLoginBannerChanged）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
記錄轉送目的地已變更（ocumLogForward目的地變更）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
NTP伺服器名稱已變更（ocumNtpServerNamesChanged）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
NTP伺服器計數低（安全性設定NTPServerCountLowRisk）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集對等通訊未加密（ocumClusterPeerEncryptionDisabled）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
SSH使用不安全的密碼（ocumClusterSSHInSecure）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
已啟用遠端登入傳輸協定（ocumClusterTelnetEnabled）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
某些ONTAP 使用者帳戶的密碼使用較不安全的MD5雜湊功能（ocumClusterMD5PasswordHashUsed）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集使用自我簽署的憑證（ocumClusterSelfSignedCertificate）
 a| 
風險
 a| 
叢集
 a| 
警告



 a| 
叢集遠端Shell已啟用（ocumClusterRshDisabled）
 a| 
風險
 a| 
叢集
 a| 
警告

|===