---
permalink: events/reference_lun_events.html 
sidebar: sidebar 
keywords: lun, events, impact area, availability, capacity, configuration, performance 
summary: LUN事件可提供LUN狀態的相關資訊、以便監控潛在問題。事件會依影響區域分組、包括事件和陷阱名稱、影響層級、來源類型和嚴重性。 
---
= LUN事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LUN事件可提供LUN狀態的相關資訊、以便監控潛在問題。事件會依影響區域分組、包括事件和陷阱名稱、影響層級、來源類型和嚴重性。



== 影響領域：可用度

星號（*）表示已轉換為Unified Manager事件的EMS事件。

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
LUN離線（ocumEvtLunOffline）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
LUN毀損*（lunD斷 點）
 a| 
活動
 a| 
LUN
 a| 
資訊



 a| 
在igroup中使用不受支援的作業系統對應LUN（igroupUnsupportedOsType）
 a| 
事件
 a| 
LUN
 a| 
警告



 a| 
存取LUN的單一作用中路徑（ocumEvtLunSingleActivePath）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
無存取LUN的作用中路徑（ocumEvtLunNotReachable）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
沒有最佳化的存取LUN路徑（ocumEvtLunOptimizedPathInactive）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
無法從HA合作夥伴存取LUN（ocumEvtLunPathInactive）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
HA配對中的一個節點沒有存取LUN的路徑（ocumEvtLunNodePathStatusDown）
 a| 
風險
 a| 
LUN
 a| 
錯誤

|===


== 影響領域：容量

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
LUN Snapshot複製空間不足（ocumEvtLunSnapshotNotPossible）
 a| 
風險
 a| 
Volume
 a| 
警告

|===


== 影響領域：組態

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
在igroup中使用不受支援的作業系統對應LUN（igroupUnsupportedOsType）
 a| 
風險
 a| 
LUN
 a| 
警告

|===


== 影響領域：效能

|===
| 事件名稱（陷阱名稱） | 影響層級 | 來源類型 | 嚴重性 


 a| 
違反LUN IOPS臨界值（ocumLunIopsIncident）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN IOPS警告臨界值（ocumlunIopsWarnings）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
LUN MB/s重大臨界值已超出（ocumLunMbps突 發事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN MB/s警告臨界值（ocumLunMbpsWarning）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲毫秒/營運關鍵臨界值（ocumlunlatency事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲毫秒/作業警告臨界值（ocumlunlatency警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和IOPS臨界臨界值（ocumLunLatency IopsIncident）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲和IOPS警告臨界值（ocumLunLatency IopsWarning）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和MB/s臨界臨界值（ocumlunLatency Mbps突 發事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲和MB/s警告臨界值（ocumlunLatency MbpsWarning）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和Aggregate效能已用容量臨界值（ocumLunLatency Aggregate Perf電容 已用事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲和Aggregate效能使用容量警告臨界值（ocumLunLatency Aggregate Perf電容 使用警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和彙總使用率臨界臨界值（ocumLunLatency Aggreggregate公用程式事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲和Aggregate使用率警告臨界值（ocumLunLatency Aggregate公用程式警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和節點效能使用容量臨界值（ocumLunityNodePerf電容 使用事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
LUN延遲和節點效能使用容量已超過警告臨界值（ocumLunLatency節點Perf電容 使用警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
使用的LUN延遲和節點效能容量-超過臨界臨界臨界值（ocumLunLatency Aggregate Perf電容 使用接管事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
使用的LUN延遲和節點效能容量-違反接管警告臨界值（ocumLunLatency Aggregate Perf電容 使用接管警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反LUN延遲和節點使用率臨界臨界臨界值（ocumLunLatency節點公用程式事件）
 a| 
事件
 a| 
LUN
 a| 
關鍵



 a| 
違反LUN延遲和節點使用率警告臨界值（ocumLunLatency節點公用程式警告）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反QoS LUN最大IOPS警告臨界值（ocumQoslunMaxIopsWarnings）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
違反QoS LUN最大MB/s警告臨界值（ocumQoslunMaxMbpsWarnings）
 a| 
風險
 a| 
LUN
 a| 
警告



 a| 
工作負載LUN延遲臨界值違反效能服務層級原則（ocumConformanceLatency警告）
 a| 
風險
 a| 
LUN
 a| 
警告

|===