---
permalink: events/task_add_scripts.html 
sidebar: sidebar 
keywords: add, scripts 
summary: 您可以在Unified Manager中新增指令碼、並將指令碼與警示建立關聯。這些指令碼會在產生警示時自動執行、並可讓您取得產生事件之儲存物件的相關資訊。 
---
= 新增腳本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在Unified Manager中新增指令碼、並將指令碼與警示建立關聯。這些指令碼會在產生警示時自動執行、並可讓您取得產生事件之儲存物件的相關資訊。

.開始之前
* 您必須已建立並儲存要新增至Unified Manager伺服器的指令碼。
* 支援的指令碼檔案格式包括Perl、Shell、PowerShell、Python和.bat'檔案。
+
|===
| 安裝Unified Manager的平台 | 支援的語言 


 a| 
VMware
 a| 
Perl和Shell指令碼



 a| 
Linux
 a| 
Perl、Python和Shell指令碼



 a| 
Windows
 a| 
PowerShell、Perl、Python和.bat指令碼

|===
+
** 對於Perl指令碼、Perl必須安裝在Unified Manager伺服器上。對於VMware安裝、預設會安裝Perl 5、而指令碼只會支援Perl 5所支援的功能。如果Perl是在Unified Manager之後安裝、您必須重新啟動Unified Manager伺服器。
** 對於PowerShell指令碼、必須在Windows伺服器上設定適當的PowerShell執行原則、才能執行指令碼。


+
[NOTE]
====
如果指令碼建立記錄檔來追蹤警示指令碼進度、您必須確保不會在Unified Manager安裝資料夾的任何位置建立記錄檔。

====
* 您必須具有應用程式管理員或儲存管理員角色。


您可以上傳自訂指令碼、並收集警示的事件詳細資料。

[NOTE]
====
如果您在使用者介面中沒有看到此功能、這是因為系統管理員已停用此功能。如有需要、您可以從*儲存管理*>*功能設定*啟用此功能。

====
.步驟
. 在左導覽窗格中、按一下*儲存管理*>*指令碼*。
. 在「*指令碼*」頁面中、按一下「*新增*」。
. 在*新增指令碼*對話方塊中、按一下*瀏覽*以選取指令碼檔案。
. 輸入所選指令碼的說明。
. 按一下「 * 新增 * 」。


*相關資訊*

link:../config/task_enable_and_disable_ability_to_upload_scripts.html["啟用及停用上傳指令碼的功能"]
