---
permalink: data-protection/reference_protection_storage_virtual_machine_associations_page.html 
sidebar: sidebar 
keywords: svm, association, page 
summary: Storage VM關聯頁面可讓您檢視來源與目的地儲存VM之間的現有儲存VM關聯。 
---
= 了解儲存虛擬機器關聯
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存虛擬機器（儲存VM）關聯是從來源儲存VM到目的地儲存VM的對應、合作夥伴應用程式會使用這些對應來選擇資源和次要Volume資源配置。

無論目的地儲存VM是次要目的地或第三目的地、都會在來源儲存VM和目的地儲存VM之間建立關聯。您無法使用次要目的地儲存VM作為來源、來建立與第三目的地儲存VM的關聯。

身為應用程式管理員或儲存管理員、您可以在* Protection *>* Storage VM Association*頁面上檢視環境中的儲存VM關聯。

您可以使用三種方式建立SVM的關聯：

* *關聯任何儲存VM*：您可以在任一主要來源儲存VM與一或多個目的地SVM之間建立關聯。這表示目前需要保護的所有現有SVM、以及未來建立的任何SVM、都會與指定的目的地SVM相關聯。例如、您可能想要將不同位置的多個不同來源的應用程式備份到同一個位置的一或多個目的地SVM。
* *關聯特定的儲存VM*：您可以在特定來源儲存VM與一或多個特定目的地SVM之間建立關聯。例如、如果您要提供儲存服務給許多用戶端、而這些用戶端的資料必須彼此分開、您可以選擇此選項、將特定來源儲存VM與僅指派給該用戶端的特定目的地儲存VM建立關聯。
* *與外部儲存VM*建立關聯：您可以在來源儲存VM與目的地儲存VM的外部彈性Volume之間建立關聯。




== 建立儲存VM關聯

Create Storage Virtual Machine Associations（建立儲存虛擬機器關聯）精靈可讓合作夥伴保護應用程式將來源儲存VM與目的地儲存VM建立關聯、以便與SnapMirror和SnapVault 相依關係搭配使用。合作夥伴應用程式在初始配置目的地磁碟區時、會使用這些關聯來決定要選擇哪些資源。dd

.開始之前
* 您正在關聯的儲存VM必須已經存在。
* 您必須具有應用程式管理員或儲存管理員角色。


對於任何來源儲存VM和關係類型、您只能在每個目的地叢集上選擇一個目的地儲存VM。

使用刪除和建立功能變更關聯只會影響未來的資源配置作業。它不會移動現有的目的地磁碟區。

.步驟
. 在左導覽窗格中、按一下* Protection（保護）*>* Storage VM Association*。
. 在* Storage VM Association*頁面上、按一下* Creation*。
+
「*建立儲存虛擬機器關聯*」精靈隨即啟動。

. 選取下列其中一個來源：
+
** *任何*
+
如果您想要在任一主要儲存VM來源與一或多個目的地儲存VM之間建立關聯、請選擇此選項。這表示目前需要保護的所有現有儲存VM、以及未來建立的任何儲存VM、都會與指定的目的地儲存VM相關聯。例如、您可能希望不同位置的多個不同來源的應用程式、在同一個位置備份到一個或多個目的地儲存VM。

** *單一*
+
若要選取與一或多個目的地儲存VM相關聯的特定來源儲存VM、請選擇此選項。例如、如果您要提供儲存服務給許多用戶端、而這些用戶端的資料必須彼此分開、請選擇此選項、將特定的儲存VM來源與僅指派給該用戶端的特定儲存VM目的地建立關聯。

** *無（外部）*
+
如果您想要在來源儲存VM和目的地儲存VM的外部彈性Volume之間建立關聯、請選擇此選項。



. 選取您要建立的一種或兩種保護關係類型：
+
** * SnapMirror *
** *《*》SnapVault


. 單擊 * 下一步 * 。
. 選取一個或多個儲存VM保護目的地。
. 單擊*完成*。




== 刪除儲存VM關聯

您可以刪除合作夥伴應用程式的儲存VM關聯、以移除來源與目的地儲存VM之間的二線資源配置關係；例如、當目的地儲存VM已滿且您想要建立新的儲存VM保護關聯時、您可以這麼做。

.開始之前
您必須具有應用程式管理員或儲存管理員角色。

在至少選取一個儲存VM關聯之前、*刪除*按鈕會停用。使用刪除和建立功能變更關聯只會影響未來的資源配置作業、而不會移動現有的目的地磁碟區。

.步驟
. 在左導覽窗格中、按一下* Protection（保護）*>* Storage VM Association*。
. 請至少選取一個儲存VM關聯。
+
*刪除*按鈕已啟用。

. 按一下*刪除*。*
+
此時會顯示警告對話方塊。

. 按一下「*是*」繼續。
+
選取的儲存VM關聯會從清單中移除。


