---
permalink: data-protection/reference_create_storage_virtual_machine_associations_wizard.html 
sidebar: sidebar 
keywords: create, storage, virtual machine, peers, wizard 
summary: Create Storage Virtual Machine Peers（建立儲存虛擬機器對等端點）精靈可讓您對等來源和目的地儲存VM、以用於SnapMirror和SnapVault 各種保護關係。 
---
= Create Storage Virtual Machine對等端點精靈
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create Storage Virtual Machine Peers（建立儲存虛擬機器對等端點）精靈可讓您對等來源和目的地儲存VM、以用於SnapMirror和SnapVault 各種保護關係。



== 選取來源

「選取來源」面板可讓您選取儲存VM對等端點中的來源或主要儲存VM。

* *任何*
+
可讓您在任何儲存VM來源之間建立對等端點、以連接到一個或多個目的地、或是次要儲存VM。這表示目前需要保護的所有現有儲存VM、以及未來建立的任何儲存VM、都會與指定的目的地儲存VM進行對等關係。例如、您可能希望不同位置的多個不同來源的應用程式、在同一個位置備份到一個或多個目的地儲存VM。

* *單一*
+
可讓您將特定來源儲存VM與一或多個目的地儲存VM對等。例如、如果您要提供儲存服務給許多用戶端、而這些用戶端的資料必須彼此分開、請選擇此選項、將特定的儲存VM來源與僅指派給該用戶端的特定儲存VM目的地建立關聯。

* *無（外部）*
+
可讓您在來源儲存VM與目的地儲存VM的外部彈性Volume之間建立關聯。

+
** 儲存虛擬機器
+
列出可用來源儲存VM的名稱

** 叢集
+
列出每個儲存VM所在的叢集



* *允許這類關係*
+
可讓您選取關聯的關聯類型：

+
** SnapMirror
+
將SnapMirror關係指定為對等項類型。選取此選項可從選取的來源複寫資料到選取的目的地。

** SnapVault
+
指定SnapVault 對等關係類型為「實體」關係。選取此選項可從選取的主要位置備份到選取的次要位置。







== 選取「保護目的地」

Create Storage Virtual Machine對等端點精靈的Select Protection Destinations（選取保護目的地）面板可讓您選取要複製或複寫資料的位置。每個叢集只能在一個目的地儲存VM上建立對等端點。



== 命令按鈕

命令按鈕可讓您執行下列工作：

* *下一步*
+
將您移至精靈的下一頁。

* *返回*
+
返回精靈的上一頁。

* *完成*
+
套用您的選擇並建立關聯。

* *取消*
+
捨棄選取項目並關閉「建立儲存虛擬機器對等端點」精靈。


