---
permalink: data-protection/task_reverse_protection_relationships.html 
sidebar: sidebar 
keywords: reverse, protection, relationships, volume, relationships page 
summary: 當災難停用保護關係中的來源磁碟區時、您可以在修復或更換來源時、將目的地磁碟區轉換成讀寫磁碟區、以使用目的磁碟區來提供資料。當來源再次可供接收資料時、您可以使用反轉重新同步作業、以相反方向建立關係、將來源上的資料與讀取/寫入目的地上的資料同步。 
---
= 從「Volume關係」頁面反轉保護關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當災難停用保護關係中的來源磁碟區時、您可以在修復或更換來源時、將目的地磁碟區轉換成讀寫磁碟區、以使用目的磁碟區來提供資料。當來源再次可供接收資料時、您可以使用反轉重新同步作業、以相反方向建立關係、將來源上的資料與讀取/寫入目的地上的資料同步。

.開始之前
* 您必須具有應用程式管理員或儲存管理員角色。
* 您必須設定Workflow Automation。
* 這種關係絕不SnapVault 能是根本的關係。
* 保護關係必須已經存在。
* 保護關係必須中斷。
* 來源和目的地都必須在線上。
* 來源不可是其他資料保護磁碟區的目的地。
* 當您執行此工作時、會刪除來源上比一般Snapshot複本資料新的資料。
* 在反向重新同步關係上建立的原則和排程、與原始保護關係中建立的原則和排程相同。
+
如果原則和排程不存在、就會建立它們。



.步驟
. 從「* Volume Relationationation*」頁面中、選取一個或多個與您要反轉關係的磁碟區、然後在工具列上按一下「* Reverse Resynation*」。
+
此時會顯示「反轉重新同步」對話方塊。

. 確認「*反轉重新同步*」對話方塊中顯示的關係是您要執行反轉重新同步作業的關係、然後按一下「*提交*」。
+
反轉重新同步作業隨即啟動、您會返回「Volume Relationships」（磁碟區關係）頁面、頁面頂端會顯示工作連結。

. *選用：*按一下「* Volume Relationation*」頁面上的*「View jobs」（檢視工作）、即可追蹤每個反轉重新同步工作的狀態。
+
隨即顯示與此作業相關的篩選工作清單。

. *可選：*單擊瀏覽器上的*上一頁*箭頭返回* Volume Relationationation*頁面。
+
當所有工作任務成功完成時、反轉重新同步作業即告完成。


