---
permalink: data-protection/task_create_storage_virtual_machine_svm_associations.html 
sidebar: sidebar 
keywords: create, storage, vm, peers 
summary: Create Storage Virtual Machine對等端點精靈可讓合作夥伴保護應用程式將來源儲存虛擬機器與目的地儲存虛擬機器建立關聯、以便與SnapMirror和SnapVault 相依關係搭配使用。合作夥伴應用程式在初始配置目的地磁碟區時、會使用這些關聯來決定要選擇哪些資源。 
---
= 建立儲存VM對等端點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Create Storage Virtual Machine對等端點精靈可讓合作夥伴保護應用程式將來源儲存虛擬機器與目的地儲存虛擬機器建立關聯、以便與SnapMirror和SnapVault 相依關係搭配使用。合作夥伴應用程式在初始配置目的地磁碟區時、會使用這些關聯來決定要選擇哪些資源。

*您需要的是什麼*

* 您正在關聯的儲存VM必須已經存在。
* 您必須具有應用程式管理員或儲存管理員角色。


對於任何來源儲存VM和關係類型、您只能在每個目的地叢集上選擇一個目的地儲存VM。

使用刪除和建立功能變更關聯只會影響未來的資源配置作業。它不會移動現有的目的地磁碟區。

.步驟
. 在左導覽窗格中、按一下* Protection（保護）*** Storage VM對等端點*。
. 在「* SVM對等端點*」頁面中、按一下「*建立*」。
+
隨即啟動Create Storage Virtual Machine對等端點精靈。

. 選取下列其中一個來源：
+
** *任何*
+
如果您想要在任一主要儲存VM來源與一或多個目的地儲存VM之間建立關聯、請選擇此選項。這表示目前需要保護的所有現有儲存VM、以及未來建立的任何儲存VM、都會與指定的目的地儲存VM相關聯。例如、您可能希望不同位置的多個不同來源的應用程式、在同一個位置備份到一個或多個目的地儲存VM。

** *單一*
+
若要選取與一或多個目的地儲存VM相關聯的特定來源儲存VM、請選擇此選項。例如、如果您要提供儲存服務給許多用戶端、而這些用戶端的資料必須彼此分開、請選擇此選項、將特定的儲存VM來源與僅指派給該用戶端的特定儲存VM目的地建立關聯。

** *無（外部）*
+
如果您想要在來源儲存VM和目的地儲存VM的外部彈性Volume之間建立關聯、請選擇此選項。



. 選取您要建立的一種或兩種保護關係類型：
+
** * SnapMirror *
** *《*》SnapVault


. 單擊 * 下一步 * 。
. 選取一個或多個儲存VM保護目的地。
. 單擊*完成*。

